### ISSUE TITLE
Matrix factorization

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#10]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

A common analysis is the factorization of timeseries matrizes via PCA, NMF, SVD, CUR etc. matrix factorizations. These decompositions often result in the creation of typically 2-3 matrices, one for row-space, column-space, and weights. It is unclear where and how to store this kind of analysis right now.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/10

**Comment by oruebel** [comment]
Moved this issue to the nwb-schema issue tracker: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/47
