### ISSUE TITLE
schema/api discrepancy: volts is default_value of ElectricalSeries.unit

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1005]
## 1) Bug

`'volts'` is `default_value` of `ElectricalSeries.unit`([here](https://github.com/NeurodataWithoutBorders/pynwb/blob/80043843d074942f1be286b7e5661457052636cf/src/pynwb/data/nwb.ecephys.yaml#L34)), but in API it is programmed as if it were `value`([here](https://github.com/NeurodataWithoutBorders/pynwb/blob/80043843d074942f1be286b7e5661457052636cf/src/pynwb/ecephys.py#L96)) with no way for the user to change the unit.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Shouldn't ElectricalSeries always be in Volts? If so, the schema should be changed so that instead of `default_value: Volt`, it is `value: Volt`.

**Comment by bendichter** [comment]
Yeah I'd be fine with going that way too, I just don't like discrepancies between the API and the spec.  I can't think of any reason why the unit wouldn't be volts. Technically that would be a schema breaking change, but I don't think it would matter much since the API has been enforcing that all along. However I think we should be consistent with whether we use the singular or the plural of SI terms. `SpatialSeries` has the same issue, and is enforcing "meters". I think the plural form is more natural.

**Comment by rly** [comment]
See also: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/277

I would be fine with the plural form. Now that I'm revisiting it, it does feel more natural that way.

**Comment by oruebel** [comment]
Changing the behavior to always use ``Volts`` seems reasonable in this case (even though it is technically a breaking change, I don't think it actually breaks anything).
