### ISSUE TITLE
Remove ability to set IZeroClampSeries.bias_current and other args, which should be 0

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1013]
The documentation for `IZeroClampSeries` says that all `CurrentClampSeries` fields such as `bias_current`, `bridge_balance`, and `capacitance_compensation` will be zero, but currently they can be passed in to override the default 0.0. It seems to me that these values should be fixed and not allowed as constructor args. i.e. remove the following docval entries on `IZeroClampSeries.__init__`:
https://github.com/NeurodataWithoutBorders/pynwb/blob/12613e518183dcf6d912b7bb1ca05d35b338256f/src/pynwb/icephys.py#L211-L213
and hard code zeros for those values, i.e.:
```python
def __init__(self, **kwargs):
        name, data, unit, electrode, gain = popargs('name', 'data', 'unit', 'electrode', 'gain', kwargs)
        bias_current, bridge_balance, capacitance_compensation = (0.0, 0.0, 0.0)
        super(IZeroClampSeries, self).__init__(name, data, unit, electrode, gain, bias_current,
                                               bridge_balance, capacitance_compensation, **kwargs)
```
This follows the precedence of hard coding fixed values in `__init__`, e.g. `ElectricalSeries.unit` is hard coded to be 'volts'.

@t-b I think you developed these. Is this appropriate?

**Comment by t-b** [comment]
@rly Totally these should not be settable in the constructor.

**Comment by bendichter** [comment]
@t-b icephys isn't my field. Could you help by explaining a little more about these fields? Why do we have them if they are just set to zero? Do you think it's likely that another user might want to set these values to something other than zero?

**Comment by rly** [comment]
@bendichter IIRC, the IZeroClampSeries is a special case of CurrentClampSeries that represents a CurrentClampSeries when the recording is off. Kind of like a Triangle class could extend a Polygon class and have num_sides fixed to 3. 

This change was pushed through in #999.
