### ISSUE TITLE
electrode_group/device inconsistency

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1025]
## 1) Bug

electrode_group/device is listed in the YAML as an optional link:
https://github.com/NeurodataWithoutBorders/pynwb/blob/0eea97e520e3a9a728c017ee734e756799defcf3/src/pynwb/data/nwb.ecephys.yaml#L348-L352

However in the pynwb API it is not optional:
https://github.com/NeurodataWithoutBorders/pynwb/blob/2cd77132b53f6739db16ea96a29ea6a0d24335ae/src/pynwb/ecephys.py#L16-L28

Was there a reason this was made optional? Anyone using python has been forced to include it, and it hasn't seemed to cause any problems. 

Our options are:

1. Make it required in the YAML. This would technically be a breaking change, but only for people who are working outside of python.

2. Make it optional in the API. This could make it difficult to make sense of data.

I have a slight preference for 1. Thoughts?

**Comment by rly** [comment]
Good catch. I prefer 1.

We should generate template classes from the schema and diff them with the API to check for other mismatches. I found a few mismatches on my last read through of the schema but probably did not catch them all.

**Comment by rly** [comment]
@oruebel @ajtritt thoughts on option 1 vs 2?

**Comment by oruebel** [comment]
I agree, Option 1 (make Device required in the schema) seems the best solution in this case. While technically breaking, I don't think in reality it breaks anything and can be done as bug-fix release. 

I created https://github.com/NeurodataWithoutBorders/nwb-schema/issues/287 to make sure we add this to the release notes.
