### ISSUE TITLE
Object_id is not unique to object data

### ISSUE THREAD

**Issue by sgratiy** [NeurodataWithoutBorders/pynwb#1041]
## 1) Bug
Object id are not unique to the object data. If two object with the same data are created, the object_ids will be different. 

## Steps to Reproduce
```
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
from pynwb import TimeSeries

start_time = datetime(2017, 4, 3, 11, tzinfo=tzlocal())
create_date = datetime(2017, 4, 15, 12, tzinfo=tzlocal())
data = list(range(100, 200, 10))
timestamps = list(range(10))


nwbfile1 = NWBFile(session_description='demonstrate NWBFile basics',
                  identifier='NWB123',
                  session_start_time=start_time,
                  file_create_date=create_date)
test_ts1 = TimeSeries(name='test_timeseries', data=data, unit='m', timestamps=timestamps)


nwbfile2 = NWBFile(session_description='demonstrate NWBFile basics',
                  identifier='NWB123',
                  session_start_time=start_time,
                  file_create_date=create_date)
test_ts2 = TimeSeries(name='test_timeseries', data=data, unit='m', timestamps=timestamps)


#assert nwbfile1.object_id==nwbfile2.object_id
# or
assert test_ts1.object_id==test_ts2.object_id
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda 
- **Python Version:** Python  3.6
- **Operating System:**  Linux
- **PyNWB Version:**  1.0.3

## 2) Feature Request
I realize that object_ids are different because I created two different objects which happen to have the same data. However, this becomes a problem for regression testing when comparing files created from the same data. 

### Problem/Use Case
I am trying to use h5diff in my tests, which fails because of object_id differences. I am not sure how else then to do regression testing. I cannot exclude object_ids from comparison or opt out of creating object_id. 
#
## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
See some suggestion here: https://github.com/NeurodataWithoutBorders/pynwb/pull/991#issuecomment-522685575
