### ISSUE TITLE
Clean up Retinotopy classes

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1053]
https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/retinotopy.py

- [ ] PyNWB requires a `unit` for the sign_map. unit is not part of the specification for sign_map. 
- [ ] PyNWB requires a `focal_depth` for the vasculature_image. focal_depth is not part of the specification for vasculature_image
- [ ] AImage is not an informative class name
- [ ] AImage should extend GrayscaleImage
- [ ] AxisMap should extend NWBData
- [ ] See also changes proposed in https://github.com/NeurodataWithoutBorders/nwb-schema/issues/303

**Comment by stephprince** [comment]
This issue was closed by https://github.com/NeurodataWithoutBorders/pynwb/pull/1813 which deprecated the ImagingRetinotopy module.
