### ISSUE TITLE
nwb version hard coded in file.py

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#107]
Version is stated as 1.0.6 here:

https://github.com/NeurodataWithoutBorders/pynwb/blob/b0f263c2c6456d576c438ed3a5a9ccc6de7d5ad1/src/pynwb/file.py#L36

I think this is an old reference to a schema version, but this should be handled differently, (possibly loading from nwb.namespace.yaml?).  

Looks like API version is stored in setup.py; can this be programmatically accessed instead (i.e. from pynwb.__version__)?

**Comment by ajtritt** [comment]
resolved by #109
