### ISSUE TITLE
indexing H5DataIO

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1073]
`H5DataIO[slice]` currently throws an error. I would like it instead to call `H5DataIO.data[slice]`. 

Motivations
1. This is clearly the intention.
2. It will help with tests. I am running into an issue with the unit tests when trying to implement #1067 the unit tests break because several of them try to index `data` without checking if it's an `H5DataIO` object. With the proposed change, we can simply say something like `assert data_out[:] == data_in` and this will work whether `data_out` is a `list`, `h5py.Dataset`, `np.array`, or `H5DataIO` object.

**Comment by oruebel** [comment]
This should be implemented in HDMF on the DataIO base class. The following PR on HDMF should fix this issue:

https://github.com/hdmf-dev/hdmf/pull/141

**Comment by rly** [comment]
@bendichter I believe this has been resolved. Please close if so.
