### ISSUE TITLE
Save specs in NWB file

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#108]
When an NWBFile gets written, the specifications used to generate that file should be written to the file to ensure that the file is readable on its own. 

- [x] write specs to file
- [x] read specs from file

**Comment by oruebel** [comment]
I believe this issue is contained in #44, although we might want to update #44 (or break it up) to be more specific tasks.

**Comment by ajtritt** [comment]
duplicate of #44

**Comment by ajtritt** [comment]
duplicate of #44
