### ISSUE TITLE
Identify Interfaces that should be TimeSeries

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#11]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

For example, the FeatureExtraction Interface stores time series data, and might fit better as a TimeSeries type. Are there other Interfaces where this is appropriate.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/11

**Comment by oruebel** [comment]
It appears that this issue might be Ok to address after the planed first release, given the number of other open changes.
