### ISSUE TITLE
Create testing module for test utility functions

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1107]
Requested by @bendichter and me:
It would be helpful for extension developers to be able to access some of the tests and test utility functions in the pynwb unit/integration tests, e.g., the functions for doing round-trip tests.

Numpy and xarray both have modules [numpy.testing](https://docs.scipy.org/doc/numpy/reference/routines.testing.html) and `xarray.testing` that provide basic test support. We could create modules like those, or package the unit/integration tests with the main pynwb code, e.g. have a `tests/` folder in each of the subfolders of `src/pynwb`.

**Comment by bendichter** [comment]
I think this would be really useful. This would reduce code redundancy in matnwb [here](https://github.com/NeurodataWithoutBorders/matnwb/blob/master/%2Btests/%2Bsystem/PyNWBIOTest.py) and would make it easier to write round trip tests for extensions. As it is right now, writing good round trip tests for extensions requires copy/pasting a lot of test infrastructure code

**Comment by oruebel** [comment]
Having a pynwb.testing module sounds reasonable.

**Comment by rly** [comment]
Fixed by #1117
