### ISSUE TITLE
TimeSeries.data and TimeSeries.unit should be required as per schema

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1110]
The `data` and `unit` arguments for the `TimeSeries` constructor are currently optional, but the schema says they are required.

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/base.py#L104-L107

This is allowed: `ts = TimeSeries('name', timestamps=[1, 2, 3, 4])`

This is allowed: `ts = TimeSeries('name', data=[1, 2, 3, 4], timestamps=[1, 2, 3, 4])` but generates a warning: `MissingRequiredWarning: attribute 'unit' for 'data' (TimeSeries)`

**Comment by stephprince** [comment]
Closing this issue because these examples now return errors.
