### ISSUE TITLE
SweepTable: Should store TimeSeries

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#1116]
The current SweepTable implementation suffers from a design flaw. It should not require PatchClampSeries objects but plain TimeSeries.

The reason is that we have quite often unassociated channels, aka stimulus/response not linked to a electrode, and these can currently not be added to the SweepTable.

For this the `TimeSeries` constructor will need to learn about the sweep number as well.

**Comment by bendichter** [comment]
Thanks @t-b, it looks like this is being handled in ndx-icephys-metadata

**Comment by stephprince** [comment]
Closing because SweepTable is now deprecated and stimulus/response information can be stored in the IntracellularRecordingsTable.
