### ISSUE TITLE
cannot import name 'get_build_manager'

### ISSUE THREAD

**Issue by tbenst** [NeurodataWithoutBorders/pynwb#1119]
## Description
I am trying to build 1.1.2 and am running into what appears to be https://github.com/NeurodataWithoutBorders/pynwb/issues/203. 

```
build_fake_data (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: build_fake_data (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: build_fake_data
Traceback (most recent call last):
  File "/nix/store/c2n0xp0j3nacr1l17lmrdzwp16ljsvll-python3-3.7.5/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/build/pynwb-1.1.2/tests/build_fake_data.py", line 3, in <module>
    from pynwb import NWBFile, get_build_manager
ImportError: cannot import name 'get_build_manager' from 'pynwb' (/build/pynwb-1.1.2/src/pynwb/__init__.py)


----------------------------------------------------------------------
Ran 364 tests in 63.636s

FAILED (errors=1, skipped=115)
```

I think https://github.com/NeurodataWithoutBorders/pynwb/blob/b783df5342456cba0b6fb1c6ae0eb07e4caf7f49/tests/build_fake_data.py#L3 should be `get_manager` instead. It seems like not all tests are running on CI?

**Comment by rly** [comment]
Thanks for the report @tbenst . You're correct - that is legacy dead code that will be removed in #1117. The only tests that run on CI are in `tests/unit/` and `tests/integration/` (and soon to exist `tests/back_compat/`)

**Comment by tbenst** [comment]
great thx! can confirm that tests succeed after `rm tests/build_fake_data.py tests/build_fake_extension.py`.

**Comment by rly** [comment]
The legacy file `tests/build_fake_data.py` and `tests/build_fake_extension.py` have been removed in #1117, so this is no longer an issue.
