### ISSUE TITLE
null electrode

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1120]
The Chang Lab has an interesting use-case and I'm not sure quite how to handle it. The way they record, they need to interface between the hospital setup and their own recording system, so they will often have channels that are recorded, but they are not attached to any electrode. They are just recording air and not really meaningful, but the lab does not want to get rid of these channels, because their analyses rely on the assumption that channel ordering is consistent. 

The problem is that if I am using `ElectricalSeries` and referencing channels with a `DynamicTableRegion` to `electrodes`, the width of `ElectricalSeries.data` needs to be the same as the length of `electrodes` so we know what electrode goes to what column of data. I have no way of marking a "null" electrode. It would be convenient if we had a null option here, such as -1, which indicates that this channel does not match to any electrodes. Another option, which would not require any schema changes, would be to create a row in in the electrodes table that is the "null" electrode.

What do you think? What is the best way of handling this use-case?

**Comment by oruebel** [comment]
> Another option [...] would be to create a row in in the electrodes table that is the "null" electrode.

I think that is probably the way to go.

**Comment by rly** [comment]
I agree with @oruebel here. 

In the future, it may be worthwhile to have a mapping type in the implementation of dimension coordinates such that one dimension of a dataset can be arbitrarily mapped to a dimension of another dataset and the map is stored in a separate 1D dataset.

**Comment by bendichter** [comment]
Seems like we have consensus. Thanks for the input, guys!

**Comment by bendichter** [comment]
fyi @jrliu95, @kristinksellers
