### ISSUE TITLE
TypeError using hdmf 1.4.0 when creating a NWB file

### ISSUE THREAD

**Issue by kir0ul** [NeurodataWithoutBorders/pynwb#1121]
## Description

I get a `TypeError: Expected at most 1 arguments, got 2` when I try to create an NWB file with `hdmf` version 1.4.0. But I don't get the error if I downgrade `hdmf` at version 1.3.3.
I get the following stack trace:
```
~\Desktop\calimag\preprocessing\StdFileFormatUtils.py in WriteNWB(self, filepath_out, metadata_filepath, timeseries_filepath)
     31                 "dwarves to reclaim vast treasures."
     32             ),
---> 33             session_id="LONELYMTN",
     34         )
     35 

C:\tools\Anaconda3\envs\calimag\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    459                         raise_from(ExceptionType(msg), None)
    460 
--> 461                 return func(self, **parsed['args'])
    462         else:
    463             def func_call(*args, **kwargs):

C:\tools\Anaconda3\envs\calimag\lib\site-packages\pynwb\file.py in __init__(self, **kwargs)
    296         pargs, pkwargs = fmt_docval_args(super(NWBFile, self).__init__, kwargs)
    297         pkwargs['name'] = 'root'
--> 298         super(NWBFile, self).__init__(*pargs, **pkwargs)
    299         self.fields['session_description'] = getargs('session_description', kwargs)
    300         self.fields['identifier'] = getargs('identifier', kwargs)

C:\tools\Anaconda3\envs\calimag\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    450                             enforce_type=enforce_type,
    451                             enforce_shape=enforce_shape,
--> 452                             allow_extra=allow_extra)
    453 
    454                 for error_type, ExceptionType in (('type_errors', TypeError),

C:\tools\Anaconda3\envs\calimag\lib\site-packages\hdmf\utils.py in __parse_args(validator, args, kwargs, enforce_type, enforce_shape, allow_extra)
    162         else:  # verify that the number of positional args + keyword args is <= number of docval specified args
    163             if (len(args) + len(kwargs)) > len(validator):
--> 164                 raise TypeError('Expected at most %s arguments, got %s' % (len(validator), len(args) + len(kwargs)))
    165 
    166         # iterate through the docval specification and find a matching value in args / kwargs

TypeError: Expected at most 1 arguments, got 2
```

## Steps to Reproduce

Create an NWB file [as mentioned in the documentation](https://pynwb.readthedocs.io/en/stable/tutorials/domain/ophys.html#creating-and-writing-nwb-files):
```
nwbfile = NWBFile('my first synthetic recording', 'EXAMPLE_ID', datetime.now(tzlocal()),
                  experimenter='Dr. Bilbo Baggins',
                  lab='Bag End Laboratory',
                  institution='University of Middle Earth at the Shire',
                  experiment_description=('I went on an adventure with thirteen '
                                          'dwarves to reclaim vast treasures.'),
                  session_id='LONELYMTN')
```

## Environment

    Python Version: Python 3.7.3
    Operating System: Windows
    HDMF version: 1.4.0
    PyNWB version: 1.1.2

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
@kir0ul yes, that's right. The current release of pynwb, 1.1.2, is pinned to hdmf version 1.3.3, and that specific version is specified in the pynwb requirements.

**Comment by t-b** [comment]
@bendichter But HEAD pynwb works with HEAD hdmf?

**Comment by oruebel** [comment]
PyNWB HEAD is currently pinned to ``hdmf==1.4.0``

Because changes in HDMF may require updates in PyNWB, we generally pin HDMF to a particular release of HDMF to make sure things are working and update to the current version of HDMF once all required updates in PyNWB have been completed. Usually, PyNWB HEAD is up-to-date with the latest release of HDMF but it may not always be up-to-date with the latest HDMF HEAD yet as there may still be pending PRs. We are doing our best to make sure the libraries stay in sync, but a certain lag between the HEAD of HDMF and PyNWB HEAD, is sometimes unavoidable as we need to merge and release changes in HDMF first before we can make the corresponding changes in PyNWB.

**Comment by kir0ul** [comment]
> @kir0ul yes, that's right. The current release of pynwb, 1.1.2, is pinned to hdmf version 1.3.3, and that specific version is specified in the pynwb requirements.

@bendichter Oh I see, thanks. Sorry for the noise.

**Comment by bburan** [comment]
For what it's worth, installing pynwb 1.1.2 from conda-forge pulls in hdmf 1.4.0. Downgrading to 1.3.3 does the trick. Seems to be a packaging error if conda is pulling in the wrong version of hdmf.

**Comment by rly** [comment]
Thanks, everyone. The conda packaging error should be fixed now. See https://github.com/conda-forge/pynwb-feedstock/pull/22. pynwb 1.1.2 should pull hdmf 1.3.3 and not the latest hdmf.
