### ISSUE TITLE
[documentation] candidate processing suite examples

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#113]
To help the most users understand how to get their data into NWB, I propose that we target a handful of dominant preprocessing pipelines (that is, spike sorting & calcium segmentation/ trace extraction) & give examples of getting that data into NWB.

- One of the pain points of getting data into NWB is accounting for provenance information related to a processing pipeline (i.e. saving the ROI and neuropil subtraction in addition to the calcium traces)
- While we won't promise a script that does a conversion, this should help get users that use these existing processing pipelines 90% of the way there.
- Each of these pieces of software outputs a fairly standardized set of files.

I'd like to brainstorm and identify a handful of target "sources" for ingest into NWB.

We can then either write examples ourselves or solicit the developers of the respective tools to contribute.

My initial brainstorm:

**kilosort / phy TemplateGUI**
This is the dominant spike sorting software for dense ephys recordings. 
- **modality**: ephys
- **output files**: npy & tsv
- **docs on outputs**: http://phy-contrib.readthedocs.io/en/latest/template-gui/#analysis
- **developers**: @kwikteam

**suite2p**
AFAIK, this is the dominant segmentation and trace extraction processing software around right now.
- **modality**: 2P
- **output files**: mat
- **docs on outputs**: https://github.com/cortex-lab/Suite2P#iii-outputs
- **developers**: @marius10p

**Comment by oruebel** [comment]
I think that's a good idea. The more usable examples we have the better. For spike sorting other candidates may be: 1) KlustaKwik http://klusta.readthedocs.io/en/latest/  and 2) MountainSort. @neuromusic do you already have someone in mind that could help with putting these examples together?

**Comment by neuromusic** [comment]
klustakwik is a good candidate, too... that would be the KwikGUI version of phy.

**klusta(kwik) / phy KwikGUI**
This is the dominant spike sorting software for <100ch silicon ephys recordings.

- **modality**: ephys
- **output files**: Kwik format (HDF5)
- **docs on outputs**: https://github.com/klusta-team/kwiklib/wiki/Kwik-format
- **developers**: @kwikteam

I have experience with Kwik format, but I'm not actively using the format. 
We are using kilosort, so I think we need to build NWB files from this format anyway.
I don't know much about suite2p beyond the documentation, nor do I have example data.

**Comment by neuromusic** [comment]
I think a lot of folks use plexon for e.g. tetrode recording.

**Comment by neuromusic** [comment]
**Plexon Offline Spike Sorter**
This is probably the most popular spike sorting software, especially for <32ch.

- **modality**: ephys
- **output files**: plx
- **docs on outputs**: might be best to use Neo IO here http://neo.readthedocs.io/en/0.5.0/io.html#neo.io.PlexonIO
- **developers**: Plexon
- **note**: using the Neo IO here would effectively provide a general use case for ALL ephys formats that Neo supports. see also: https://github.com/NeuralEnsemble/python-neo/issues/221

**Comment by rly** [comment]
Conversion of processed data to NWB is being handled and documented by https://neuroconv.readthedocs.io/en/main/. Processing tools are listed now in https://nwb-overview.readthedocs.io/ including some example scripts provided by the tools themselves.
