### ISSUE TITLE
Incompatible with HDMF 1.5.0 - fix here or in hdmf?

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#1133]
## Description

Currently pynwb hardcodes 
```
$> grep hdmf requirements*
requirements.txt:hdmf==1.4.0
```
but there is 1.5.0 release of hdmf.  Apparently that release breaks compatibility with pynwb, e.g.

```
======================================================================
ERROR: pynwb (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: pynwb
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/yoh/deb/gits/pkg-exppsy/build-area/pynwb-1.1.2/.pybuild/cpython3_3.7_pynwb/build/pynwb/__init__.py", line 244, in <module>
    from . import legacy  # noqa: F401,E402
  File "/home/yoh/deb/gits/pkg-exppsy/build-area/pynwb-1.1.2/.pybuild/cpython3_3.7_pynwb/build/pynwb/legacy/__init__.py", line 3, in <module>
    from .map import ObjectMapperLegacy as ObjectMapper
  File "/home/yoh/deb/gits/pkg-exppsy/build-area/pynwb-1.1.2/.pybuild/cpython3_3.7_pynwb/build/pynwb/legacy/map.py", line 2, in <module>
    from hdmf.build.map import ObjectMapper, TypeMap
ImportError: cannot import name 'ObjectMapper' from 'hdmf.build.map' (/usr/lib/python3/dist-packages/hdmf/build/map.py)
```
probably (didn't check) because of  https://github.com/hdmf-dev/hdmf/commit/15b8de5fbcd6f26b2877f926cd8b9888123671b6 .  I wondered to suggest compatibility import fix to hdmf, but before that decided to check here on what would be desired strategy?

**Comment by rly** [comment]
@yarikoptic A new release of pynwb that is compatible with nwb-schema 2.2.0 and hdmf 1.5.0 is pending and should be released later this week. Our current strategy is to pin each version of pynwb with a particular version of hdmf (as you noted) that we know is compatible, but we are open to other strategies as well.

**Comment by yarikoptic** [comment]
> @yarikoptic A new release of pynwb that is compatible with nwb-schema 2.2.0 and hdmf 1.5.0 is pending and should be released later this week.

awesome, thanks!

> Our current strategy is to pin each version of pynwb with a particular version of hdmf (as you noted) that we know is compatible, but we are open to other strategies as well.

Well, the only strategy I could recommend is to try to "not be special" ;) i.e., do the same as other projects/libraries do, e.g.
 
- with respect to semantic versioning - not break API without boosting major version.  Then dependent projects (e.g. `pynwb`) would just need to declare minimal required version (e.g. `hdmf>=1.4.0`) allowing for bug fix releases (e.g. `1.4.1`) and backward compatible "enhancements" extending API (e.g. what `1.5.0` could have been) without changing anything in using them projects (e.g., `pynwb`). Then, if pynwb is aware that `hdmf` would break API in incompatible way it could account for it in code or just declare `>=1.4.0,<2` or smth alike (unfortunately distutils/pypi AFAIK do not allow do declare "Break" dependencies e.g. as debian does - i.e. for HDMF 1.5.0 to say that it would break `pynwb <= 1.2` or so)
- and (or if semantic versioning is not 100% adhered to) at least having a CHANELOG file summarizing such breakages.  
- Then CI (including tox.ini) shouldn't only use pinned (guaranteed to work correctly) versions of dependencies but allow installation "as it would do by regular `pip install`, so newer scipy, pandas, etc).
   - E.g., and FWIW, in DataLad we test development `datalad` (core) against released versions of extensions, and then we test development versions of extensions against released `datalad`.  This assures that development versions of core or extensions could be used with released version (whenever possible, and otherwise not explicitly restricted). 

But given that `hdmf` is a `pynwb` "extract", I do appreciate their tight relationship.  I just hope that eventually such an umbilical cord would be cut, and `hdmf` API would eventually become more  stable and thus above suggestions could become a reality ;)

**Comment by oruebel** [comment]
@yarikoptic I think the bottom line is that we should be more strict on the versioning. I think the main difference in how we have set version numbers so far is that for version X.Y.Z we have:

* Increment Z for bug fix releases that don't change the API
* Increment Y for releases that add new features or modify the API
* Increment X that make major changes 

Part of the problem is that X would grow quite fast if we were to increment it for for every breaking change. But I agree, that once things stabilize a bit more we should move towards more strict semantic versioning.

**Comment by yarikoptic** [comment]
> * Increment Z for bug fix releases that don't change the API

so you need to keep updating the pinned version and everyone is doomed to upgrade pynwb if relevant fix in hdmf is submitted.


> is that X would grow quite fast if we were to increment it for for every breaking change

I also have a fear of big numbers (so we still have datalad at `0.`), but you must be braver than me! (you are already at `1.`!) (Composing this message in Chromium 76.0.3809.100 -- must be truly brave people).  In DataLad `0.12` would also be quite a "breaker" - but that is why we are going through a bunch of `rc` to "break it hard but once".

anyways -- the issue is closed now, so I will stop

**Comment by yarikoptic** [comment]
another observation is that with such strictly pinned versioning in pynwb, ATM  we cannot even just "pip install -e ." dandi-cli, which declares dependency on pynwb and demands some version of hdmf whic is not 1.1.2:
```shell
(git)lena:~/proj/dandi/dandi-cli[nf-macos-tests]
$> grep -e hdmf -e pynwb setup.cfg 
    pynwb >= 1.0.3,!=1.1.0
    hdmf != 1.1.2
```
but as a result, we are getting hdmf 1.5.1 and pynwb 1.2.1 installed and pip only complaining that
```
ERROR: pynwb 1.1.2 has requirement hdmf==1.3.3, but you'll have hdmf 1.5.2 which is incompatible.
```
see https://github.com/dandi/dandi-cli/pull/35/checks?check_run_id=389991990#step:4:6

Smells like some bug in pip (which we do upgrade before doing all the installation dance)... and :man_facepalming: here is the elephant (or more of a mammoth since the issue is from 2013!)  -- https://github.com/pypa/pip/issues/988 !  
So, the summary for myself and anyone (attn @satra @bendichter) would be: do not rely on pip to be able to properly satisfy versioning information, and thus better minimize and simplify any specifications (e.g. restrict to `>=`). 
My "workaround" was to remove that `hdfm != 1.1.2` and poor pip has managed "to resolve" the situation correctly (I guess -- tests passed): https://github.com/dandi/dandi-cli/pull/35. heh heh

**Comment by rly** [comment]
I've been running into the pip issue as well. `pip install pynwb` (recommended) will install the correct version of HDMF. `pip install pynwb hdmf` will result in an incompatibility error. It's frustrating that pip detects the incompatibility, but 1) doesn't fix it and 2) still exits with exit code 0. I recommend running a `pip check` after doing `pip install`, which will return a non-zero exit code if there are incompatibility errors: https://github.com/pypa/pip/issues/6969#issuecomment-531538703

The current plan for pynwb and hdmf versioning is that:
- future versions of HDMF (after 1.5.x) that break backwards compatibility will increment the major version
- future versions of PyNWB (pynwb >=1.2.0, coming soon(TM)) will set a minimum x.x.x version and a maximum major version of HDMF, e.g., `hdmf >= 1.5.2,<2`

Anytime that HDMF is updated, PyNWB will also be updated to reflect the new changes in HDMF. There may be a slight delay after HDMF is updated and before PyNWB is updated (such as the present time). If HDMF increases its minor/patch version number and a user installs the latest HDMF and latest PyNWB, then PyNWB will still work. If HDMF increases its major version number and a user installs the latest HDMF and latest PyNWB, then pip would raise the incompatibility error described above. I don't think there is a way around that, except to shorten the delay between HDMF and PyNWB releases as much as possible.

What do you think of this plan?

**Comment by yarikoptic** [comment]
Sounds good to me besides

> Anytime that HDMF is updated, PyNWB will also be updated to reflect the new changes in HDMF. 

shouldn't be necessary for fixes in hdmf which do not break compatibility with pynwb.
