### ISSUE TITLE
Define a dedicated Exception class to report missing neural datatypes

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#1144]
ATM:
```
(Pdb) p exc
KeyError("'AIBS_ecephys' not a namespace")
(Pdb) p type(exc)
<class 'KeyError'>
```
so it is a very generic `KeyError`, so until #1143 is implemented, for programmatic handling of such situations it requires regex matching of the exception message to decide that it is indeed the exception reporting missing type, and extracting the name.  Ideally it should be a dedicated exception with ease access to the name of missing type (e.g. via attribute of that exception).

**Comment by bendichter** [comment]
@yarikoptic Do you mean something like this?


```python
class HDMFMissingNamespaceException(Exception):
    def __init__(self, namespace):
        self.namespace = namespace
        super().init("'{}' not a namespace".format(namespaace))
```

**Comment by oruebel** [comment]
I would suggest transferring this issue to HDMF and potentially merging it with https://github.com/hdmf-dev/hdmf/issues/340

At that point we should also add support to add additional details to the message to allow us to address https://github.com/NeurodataWithoutBorders/pynwb/issues/1143

**Comment by bendichter** [comment]
Yes, I agree, but I don't think I have transfer permissions to that repo

**Comment by rly** [comment]
> You can only transfer issues between repositories owned by the same user or organization account.
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

I will start a new issue in hdmf and link back to this.

**Comment by rly** [comment]
Scratch that. We can just add to https://github.com/hdmf-dev/hdmf/issues/340
