### ISSUE TITLE
Read capability for NWB 1.x

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#115]
Starting a list of items that will be needed to support reading of NWB 1.x files.

- [ ] Extend TypeMap to override the get_cls method. This is needed to determine the neurodata_type for GroupBuilders that don't have 2.x neurodata_type and namespace attributes.
- [ ] Create ObjectMappers for the TimeSeries and Interfaces from 1.x. These ObjectMappers should be registered with the TypeMap extension using register_map
- [ ] The TypeMap extension, once instantiated, will need to register the neurodata_types from the global TypeMap. Once this is complete, it can be used to create a BuildManager, which can be passed into HDF5IO.

**Comment by jcfr** [comment]
xref #209

**Comment by t-b** [comment]
Closed via  936c438.
