### ISSUE TITLE
File Validation Error 

### ISSUE THREAD

**Issue by MarikeReimer** [NeurodataWithoutBorders/pynwb#1166]
## Description
When I try to validate my NWB files, I get a value error for the namespace.

## Steps to Reproduce
1) Create NWB file in this tutorial:
https://pynwb.readthedocs.io/en/stable/tutorials/domain/ecephys.html#sphx-glr-tutorials-domain-ecephys-py

2) Attempt validation in Jupyter/command prompt. 

3) Observe error: 
ValueError: data type 'NWBFile' not found in namespace hdmf-common

Jupyter:
! python -m pynwb.validate ecephys_example.nwb

Command prompt:
python -m pynwb.validate ecephys_example.nwb

## Environment

    Python Executable: Python
    Python Version: Python 3.7.5
    Operating System: Windows
    HDMF Version: Version of PyNWB used: 1.1.2

## Checklist

- [ X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [X ] Have you included a brief and descriptive title?
- [ X] Have you included a clear description of the problem you are trying to solve?
- [ X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by t-b** [comment]
Is that the same as https://github.com/NeurodataWithoutBorders/pynwb/issues/1157?

**Comment by MarikeReimer** [comment]
They are both validation problems, however the error messages are
different: 

1166:

ValueError: builder for container 'root' must have data type defined
with attribute 'data_type'

1166: 

ValueError: data type 'NWBFile' not found in namespace hdmf-common 

On 2020/01/30 09:53, Thomas Braun wrote:

> Is that the same as #1157 [1]? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

  

Links:
------
[1]
https://urldefense.com/v3/__https://github.com/NeurodataWithoutBorders/pynwb/issues/1157__;!!C5qS4YX3!VUc8KJr41rt1zyX8u2hlmh-WRM0db3vxuL_QxhmFUYc8zPj9IKXukkYNqtq97uw-Dg$
[2]
https://urldefense.com/v3/__https://github.com/NeurodataWithoutBorders/pynwb/issues/1166?email_source=notifications&amp;email_token=AIPFK7HPYL6IHX7IC7MABRTRAMH2JA5CNFSM4KN2H7NKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKL5I4A*issuecomment-580375664__;Iw!!C5qS4YX3!VUc8KJr41rt1zyX8u2hlmh-WRM0db3vxuL_QxhmFUYc8zPj9IKXukkYNqtruOcaK8w$
[3]

**Comment by oruebel** [comment]
From the errors it sounds like this may have to do with move of things from PyNWB to HDMF. 

CC @rly @ajtritt f

**Comment by t-b** [comment]
I'm happy to (help) tackling that if I can get some pointers.

**Comment by oruebel** [comment]
Thanks @t-b  Luckily the hackathon is coming up next week, so if we can't get to it now, then just ping Andrew or Ryan there ;-)

**Comment by rly** [comment]
I believe this specific error will be fixed by this commit in #1167: https://github.com/NeurodataWithoutBorders/pynwb/pull/1167/commits/1e6a51304e598a1f2eca61c2feba9dd73e86864b

I believe the errors are different between this and #1157 because PyNWB 1.1.2 does not yet incorporate the recently merged PR https://github.com/NeurodataWithoutBorders/pynwb/pull/1094
