### ISSUE TITLE
Gallery/example validation tests take a long time

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1172]
With the merging of #1164, running the gallery/example test suite now runs validation CLI on the resulting files. This takes 12+ minutes, up from about 3 minutes, and significantly slows down CI, especially if we want to merge a few PRs in one sitting. 

I suggest we do the full validation suite of:
```
python -m pynwb.validate <filename>
python -m pynwb.validate --cached-namespace <filename>
python -m pynwb.validate --no-cached-namespace <filename>
python -m pynwb.validate --cached-namespace --ns <namespace> <filename>
```
on only one or two example files (particularly one with and without a cached namespace) rather than all 24 of them.

**Comment by t-b** [comment]
@rly How about only doing the validation tests for the dev branch only?

**Comment by rly** [comment]
@t-b are you suggesting doing the validation tests as is only for the dev branch? Or a much smaller subset of validation tests as I suggest above only for the dev branch?

Running all the validation tests for the dev branch would still be slow and add 9 minutes (instead of add 18 minutes) between merges, compared to before #1164. Whenever I merge a PR, I would need to wait for 1) all the tests to run on dev, including validation and 2) all the tests to run on the next PR (without validation). Is it necessary to validate all the example files in every CLI parameterization?

**Comment by t-b** [comment]
Use scheduled pipelines every night on the dev branch only.
