### ISSUE TITLE
 Avoid using `ic` as abbreviation for icephys

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#1181]
See https://github.com/oruebel/ndx-icephys-meta/issues/36.

We probably should also have `add_icephys_electrode` and show a warning for `add_ic_electrode` in pynwb. In addition the tutorials should use the the function call.

**Comment by oruebel** [comment]
@t-b sounds good. I'll address this as part of https://github.com/oruebel/ndx-icephys-meta/issues/36 Closing this issue in favor of the one on the icephys extension.

**Comment by oruebel** [comment]
This is actually hard to address in the subclass. I'm reopening this issue and will submit a PR to fix this in PyNWB directly
