### ISSUE TITLE
error when reading file with unversioned extension

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1183]
Trying to open another neuropixel file, I got that it couldn't open because the version was missing. I didn't think this through before when we decided to enforce this. I realized that writing without a version would cause an error, but did not fully appreciate that this would break read on existing Allen datasets. Can we adjust the object mapper to deal with this?

**Comment by bendichter** [comment]
@ajtritt , could you help out with this?

**Comment by ajtritt** [comment]
@bendichter  #1184 would demonstrate how to do this, but I'm not sure it's the right solution, since there is no _nwb_version_ argument to the _NWBFile_ constructor. 

Can you share the error message?

**Comment by bendichter** [comment]
TBH I was pair programing with Matt and I don't remember what file he was opening. I'll ask and try to reproduce myself

**Comment by t-b** [comment]
EDIT: wrong thread

**Comment by bendichter** [comment]
@ajtritt did you catch that this is an issue with the extension version, not the nwb-schema version? This is from one of those files that provided a non-versioned AIBS_ecephys extension

**Comment by rly** [comment]
I think reading files with unversioned extensions should be handled in the load namespaces function of HDMF. Take a look at https://github.com/hdmf-dev/hdmf/pull/292 which should fix it.
