### ISSUE TITLE
Create appveyor team to setup continuous integration

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#120]
In order to have a Appveyor organization named "NeurodataWithoutBorders", 

Here are the steps to follow:

1. Create the following gmail account like this one:

```
  email: NeurodataWithoutBorders.appveyor@gmail.com
```

2. Create an organizational Appveyor account associated with this email.

3. Add the "pynwb" project to it. Then the following URL will be valid:

   https://ci.appveyor.com/project/NeurodataWithoutBorders/pynwb

4. Add @dorukozturk and Myself (@jcfr) as collaborators (with administrative privileges) to the NeurodataWithoutBorders user

5. When completed, following this steps will allow developer signing up to their appveyor account to choose the "NeurodataWithoutBorders" team/user.

References:

* https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization
* https://github.com/scikit-build/scikit-build/issues/94#issuecomment-234357835

**Comment by jcfr** [comment]
cc: @mgrauer

**Comment by mgrauer** [comment]
Thanks @jcfr .

It is a bit unclear to me what is the next step here, is there something that someone else needs to continue with, or is this simply a record of what you have done, and the task is now complete?

**Comment by jcfr** [comment]
Apologize for the confusion, I copied the text from a previous communication and omitted to update the tense. Changing to present tense should make things clearer. 

> someone else needs to continue 

Indeed, one of the core dev should go ahead and create the email and corresponding AppVeyor account.  The idea, is to share the credential to that email account with few others  ...

**Comment by oruebel** [comment]
@dorukozturk @jcfr I've create the email and AppVeyor account. Can you send me your email addresses that I should use so that I can add to the AppVeyor

**Comment by jcfr** [comment]
Thanks @oruebel , the email associated with my appveyor account email is my kitware one.

**Comment by oruebel** [comment]
@jcfr you are now an admin on the AppVeyor. For some reason I'm having trouble adding PyNWB to account. Can you take it from here?

**Comment by jcfr** [comment]
@oruebel  I confirm I can now log to AppVeyor selecting `NeurodataWithoutBorders`. 

That said, I can not  add the project. Which is strange because the following is mentioned:

```
AppVeyor was authorized 32 minutes ago for admin:repo_hook,read:org,repo:status access to GitHub repositories as nwb-bot account
```


For @nwb-bot **GitHub** account, could you check that:
* it has access to https://github.com/NeurodataWithoutBorders/pynwb   (write access should do it)
* the account has been verified
* the https://github.com/settings/applications effectively list Appveyor

**Comment by jcfr** [comment]
You could either add the @nwb-bot user to `NWBdev` team or create a dedicated team with access to a subset of the repo.

**Comment by oruebel** [comment]
@jcfr I assume AppVeyor only needs read access, correct? @ajtritt wouldn't adding @nwb-bot to NWBdev give the bot user unwanted write access to the repo?

**Comment by jcfr** [comment]
> I assume AppVeyor only needs read access, correct?

That would be ideal, we can try this first.  In that case, you could create a `NBWbot` team

**Comment by oruebel** [comment]
Ok nwb-bot is now in NWBdev. The repos are now visible in AppVeyor.

**Comment by jcfr** [comment]
> Ok nwb-bot is now in NWBdev. The repos are now visible in AppVeyor.

Great. I was able to add the project.
