### ISSUE TITLE
Adding electrode column rel_x causes unintended behavior

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1204]
In PyNWB 1.3.0, `rel_x`, `rel_y`, `rel_z`, and `reference` were added as optional columns. However, existing code in SpikeInterface adds these columns and no longer works. See https://github.com/SpikeInterface/spikeextractors/issues/323

Adding a column that already exists in the electrodes table should raise an error. It does not do this because of a bug in how I initialized the electrodes table. I will fix that.

But more generally, when we add an optional column to a table specification, if a user adds a column with the same name, should an error or a warning be raised? If an error is raised, that kind of breaks backwards compatibility. If a warning is raised, but the behavior of the user's code is changed (e.g., the user-defined column is not added), that also breaks backwards compatibility but quietly (which seems worse!). If a warning is raised but the user's code runs as intended, then the resulting data does not conform to the new spec (which I think is even worse!)

So I think an error should be raised, and this breaking is an unfortunate consequence of updating to the new schema and PyNWB version. @oruebel @ajtritt @bendichter thoughts?

<details><summary>Offending code: (click to expand)</summary>

```python
            if nwbfile.electrodes is None or 'rel_x' not in nwbfile.electrodes.colnames:
                nwbfile.add_electrode_column('rel_x', 'x position of electrode in electrode group')
            if nwbfile.electrodes is None or 'rel_y' not in nwbfile.electrodes.colnames:
                nwbfile.add_electrode_column('rel_y', 'y position of electrode in electrode group')
            for m in channel_ids:
                if m not in nwb_elec_ids:
                    location = recording.get_channel_property(m, 'location')
                    while len(location) < 2:
                        location = np.append(location, [0])
                    impedence = -1.0
                    grp_name = recording.get_channel_groups(channel_ids=[m])
                    grp = nwbfile.electrode_groups[str(grp_name[0])]
                    nwbfile.add_electrode(
                        id=m,
                        x=np.nan, y=np.nan, z=np.nan,
                        rel_x=float(location[0]), rel_y=float(location[1]),
                        imp=impedence,
                        location='unknown',
                        filtering='none',
                        group=grp,
                    )
```
</details>

**Comment by oruebel** [comment]
> But more generally, when we add an optional column to a table specification, if a user adds a column with the same name, should an error or a warning be raised?

If I understand the issue correctly, then the problem is that the users added a column that previously was custom but is now part of the spec. In general, I think there are two cases: 1) the custom column the users wants to add is compliant with the schema, in which case we could should add the data and raise a DeprecationWarning to let them know to change their code or 2) the custom column has the same name as new optional column in the schema but the data is not compliant with the schema, in which case we should raise an error. I don't think this is actually breaking backwards compatibility as it only modifies custom user behavior. However, it raises the question whether we should use a major version bump for PyNWB for these changes?

**Comment by rly** [comment]
> If I understand the issue correctly, then the problem is that the users added a column that previously was custom but is now part of the spec. 

You got it. 

> In general, I think there are two cases: 1) the custom column the users wants to add is compliant with the schema, in which case we could should add the data and raise a DeprecationWarning to let them know to change their code or 

I think this is dangerous, because we do not know whether what the user intends is exactly what the new column specifies. Also, practically, I don't think it is possible to specify a data type for a user-defined column. So it would be highly unlikely that a user-defined column would perfectly match the new specification of the same column (name, description, dtype, indexed), so if we are strict with defining "compliant with the schema", then case 1 would almost never happen.

> 2) the custom column has the same name as new optional column in the schema but the data is not compliant with the schema, in which case we should raise an error. I don't think this is actually breaking backwards compatibility as it only modifies custom user behavior. However, it raises the question whether we should use a major version bump for PyNWB for these changes?

DynamicTables are designed for custom user behavior. I would call modifying custom user behavior breaking. It feels kinda silly to use a major version bump whenever we want to add optional columns to a table to help standardize them, but that is probably most appropriate.

**Comment by bendichter** [comment]
Let's just throw a warning and stick with the core. Usually this occurs
when a package is anticipating a release and leading the change, so I think
the chances of it matching the new optional column are quite high.

**Comment by luiztauffer** [comment]
Maybe it's relevant to that: 
when adding a second electrode to a table, if using any the new optionals `rel_x`, `rel_y`, `rel_z`, `reference`, an error occurs.

It manages to add the first electrode, but not the second:

```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, NWBHDF5IO
import numpy as np

nwbfile = NWBFile('abc', 'abc123', datetime.now(tzlocal()))

# Create device
device = nwbfile.create_device('device')

# Create electrode group
grp = nwbfile.create_electrode_group(
    name='elgroup',
    location='loc',
    device=device,
    description='description'
)

# Create electrodes one by one
for i in range(2):
    print('adding id: ', i)
    nwbfile.add_electrode(
        id=i,
        x=float(i), y=float(i), z=float(i),
        rel_x=float(i), rel_y=float(i), rel_z=float(i),
        reference = 'ref',
        imp=0.,
        location='unknown',
        filtering='none',
        group=grp,
    )
    print('added id: ', i)

# write
with NWBHDF5IO('example.nwb', 'w') as io:
    io.write(nwbfile)
    
# read
with NWBHDF5IO('example.nwb', 'r') as io:
    nwb2= io.read()
    print(nwb2.electrodes)
```

error:
```
adding id:  0
added id:  0
adding id:  1
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-9575fc49b679> in <module>
     28         location='unknown',
     29         filtering='none',
---> 30         group=grp,
     31     )
     32     print('added id: ', i)

~\Anaconda3\envs\spike_extract\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

~\Anaconda3\envs\spike_extract\lib\site-packages\pynwb\file.py in add_electrode(self, **kwargs)
    532                 d.pop(col_name)  # remove args from d if not set
    533 
--> 534         call_docval_func(self.electrodes.add_row, d)
    535 
    536     @docval({'name': 'region', 'type': (slice, list, tuple), 'doc': 'the indices of the table'},

~\Anaconda3\envs\spike_extract\lib\site-packages\hdmf\utils.py in call_docval_func(func, kwargs)
    362 def call_docval_func(func, kwargs):
    363     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 364     return func(*fargs, **fkwargs)
    365 
    366 

~\Anaconda3\envs\spike_extract\lib\site-packages\hdmf\utils.py in func_call(*args, **kwargs)
    481 
    482             if is_method:
--> 483                 return func(args[0], **parsed['args'])
    484             else:
    485                 return func(**parsed['args'])

~\Anaconda3\envs\spike_extract\lib\site-packages\hdmf\common\table.py in add_row(self, **kwargs)
    382                     'row data keys don\'t match available columns',
    383                     'you supplied {} extra keys: {}'.format(len(extra_columns), extra_columns),
--> 384                     'and were missing {} keys: {}'.format(len(missing_columns), missing_columns)
    385                 ])
    386             )

ValueError: row data keys don't match available columns
you supplied 0 extra keys: set()
and were missing 4 keys: {'rel_z', 'rel_y', 'reference', 'rel_x'}
```

**Comment by bendichter** [comment]
@rly can you look at Luiz's code? It looks like you can't use `rel_x`, `rel_y`, `rel_z` at all in the latest version.
