### ISSUE TITLE
https://pynwb.readthedocs.io/en/latest/ is outdated

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#1206]
At least the title is set to

```html
<title>NWB for Python &mdash; PyNWB 1.3.0 documentation</title>
```

which is not correct.

**Comment by rly** [comment]
@t-b I think that is correct. PyNWB - the software - is at version 1.3.0. The NWB schema is at 2.2.2.

**Comment by t-b** [comment]
@rly Dooh! Sorry for the noise.
