### ISSUE TITLE
Suggestion: Keep release notes in local CHANGELOG.md and not (only) on github releases

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#1207]
I needed to know since which version of pynwb, use of `object_id` was introduced... and I could not find **any** changelog within pynwb.  Then I decided to look at https://github.com/NeurodataWithoutBorders/pynwb/releases where you have it (so only github has it). So it seems to be just a matter of adjusting a workflow.  Instead of preparing changelog on github releases, why not to keep it e.g. within CHANGELOG.md (as majority of projects do) and then copy/paste into your release notes on github? Somewhat alternatively, if you tag release "locally" with an annotated tag (which you already do -- signed tags), where you embed corresponding release section, "Edit tag" for the release and "Save" would populate it on github releases.   That is what I tend to do but difficulty is that while preparing tag text in editor git treats lines starting with '#' as comments.

**Comment by rly** [comment]
Yes, moving the release notes to CHANGELOG.md makes a lot of sense and we should have been doing that before -- it was just convenient to put it with the GitHub release tag. The release notes should also be included on the PyNWB readthedocs page.

Regarding tag text -- our workflow involves use of CI and a [third-party tool](https://pypi.org/project/githubrelease/) to make the release. Then I go in and edit the tag text on GitHub. I will have to look into changing our workflow to allow annotated tags with the release notes there, but that is lower priority.
