### ISSUE TITLE
Error updating specification of older files during pynwb.NWBHDF5IO.write()

### ISSUE THREAD

**Issue by MatthewAitken** [NeurodataWithoutBorders/pynwb#1228]
## Description

When appending data to an NWB file that was written prior to the hdmf-common-schema 1.1.3, updating the specification causes a shape error. Prior to 1.1.3, shape was determined by h5py, but after 1.1.3 shape is set to (). When the specification updates, this error occurs (specifically when updating specifications/core/2.2.4/namespace). The old spec had the shape (1,), while the new spec has the shape ().

```
File "/opt/anaconda3/envs/ipfx/lib/python3.8/site-packages/h5py/_hl/group.py", line 198, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (1,) vs new ())
```

## Steps to Reproduce
Write a file with Pynwb<=1.0.2 which will use hdmf<=1.0.1 
Then in Pynwb > 1.0.2 (I used PyNWB 1.3.0)
```python
import pynwb


fname = 'previous.nwb'

with pynwb.NWBHDF5IO(fname, 'a') as io:
    nwbfile = io.read()
    io.write(nwbfile)
```
## Environment

    Python Executable: Python
    Python Version: Python 3.6 and 3.7
    Operating System: macOS and Linux
    HDMF Version: Pynwb<=1.0.2 with hdmf<=1.0.1 and Pynwb > 1.3.0

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by t-b** [comment]
I can't reproduce that here using only pynwb.

Things to check:
- Are using a previous NWB file not generated using pynwb? Maybe from MIES/IPNWB?
- If you are using a local git checkout are you sure you've updated the nwb-schema submodule to the correct version?

Here is what I did:

```
virtualenv ~/.pynwb-1.0.2
source ~/.pynwb-1.0.2/bin/activate
pip install pynwb==1.0.2 hdmf==1.0.1
python icephys.py
virtualenv ~/.pynwb-1.3.0
source ~/.pynwb-1.3.0/bin/activate
pip install pynwb==1.3.0 hdmf==1.6.1
python recipe.py
```

recipe.py:

```python
import pynwb

fname = 'icephys_example.nwb'

with pynwb.NWBHDF5IO(fname, 'a') as io:
    nwbfile = io.read()
    io.write(nwbfile)
```

Screenshot from silx view:
![grafik](https://user-images.githubusercontent.com/1185677/81316300-b7662500-908b-11ea-8cc1-dde72d719688.png)

icephys.py and final icephys_example.nwb
[icephys.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/4594107/icephys.zip)

**Comment by t-b** [comment]
So the problem is only there if the original file was written by MIES.

Here is the full stacktrace:
```
Traceback (most recent call last):
  File "recipe.py", line 7, in <module>
    io.write(nwbfile)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 297, in write
    ns_builder.export('namespace', writer=writer)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\utils.py", line 483, in func_call
    return func(args[0], **parsed['args'])

  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\spec\write.py", line 213, in export
    writer.write_spec(out, path)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5_utils.py", line 280, in write_spec
    return self.__write(spec, path)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\hdmf\backends\hdf5\h5_utils.py", line 276, in __write
    dset = self.__group.require_dataset(name, shape=tuple(), data=data, dtype=self.__str_type)
  File "C:\users\thomas\Anaconda3\envs\pynwb\lib\site-packages\h5py\_hl\group.py", line 198, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing (1,) vs new ())
```

and an example file -> [HardwareTests-V2.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/4595691/HardwareTests-V2.zip)
