### ISSUE TITLE
load_namespaces assumes an h5 file on disk

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#1232]
## Description

If an NWBHDFIO is constructed by passing an h5py.File to its file parameter, it should use that file for all of its IO operations, rather than opening a new one from the argued path. [`load_namespaces`](https://github.com/hdmf-dev/hdmf/blob/bd2b00541cd47b37ddb7bbbafd08059a8b875866/src/hdmf/backends/hdf5/h5tools.py#L91) tries to open `path` as a new h5 file, rather than using the provided file object, which fails if the h5py.File is not backed by a file on disk.

This problem originates in hdmf, but fixing it will require a small synchronized change to pynwb, so I am just opening the one issue here.

## Steps to Reproduce

```
from io import BytesIO
from datetime import datetime

from pynwb import NWBHDF5IO, NWBFile
import h5py


def main():

    path = "fish.nwb"

    nwbfile = NWBFile(session_description="repro", identifier="fish", session_start_time=datetime.now())
    with NWBHDF5IO(path, "w") as writer:
        writer.write(nwbfile)

    with open(path, "rb") as raw_file:
        buffer = BytesIO(raw_file.read())
        file_obj = h5py.File(buffer)
    
    with NWBHDF5IO(file_obj.filename, "r", file=file_obj, load_namespaces=True) as reader:
        obtained = reader.read()
        print(obtained.identifier)  # prints "fish" if load_namespaces is False

if __name__ == "__main__":
    main()
```

## Environment

pynwb 1.3.0, hdmf 1.6.1, python 3.7.6, ubuntu 20.04

**Comment by rly** [comment]
Good point, and should be an easy fix. I'll take a look.

**Comment by NileGraddis** [comment]
@rly thanks for the rapid fix to hdmf! I think a companion change to [this line](https://github.com/NeurodataWithoutBorders/pynwb/blob/dad658a99e01d5edcd84b56c22e5dc26b4425a31/src/pynwb/__init__.py#L230) might be needed to get this working in pynwb
