### ISSUE TITLE
cannot create an ROI with a timeless ImageSeries

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#124]
I'm trying to create ROIs with `pynwb.ophys.ROI` & there is a required attribute `reference_images`

`pynwb.ophys.ROI` describes this required attribute... 

```
reference_images (ImageSeries) – One or more image stacks that the masks apply to (can be oneelement stack).
```

So it looks like I have to specify an ImageSeries and that this can be a "one element stack".

I have a numpy array called `max_projection` which I want to use as the reference_image. However, when I try to create the image series...

```
max_proj = image.ImageSeries(
    name = 'Max Projection',
    source = NA,
    data = max_projection,
    unit = NA,
    format = 'raw',
)
```

I get an error that I must specify timestamps.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-87-f1b87f048d2b> in <module>()
     15     data = max_projection,
     16     unit = NA,
---> 17     format = 'raw',
     18 )
     19 

/local1/Code/pynwb/src/form/utils.pyc in func_call(*args, **kwargs)
    270                     msg = ', '.join(parse_err)
    271                     raise_from(TypeError(msg), None)
--> 272                 return func(self, **parsed['args'])
    273         else:
    274             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/image.pyc in __init__(self, **kwargs)
     52         name, source, data, unit = popargs('name', 'source', 'data', 'unit', kwargs)
     53         bits_per_pixel, dimension, external_file, starting_frame, format = popargs('bits_per_pixel', 'dimension', 'external_file', 'starting_frame', 'format', kwargs)
---> 54         super(ImageSeries, self).__init__(name, source, data, unit, **kwargs)
     55         self.bits_per_pixel = bits_per_pixel
     56         self.dimension = dimension

/local1/Code/pynwb/src/form/utils.pyc in func_call(*args, **kwargs)
    270                     msg = ', '.join(parse_err)
    271                     raise_from(TypeError(msg), None)
--> 272                 return func(self, **parsed['args'])
    273         else:
    274             def func_call(*args, **kwargs):

/local1/Code/pynwb/src/pynwb/base.pyc in __init__(self, **kwargs)
    155             self.rate_unit = 'Seconds'
    156         else:
--> 157             raise TypeError("either 'timestamps' or 'starting_time' and 'rate' must be specified")
    158 
    159         #self.fields['data_link'] = set()

TypeError: either 'timestamps' or 'starting_time' and 'rate' must be specified
```

Specifying timestamps on this image is nonsensical, as it is a computed image and has no time component.

Note: it is impossible to save calcium traces without resolving this, as ROIs are required for ImagingPlane, which is required for PlaneSegmentation, which is required for ImageSegmentation, which is required for RoiResponseSeries, which is required for DfOverF.

**Comment by oruebel** [comment]
I think the issue is that what you are trying to do is not what ROI was designed to do. ImageSeries is a TimeSeries and as such either 'timestamps' or 'starting_time' are always required. Based on this, my guess is that ROI was intended to always be based on some actual recording of an image series. This is just my guess, as this all comes from NWB 1.x.

**Comment by neuromusic** [comment]
Thanks Oliver. I'll close this issue and open one on nwb-schema

**Comment by ajtritt** [comment]
Looking over the original spec, I think we may have made a mistake when we converted the old schema to the new format. NWB 1.0 had reference_images as members of the group that we have assigned the type _PlaneSegmentation_ to. I'm guessing that got carried over into the API when David wrote up these classes.
