### ISSUE TITLE
Add documentation on PRs and preparing a release

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1244]
Preparing a release is a many step process that should be published on the PyNWB read the docs. This is a draft that I have been working with and adding to. 

TODO consult the most up-to-date software process for the schema repos and update this accordingly: https://hdmf-common-schema.readthedocs.io/en/latest/software_process.html

> 1. Update package versions in requirements.txt, requirements-dev.txt, requirements-doc.txt, requirements-min.txt
> 2. Check legal file dates and information in Legal.txt, license.txt, README.rst, conf.py, and any other locations
> 3. Review setup.py information
> 4. Check README updates
> 5. Update nwb-schema submodule. Check the version number manually. Make sure hdmf-common-schema is updated within nwb-schema.
> 6. Update relevant docs
> 7. Run tests locally
> 8. Run example and validation tests locally (the allen data download takes ~10 min)
> 9. Test docs locally (make apidoc, make html) and fix warnings/errors
> 10. Go to readthedocs build and check that the latest build succeeds:
>    https://readthedocs.org/projects/pynwb/builds/
> 11. Prepare release notes
> 12. Choose an appropriate version number
> 13. Create release by following steps in docs/source/make_a_release.rst or alias git pypi-release
> 14. Update release notes on GitHub releases page
> 15. Update conda pynwb-feedstock

**Comment by stephprince** [comment]
Closing because this documentation now exists [here](https://pynwb.readthedocs.io/en/latest/make_a_release.html).
