### ISSUE TITLE
clarification on ImageSegmentation argument

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#125]
`pynwb.ophys.ImageSegmentation` has a required attribute named "plane_segmentation"

The documentation says that this needs to be of the type "PlaneSegmentation" but describes it as "ImagePlane class"

```
plane_segmentation (PlaneSegmentation) – ImagePlane class.
```

passing in an object of the `pynwb.ophys.ImagePlane` type fails.

Is this a documentation error?

**Comment by oruebel** [comment]
The type you need to use is ```pynwb.ophys.PlaneSegmentation```. 

I'll update the docs to avoid confusion. 

Just for clarification, in the documentation the type that is required is always listed in round brackets after the name of the parameter. In this case with ```plane_segmentation (PlaneSegmentation) – ImagePlane class.```

- ```plane_segmentation``` is the name of the parameter
- ```PlaneSegmentation``` is the type of the parameter and
- the remainder is additional docs.
