### ISSUE TITLE
More informative deprecation messages

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#1259]
Currently at least some deprecation messages do not make it clear what it is that is being depreciated, forcing the user to look into the code. It would be useful to add information about the command that is deprecated. See examples below

`Users/loren/opt/anaconda3/envs/nwbdj/lib/python3.7/site-packages/pynwb/file.py:404:` DeprecationWarning: replaced by NWBFile.processing
  warn("replaced by NWBFile.processing", DeprecationWarning)

**Comment by bendichter** [comment]
@lfrank is #1261 along the lines you were thinking?

**Comment by lfrank** [comment]
@bendichter Yes, very much so. Thanks...
