### ISSUE TITLE
If ImageSeries external_file is provided, starting_frame should be required

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1263]
## Description

In the NWB schema, `starting_frame` is a required attribute of `external_file` which is an optional dataset of `ImageSeries`. If `external_file` is provided, PyNWB should enforce that `starting_frame` is provided.

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.5, 3.6, or 3.7
    Operating System: Windows, macOS or Linux
    HDMF Version: Version of PyNWB used

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
I think it should have a default value of 0

**Comment by rly** [comment]
Yeah, that makes more sense than requiring it. My guess is, 95% of the time, there will be one file and the starting frame will be 0. `starting_frame` is an array, so it would actually be a default value of [0].
