### ISSUE TITLE
AnnotationSeries docstring refers to code that doesn't exist

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1273]
## Description

The docstring for AnnotationSeries says:
```
    Stores text-based records about the experiment. To use the
    AnnotationSeries, add records individually through
    add_annotation() and then call finalize(). Alternatively, if
    all annotations are already stored in a list, use set_data()
    and set_timestamps()
```

Of the four methods mentioned, only `add_annotation` exists.

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.5, 3.6, or 3.7
    Operating System: Windows, macOS or Linux
    HDMF Version: Version of PyNWB used

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by TomDonoghue** [comment]
Just a quick note (since I was looking for / through issues related to the docstrings, etc) - that I believe this issue has now been updated / resolved in the code, and so presumably can be closed.
