### ISSUE TITLE
R Wrapper?

### ISSUE THREAD

**Issue by hummuscience** [NeurodataWithoutBorders/pynwb#1278]
Dear NWB Team,

I was wondering if there is an R wrapper for the python API? I looked around Github but could not find one. If that is the case, I will attempt to write one with the hope that some people (besides me) might find it useful.

Best wishes and thank you in advance!

Muad

**Comment by oruebel** [comment]
The RAVE team https://openwetware.org/wiki/RAVE was working on accessing NWB files from R as part of the RAVE tool, but I'm not sure what the exact status of that effort is and how complete their NWB R API is. You may want to check with them to see if that will server your needs. For basic data access, some general Python/R interface methods, e.g,. https://rstudio.github.io/reticulate/ , to call PyNWB from R may also work. However, as far as I know, there are currently no full-featured wrappers of PyNWB for R.
