### ISSUE TITLE
pynwb mangles names with "/"

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#129]
on Python 2.7

I created an RoiResponseSeries and named it "dF/F"

https://gist.github.com/neuromusic/b44fa185f03b7e588af7f5e7ccb52bdd#file-ophys_example-py-L82

I can't validate the created NWB file because of #127, however, when opening with h5py, the object gets split into a hierarchy of groups "dF" & "F"

![image](https://user-images.githubusercontent.com/1245615/30826851-dace6542-a1ec-11e7-8388-80d63f54b72b.png)

**Comment by neuromusic** [comment]
the problem here is that "/" is not allowed in HDF5 group names.

one solution would be for pynwb to serialize & deserialize such names to HDF5 group names (perhaps using percent-encoding to be maximally generalizable)

**Comment by oruebel** [comment]
Another solution would be to simply make it explicit in the docs that "/" is not allowed in object names and have PyNWB raise an error/warning when it encounters a name that contains a "/". Personally, I feel that this would be a reasonable restriction.

**Comment by neuromusic** [comment]
fixed in #478
