### ISSUE TITLE
cannot add hdmf's MultiContainerInterface to NWB file

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1294]
## Description

We can now automatically generate `MultiContainerInterface` API classes in HDMF, but these new objects cannot be added to the processing module of an NWB file, because it is not one of the accepted types. The `pynwb` brand of `MultiContainerInterface` can be added to processing modules because it inherits from `NWBDataInterface`, but this new HDMF type does not.

Two possible ways to address this:
1) Make this new type one of the accepted types by adding `hdmf.container.MultiContainerInterface` as an allowed type in the docval of `ProcessingModule`
2) Make it so that `MultiContainerInterface` objects that were created using `pynwb.get_class` inherit from one of the accepted types, most likely `NWBDataInterface`

## Steps to Reproduce

```python
from hdmf.spec import GroupSpec, SpecCatalog, SpecNamespace, NamespaceCatalog
from hdmf.build import TypeMap

# create auto-generated MultiContainerInterface
CORE_NAMESPACE = 'test_core'

spec_catalog = SpecCatalog()
bar_spec = GroupSpec('A test group specification with a data type', data_type_def='Bar')
spec_catalog.register_spec(bar_spec, 'test.yaml')
namespace = SpecNamespace('a test namespace', CORE_NAMESPACE, [{'source': 'test.yaml'}],
                          version='0.1.0',
                          catalog=spec_catalog)
namespace_catalog = NamespaceCatalog()
namespace_catalog.add_namespace(CORE_NAMESPACE, namespace)
type_map = TypeMap(namespace_catalog)

multi_spec = GroupSpec('A test extension that contains a multi',
                       data_type_def='Multi',
                       groups=[GroupSpec(
                           data_type_inc=bar_spec,
                           doc='test multi',
                           quantity='*')]
                       )
spec_catalog.register_spec(multi_spec, 'extension.yaml')
Bar = type_map.get_container_cls(CORE_NAMESPACE, 'Bar')
Multi = type_map.get_container_cls(CORE_NAMESPACE, 'Multi')
multi = Multi(bars=[Bar('my_bar')])


# add MCI to NWB file
from pynwb import NWBFile
import datetime


nwbfile = NWBFile(session_description='test foraging2',
                  identifier='behavior_session_uuid',
                  session_start_time=datetime.datetime.now())

mod = nwbfile.create_processing_module('test', 'test')
mod.add(multi)
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-d387d53c934f> in <module>
     12 
     13 mod = nwbfile.create_processing_module('test','test')
---> 14 mod.add(multi)
     15 
     16 with NWBHDF5IO('/Users/bendichter/dev/sandbox/test_S10.nwb', 'w') as io:

~/dev/hdmf/src/hdmf/utils.py in func_call(*args, **kwargs)
    558         if is_method:
    559             def func_call(*args, **kwargs):
--> 560                 pargs = _check_args(args, kwargs)
    561                 return func(args[0], **pargs)
    562         else:

~/dev/hdmf/src/hdmf/utils.py in _check_args(args, kwargs)
    551                 if parse_err:
    552                     msg = '%s: %s' % (func.__qualname__, ', '.join(parse_err))
--> 553                     raise ExceptionType(msg)
    554 
    555             return parsed['args']

TypeError: MultiContainerInterface.__make_add.<locals>._func: incorrect type for 'data_interfaces' (got 'Multi', expected 'list, tuple, dict, NWBDataInterface or DynamicTable')
```

## Environment

    Python Executable: Conda
    Python Version: 3.7
    Operating System: macOS
    HDMF Version: latest
    Version of PyNWB used: latest

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
>     2\. Make it so that `MultiContainerInterface` objects that were created using `pynwb.get_class` inherit from one of the accepted types, most likely `NWBDataInterface`

Technically, I think this would be the correct solution to avoid possible issues down the road with non-compliance with the schema.

**Comment by rly** [comment]
@bendichter If you are making an extension for use in NWB, then you should use the `NWBGroupSpec` class and your new `MultiContainerInterface` subtype should inherit from `NWBDataInterface` using `neurodata_type_inc`. Similarly, any new group must inherit from `NWBDataInterface` or `NWBContainer` and any new dataset must inherit from `NWBData` for it to be used within other NWB types.

In your example, you also cannot add the `Bar` class to a processing module.

That said, I can see this behavior is not that intuitive, so we might want to raise a warning if someone tries to create an `NWBGroupSpec` or `NWBDatasetSpec` with a `neurodata_type_def` and no `neurodata_type_inc`. Or perhaps we set `neurodata_type_inc='NWBContainer'` as the default for `NWBGroupSpec` and `neurodata_type_inc='NWBData'` as the default for `NWBDatasetSpec`.

The following example works:
```python
from pynwb.spec import NWBNamespaceBuilder, export_spec, NWBGroupSpec

ns_builder = NWBNamespaceBuilder(
    doc='An NWB extension',
    name='ndx-test',
    version='0.1.0',
    author='author',
    contact='me@me.me'
)

ns_builder.include_type('NWBDataInterface', namespace='core')

bar_spec = NWBGroupSpec(
    doc='A test group specification with a data type',
    neurodata_type_def='Bar'
)

multi_spec = NWBGroupSpec(
    doc='A test extension that contains a multi',
    neurodata_type_def='Multi',
    neurodata_type_inc='NWBDataInterface',
    groups=[NWBGroupSpec(
       neurodata_type_inc=bar_spec,
       doc='test multi',
       quantity='*')]
)

new_data_types = [multi_spec, bar_spec]

# export the spec to yaml files in the spec folder
export_spec(ns_builder, new_data_types, '.')

# add MCI to NWB file
from pynwb import NWBFile, get_class, load_namespaces
import datetime

load_namespaces('ndx-test.namespace.yaml')
Bar = get_class('Bar', 'ndx-test')
Multi = get_class('Multi', 'ndx-test')


nwbfile = NWBFile(session_description='test foraging2',
                  identifier='behavior_session_uuid',
                  session_start_time=datetime.datetime.now())

mod = nwbfile.create_processing_module('test', 'test')

bar = Bar('my_bar')
multi = Multi(bars=[bar])
mod.add(multi)
```

**Comment by bendichter** [comment]
@rly oh, yes, thanks this is great! Somehow it slipped my mind that multiple inheritance would fix this.

I'll close this since the issue is fixed, but I do really like your suggestion of setting default values for `neurodata_type_inc` for the NWB spec API. If a user doesn't want those default types they can always use the hdmf versions of those functions
