### ISSUE TITLE
specify in the API class the a column is multi-indexed

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1296]
Now that we have double indexes working

https://github.com/hdmf-dev/hdmf/blob/535985ca4eafed6b5bdcd34ab3bc32000ee54a88/tests/unit/common/test_table.py#L1067-L1078

we can use this for specifying waveforms. But how do we specify this in the python API as an optional column? in `__columns__`, we can add `{'name': 'waveforms', 'description': 'snippet for each spike', 'index': True}`. That specifies a single index, but how to specify a double index? Maybe we can have `index` take an `int`, specifying the number of dimensions that are indexed?

https://github.com/NeurodataWithoutBorders/pynwb/blob/c4631e9e8e09a46e427442fd173818fb40414283/src/pynwb/misc.py#L143-L152

**Comment by bendichter** [comment]
Looks like the problem is here. Would be better if the `index` arg of `DynamicTable.add_column` could be of type `int`, which would create that many nested VectorIndex columns

https://github.com/hdmf-dev/hdmf/blob/f11185f6c899d7d7973f49dd54c918d2eb9c7e78/src/hdmf/common/table.py#L627-L636

**Comment by bendichter** [comment]
@ajtritt, what do you think about that change to DynamicTable.add_column?

**Comment by ajtritt** [comment]
@bendichter That seems like a reasonable solution.

**Comment by bendichter** [comment]
@CodyCBakerPhD can you take a stab at this?

you'll also need to add a test for this in hdmf

**Comment by CodyCBakerPhD** [comment]
@bendichter Sure thing, starting on it now
