### ISSUE TITLE
`PatchClampSeries.data` should be 1-dimensional

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1300]
## Description

The PatchClampSeries schema says:
```yaml
- name: data
  dtype: numeric
  dims:
  - num_times
  shape:
  - null
```

The `PatchClampSeries` constructor should validate the shape of the `data` argument and enforce that it is 1-dimensional. 

## Environment

    Python Executable: Python
    Python Version: Python 3.7
    Operating System: Windows
    HDMF Version: latest

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
It is also possible to write a 2D `PatchClampSeries` without error or warning. But the file does not validate.

**Comment by bendichter** [comment]
Can confirm, the following runs without error:

```python
from pynwb.icephys import PatchClampSeries, IntracellularElectrode, Device
import numpy as np

device = Device(name="device")

electrode = IntracellularElectrode(
    name="electrode",
    device=device,
    description="description",
)

pcs = PatchClampSeries(
    name="patch",
    data=np.ones((30,30)),
    unit='V',
    electrode=electrode,
    gain=np.nan,
    rate=100_000.,
)
```
