### ISSUE TITLE
Pathlib support in NWBHDF5IO

### ISSUE THREAD

**Issue by kir0ul** [NeurodataWithoutBorders/pynwb#1303]
It would be nice if the `NWBHDF5IO` class could support `pathlib.Path` objects instead strings as `path` argument.

**Describe the solution you'd like**
It would look like something like this:
```python
from pynwb import NWBHDF5IO
from pathlib import Path

nwb_path_obj = Path('example_file_path.nwb')
with NWBHDF5IO(nwb_path_obj, 'w') as io:
    io.write(nwbfile)
```

**Describe alternatives you've considered**
A simple alternative is to convert the Path objects as strings when used with `NWBHDF5IO`.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by t-b** [comment]
I don't think `instead` will work, but allowing the user to pass in `pathlib.Path` as an option sounds like a good idea. It is also present since python 3.4, so no problem on that side.

**Comment by oruebel** [comment]
Ideally, this issue should be addressed in HDMF. I opened a corresponding issue there https://github.com/hdmf-dev/hdmf/issues/439
