### ISSUE TITLE
determine if prop of pynwb cls is a child

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1304]
@luiztauffer and I would like to be able to determine if a member of `cls.__nwbfields__` is a `child` or not. For instance, looking at `pynwb.ophys.ImagingPlane`, we have:

```python
@register_class('ImagingPlane', CORE_NAMESPACE)
class ImagingPlane(NWBContainer):
    """An imaging plane and its metadata."""

    __nwbfields__ = ({'name': 'optical_channel', 'child': True},
                     'description',
                     'device',
                     'excitation_lambda',
                     'imaging_rate',
                     'indicator',
                     'location',
                     'manifold',
                     'conversion',
                     'unit',
                     'reference_frame')
    ...
```

however, when you call this programmatically, you get:

```python
from pynwb.ophys import ImagingPlane

ImagingPlane.__nwbfields__

('optical_channel',
 'description',
 'device',
 'excitation_lambda',
 'imaging_rate',
 'indicator',
 'location',
 'manifold',
 'conversion',
 'unit',
 'reference_frame')
```

The information about `'optical_channel'` having `'child': True` is no longer accessible here. Why is this the case? Is there a way of recovering this information?

**Comment by rly** [comment]
For context, what is the use case?

**Comment by bendichter** [comment]
We are trying to create a form to help people populate metadata for creation of an NWB file. In this form we want to treat links differently from objects that are contained. If an object is contained, such as an OpticalChannel, we will create a hierarchical form. If the object is linked, we will allow the user to create the object in another section of the form and link to that object in this field. We would like to be able to generate these forms directly from pynwb classes. @luiztauffer can provide an example of what the forms look like if that would be helpful.

**Comment by bendichter** [comment]
@rly is there any way to get this information programmatically from the API?

**Comment by rly** [comment]
Unfortunately, `__nwbfields__` is replaced with a tuple of field names before it is accessible. We can change that in HDMF, though. Could you open an issue in HDMF? I'll take a stab at it today.

**Comment by bendichter** [comment]
@rly ok, thanks. A minimal change might be to have a `cls.__ischild_list` prop that stores a list of all the args where `child==True`

**Comment by rly** [comment]
I believe this is now fixed. You can use `cls.get_fields_conf`. Please reopen if this is still an issue.
