### ISSUE TITLE
ScratchData notes passed as None instead of empty string in add_scratch

### ISSUE THREAD

**Issue by lvsltz** [NeurodataWithoutBorders/pynwb#1307]
## Description

If an `np.ndarray` is added in scratch with `nwbfile.add_scratch(ndarray,name='some_name'`) without a `notes` argument, `ScratchData` is created with `notes = None` and fails with
`TypeError: ScratchData.__init__: incorrect type for 'notes' (got 'NoneType', expected 'str')`

Adding something like this before https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/file.py#L695 should fix it.
```
if notes is None:
    notes = ''
```

## Steps to Reproduce

```
data = np.random.randint(0,30,(5,9))
nwbfile.add_scratch(data, name = 'some_name')
```

## Environment

    Python Executable: Conda
    Python Version: 3.7
    Operating System: Linux
    HDMF Version: pynwb 1.3.3, hdmf 1.6.4

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
Thank, @lvsltz! Looks like Ryan is on this.
