### ISSUE TITLE
CompassDirection.spatialSeries.data.unit problem

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1315]
[`CompassDirection`](https://pynwb.readthedocs.io/en/stable/pynwb.behavior.html#pynwb.behavior.CompassDirection) is a `MultiContainerInterface` that takes `SpatialSeries` objects, and specifies that these objects should have units "degrees" or "radians". `SpatialSeries` in the nwb schema provides "meters" as a default value for data.units, but pynwb's implementation hard-codes that the units must be meters. To accommodate `CompassDirection` and to be consistent with the schema, the units arg of `SpatialSeries` should be a default value of "meters" but should be changeable.

cc @weiglszonja

**Comment by bendichter** [comment]
@weiglszonja, would you be able to create a PR for this on this repo?

**Comment by weiglszonja** [comment]
@bendichter thanks for creating this issue. Yes, I will create one 👍
