### ISSUE TITLE
I am trying to test the examples in the tutorials but encountered TypeError: No conversion path for dtype: dtype('<U10')

### ISSUE THREAD

**Issue by ConBke** [NeurodataWithoutBorders/pynwb#1320]
I am trying the examples in the tutorial, but keep encountering the problem : TypeError: No conversion path for dtype: dtype('<U10') when writing files with NWBHDF5IO 
<img width="1015" alt="截屏2020-11-20 21 17 49" src="https://user-images.githubusercontent.com/57983269/99804360-db93da00-2b75-11eb-8766-a0754b4fce85.png">

The version of the packages are:
<img width="1009" alt="截屏2020-11-20 21 18 42" src="https://user-images.githubusercontent.com/57983269/99804446-fb2b0280-2b75-11eb-970f-ca8284a404f1.png">

The example in the tutorial is 
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
from pynwb import NWBHDF5IO
import numpy as np
nwbfile = NWBFile('my first synthetic recording', 'EXAMPLE_ID', datetime.now(tzlocal()),
                  experimenter='Dr. Bilbo Baggins',
                  lab='Bag End Laboratory',
                  institution='University of Middle Earth at the Shire',
                  experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
                  session_id='LONELYMTN')

from pynwb.ecephys import ElectricalSeries

rate = 10.0
np.random.seed(1234)
data_len = 1000
device = nwbfile.create_device(name='trodes_rig123')
electrode_name = 'tetrode1'
description = "an example tetrode"
location = "somewhere in the hippocampus"

electrode_group = nwbfile.create_electrode_group(electrode_name,
                                                 description=description,
                                                 location=location,
                                                 device=device)
for idx in [1, 2, 3, 4]:
    nwbfile.add_electrode(id=idx,
                          x=1.0, y=2.0, z=3.0,
                          imp=float(-idx),
                          location='CA1', filtering='none',
                          group=electrode_group)
ephys_data = np.random.rand(data_len * 2).reshape((data_len, 2))
ephys_timestamps = np.arange(data_len) / rate
electrode_table_region = nwbfile.create_electrode_table_region([0, 2], 'the first and third electrodes')
ephys_ts = ElectricalSeries('test_ephys_data',
                            ephys_data,
                            electrode_table_region,
                            timestamps=ephys_timestamps,
                            # Alternatively, could specify starting_time and rate as follows
                            # starting_time=ephys_timestamps[0],
                            # rate=rate,
                            resolution=0.001,
                            comments="This data was randomly generated with numpy, using 1234 as the seed",
                            description="Random numbers generated with numpy.random.rand")
nwbfile.add_acquisition(ephys_ts)
with NWBHDF5IO('example_file_path.nwb', 'w') as io: io.write(nwbfile)

Thank you!

**Comment by bendichter** [comment]
@ConBke looks like you are probably using h5py 3.x, which is not supported. They just released a new version, which requires a few changes on our end. See https://github.com/hdmf-dev/hdmf/issues/458 for progress on updating our libraries to this new version of h5py.

In the meantime, you should be able to solve this with`pip install h5py==2.10.0`

Thanks for submitting this. I think a few others will likely run into this problem while we make the transition, and it is nice to have it documented in the Issues

**Comment by ConBke** [comment]
> @ConBke looks like you are probably using h5py 3.x, which is not supported. They just released a new version, which requires a few changes on our end. See [hdmf-dev/hdmf#458](https://github.com/hdmf-dev/hdmf/issues/458) for progress on updating our libraries to this new version of h5py.
> 
> In the meantime, you should be able to solve this with`pip install h5py==2.10.0`
> 
> Thanks for submitting this. I think a few others will likely run into this problem while we make the transition, and it is nice to have it documented in the Issues

Thank you for you reply!
