### ISSUE TITLE
pynwb.core.MultiContainerInterface.get_fields_conf() return an empty tuple.

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/pynwb#1328]
the get_fields_conf() method returns an empty tuple for any subclass from pynwb.core.MultiContainerInterface
This affects classes such as Fluorescence, DfOverF, ImageSegmentation...

**Comment by rly** [comment]
Thanks for the report. I touched on this part of the code recently and will look into it.

**Comment by rly** [comment]
`MultiContainerInterface` uses `__clsconf__` in addition to `get_fields_conf()` when generating class attributes and methods. What are you trying to do with the fields conf and can it be done with the `__clsconf__`?

**Comment by luiztauffer** [comment]
I want to be able to tell if any fields of a class are `child=True`

**Comment by rly** [comment]
By default, when a `Container` called `container` is added to a `MultiContainerInterface` called `mci`, if `container` does not already have a parent, then it will be added to a child of `mci`. However, if `container` does have a parent, then it will be added as a link within `mci`. 

So the short answer is for a given `MultiContainerInterface` class, the container classes listed in `__clsconf__` (under the 'type' key) may be children but may also not be children. Does that help?

**Comment by luiztauffer** [comment]
that helps, thanks!
