### ISSUE TITLE
test fixtures

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1339]
A great deal of time and lines of code are dedicated to creating dummy pynwb objects for testing purposes, both within the PyNWB codebase, and outside of this codebase in other repos that rely on PyNWB. I propose we create pynwb/testing/fixtures/[module].py files that contain test versions of objects, e.g. in pynwb/testing/fixtures/file.py we would have definitions like:

```python
@pytest.fixture
def nwbfile_fixture():
    return NWBFile('aa', 'bb', datetime(1990, 1, 1))
```

(this is just for illustrative purposes, the real fixtures would be more fleshed out)

All of the other fixtures objects could be built up from other fixtures. This avoids having a lot of templating code in the tests and would make these fixture objects available for other packages to use them to write their own tests. It would also act as a central place for illustrating how to create all PyNWB objects.

@yarikoptic I know you have experience with fixtures. Does this sound like the most economical way to use them here?

**Comment by yarikoptic** [comment]
yeap -- we do have already some fixtures like that in dandi-cli, although we just generate an .nwb file but it could be an instance and it could be produced once for entire session or per test.  See e.g. https://github.com/dandi/dandi-cli/blob/master/dandi/tests/fixtures.py#L51

**Comment by bendichter** [comment]
solved with `testing.mock`
