### ISSUE TITLE
CI: Support automatic versioning using versioneer

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#137]
Currently the version is hard-coded in setup.py, the idea use [python-versioneer](https://github.com/warner/python-versioneer)

It allows to:

* have a unique version number based on the latest tag (if no tag is present, version starts with `0`)

* automatically integrate version number in source distribution

* properly label development (or nightly) release 

* simplify the release process reducing the number of actions

[Here](https://github.com/scikit-build/scikit-ci/blob/8fb1d361c36082608636311d0ed115f7b202ac25/setup.cfg#L7-L12) is example of configuration associated with `setup.cfg`

**Comment by jcfr** [comment]
@oruebel  After dev is merged to master and a release is created, we will have to tag the repository. Options are to use strings like `0.2.0` or `v0.2.0`. Which one do you prefer ?

**Comment by oruebel** [comment]
I'm ok with either format. My vote is for the variant with the `v` but either way is fine. The bigger question for me is, what version number we should use for the SfN release. For the NWB format it will be something like 2.0.0beta but I'm not sure which version we should use for PyNWB. We should discuss this during our next telecon. @ajtritt any thoughts?
