### ISSUE TITLE
Update or remove tutorial_source/convert.rst

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#1378]
## Description

The page https://pynwb.readthedocs.io/en/stable/tutorial_source/convert.html should be removed or updated. The information is outdated and it looks like the page may also not be linked in the page index, at least according to Sphinx: 

```
...pynwb/docs/source/tutorial_source/convert.rst: WARNING: document isn't included in any toctree
```

## Checklist

- [X] Have you ensured the bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Yeah, it looks like that page and the linked notebooks use functionality that has been removed or changed in PyNWB, e.g.,

```python
from pynwb.misc import UnitTimes, SpikeUnit
from pynwb.epoch import EpochTimeSeries
from pynwb.core import set_parents
```

**Comment by bendichter** [comment]
I say we remove it
