### ISSUE TITLE
Rename get_raw_timeseries

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#138]
I just checked in an example extension that writes and then reads back out a population spike train:

https://github.com/nicain/population_spike_train

I use get_raw_timeseries for the read, but this is confusing. I think this should be get_acquisition (and the add_raw_timeseries should be changed to add_acquisition).  This reflects the fields in the h5 file.

**Comment by nicain** [comment]
Also, in add_raw_timeseries https://github.com/NeurodataWithoutBorders/pynwb/blob/fbe5ef1c8582b2eb10aca562a0a58ad9dc0db8e0/src/pynwb/file.py#L279 should TimeSeries be changed to NWBContainer to allow users to add data extended from NWBContainer?

**Comment by ajtritt** [comment]
@nicain that would not be schema compliant. Right now, only TimeSeries are allowed in /acquisition. I don't see why it should be that way, but this would require modifying the schema.

**Comment by nicain** [comment]
OK, got it.

**Comment by jeffteeters** [comment]
@ajtritt you wrote:
> Right now, only TimeSeries are allowed in /acquisition. 

This does not match the schema doc because images are allowed in /acquisition, specifically in /acquisition/images.  Did you mean to write that only TimeSeries are allowed in /acquisition/timeseries?

**Comment by ajtritt** [comment]
@jeffteeters You are correct. I forgot about /acquisition/images. With that said, I would augment NWBFile.add_raw_timeseries to take a TimeSeries or an Image.

**Comment by neuromusic** [comment]
I would second @nicain 's request that this method be changed to `add_acquisition`, especially if it will accept an Image as well.

- "raw" is confusing, as there is nothing else in the spec named "raw"
- a method called "add_raw_timeseries" that accepts non-timeseries things is confusing

**Comment by CellAssembly** [comment]
I also agree with @nicain. We are trying to save simulation data using 
https://github.com/nicain/population_spike_train
And given our needs, it would be much better if we are not forced in the realm of TimeSeries (or Images) in acquisition but were given the flexibility to extend directly from NWBcontainer.
