### ISSUE TITLE
Is there a “nice” way to selectively disable tests which require network access?

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/pynwb#1412]
## Description

The test suite passes fine, but as it is run in a sandbox for the system-wide install, it fails for tests requiring network access: https://ppb.chymera.eu/069f03.log
Is there any way to easily blacklist these tests?

Just as an aside, hdf5/h5py ROS3 support is enabled.
I know some other people had issues with this, and it's the same 2 tests I'm talking about, but ROS3 is **not** the issue here, the library used for that, curl, just can't connect because it's not supposed to be able to connect.

## Environment

    Python Executable: Conda or Python
    Python Version: Python 3.9
    Operating System: Linux
    HDMF Version: `3.1.1`
    PyNWB Version: `2.0.0`

**Comment by oruebel** [comment]
For this particular case, I think it would makes sense to just automatically skip the test if DANDI is unavailable or if ROS3 is not installed. I've implemented this here https://github.com/NeurodataWithoutBorders/pynwb/pull/1414/files#diff-b66333a7080e84bd92657719668cd9fcdbe0d26b919e05d00a5bcd7acb823c54. Will this work for your case? In general, I would like to avoid adding complex configurations for unittests if possible.

**Comment by TheChymera** [comment]
@oruebel both DANDI and ROS3 support in hdf5 are available (which is why I explicitly mentioned that this is **not** related to ros3, since I see many people have difficulties getting support for this). It's just that external network connectivity is not available.

I asked since many packages have either a ~NO_NETWORK (or similar naming) environment variable, or test function definition which makes it easy to deselect network-reliant functions.
