### ISSUE TITLE
Slow loading of time intervals

### ISSUE THREAD

**Issue by jsiegle** [NeurodataWithoutBorders/pynwb#1430]
## Description

In the Allen Institute Neuropixels NWB files, information about visual stimulus presentations (trials) is stored as time intervals. I've noticed that loading the time interval data from the file can be quite slow, resulting in delays of up to a minute when querying the file for stimulus information. Fortunately this is cached by the AllenSDK `EcephysSession` object, so it only has to happen once per session. But loading the same information from a CSV is very fast, so perhaps the loading procedure can be optimized a bit more.

This issue looks like it could be a similar issue to #936, which was closed in 2019.

## Steps to Reproduce

1. Download an example session NWB file from DANDI. I used [sub-754488976_ses-771160300.nwb](https://gui.dandiarchive.org/#/dandiset/000022/draft/files?location=sub-754488976%2F)

2. Run the following code (adapted from the [implementation in the AllenSDK](https://github.com/AllenInstitute/AllenSDK/blob/328d30f69c72524d65eedb9b6bf0dfbb4b4d53f7/allensdk/brain_observatory/nwb/nwb_api.py#L75-L88)):

```python
import pynwb as nwb
import pandas as pd
import collections
import timeit

io = nwb.NWBHDF5IO('sub-754488976_ses-771160300.nwb', 'r', load_namespaces=True)
nwbfile = io.read()

def load_presentations(nwbfile):
    presentation_dfs = []
    columns_to_ignore = set(['tags', 'timeseries', 'tags_index',
                                 'timeseries_index'])
    for interval_name, interval in nwbfile.intervals.items():
        print(interval_name)
        presentations = collections.defaultdict(list)
        for col in interval.columns:
            if col.name not in columns_to_ignore:
                presentations[col.name].extend(col.data)
        df = pd.DataFrame(presentations).replace({'N/A': ''})
        presentation_dfs.append(df)
    print(len(pd.concat(presentation_dfs)))
    return presentation_dfs
        
print(timeit.timeit('load_presentations(nwbfile)', number=1, globals=globals()))
```
This loads the data for 77361 stimulus presentations in about 23 seconds on my machine. It's clear from the `print` statements that the majority of time is spent loading the movie stimuli (which have a separate row for every frame).

## Environment

    Python Executable: Conda
    Python Version: Python 3.8
    Operating System: Linux
    HDMF Version: 3.1.1
    PyNWB Version: 2.0.0

## Checklist

- [X] Have you ensured the bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
@jsiegle thanks for creating this issue and all the helpful details. I'll take a look at this during the hackathon next week.

**Comment by oruebel** [comment]
@jsiegle I did some initial testing to evaluate the performance for generating the dataframes: 1) using the function you provided, 2) using the ``DynamicTable.to_dataframe`` method from PyNWB/HDMF, and 3) loading the tables from a CSV file.

1. Using the function you provided I was able to confirm that I see similar performance on my MacBook of **~18.3s**
2. Using ``DynamicTable.to_dataframe``  performance improves for me by a factor of ~166x to around **0.11s** 
3. Loading the tables from CSV files takes around **0.6 - 0.8s** on my system (i.e., the performance seems to be slightly better but comparable to loading the tables with ``DynamicTable.to_dataframe``). 

I have not done any more in-depth performance evaluation to see what causes the function you provided to be that much slower, but hopefully the approach using ``DynamicTable.to_dataframe``   will be helpful for you. 

Here the code of how I adapted your function to use ``DynamicTable.to_dataframe``  instead:
```

def load_presentations_V2(nwbfile):
    """Alternate version of load_presentations using the to_dataframe method of DynamicTable"""
    presentation_dfs = []
    columns_to_ignore = set(['tags', 'timeseries', 'tags_index',
                             'timeseries_index'])
    for interval_name, interval in nwbfile.intervals.items():
        df = interval.to_dataframe(exclude=columns_to_ignore)
        presentation_dfs.append(df)
    return presentation_dfs
```

I then also compared the DataFrame objects generated by the two functions to make sure the two functions indeed produce the same result (see the screenshot below)

<img width="856" alt="Screen Shot 2022-02-23 at 2 43 56 PM" src="https://user-images.githubusercontent.com/10999845/155421919-4b514452-b286-4be2-af6b-2143c33cfe35.png">

Just for reference, here the full code of the notebook I used for this test

```
import pynwb as nwb
import pandas as pd
import collections
import timeit
import numpy as np

# # Open the NWB file
io = nwb.NWBHDF5IO('sub-754488976_ses-771160300.nwb', 'r', load_namespaces=True)
nwbfile = io.read()


# # Define data load functions for time intervals
def load_presentations(nwbfile):
    """Original function provided by @jsiegle"""
    presentation_dfs = []
    columns_to_ignore = set(['tags', 'timeseries', 'tags_index',
                                 'timeseries_index'])
    for interval_name, interval in nwbfile.intervals.items():
        #print(interval_name)
        presentations = collections.defaultdict(list)
        for col in interval.columns:
            if col.name not in columns_to_ignore:
                presentations[col.name].extend(col.data)
        df = pd.DataFrame(presentations).replace({'N/A': ''})
        presentation_dfs.append(df)
    #print(len(pd.concat(presentation_dfs)))
    return presentation_dfs

def load_presentations_V2(nwbfile):
    """Alternate version of load_presentations using the to_dataframe method of DynamicTable"""
    presentation_dfs = []
    columns_to_ignore = set(['tags', 'timeseries', 'tags_index',
                             'timeseries_index'])
    for interval_name, interval in nwbfile.intervals.items():
        #print(interval_name)
        df = interval.to_dataframe(exclude=columns_to_ignore)
        presentation_dfs.append(df)
    #print(len(pd.concat(presentation_dfs)))
    return presentation_dfs

def save_presentations_as_csv(df_list):
    """Save a list of dataframes to CSV files"""
    frame_files = ["dataframe_%i.csv" % i for i in range(len(df1))]
    for i, df in enumerate(df1):
        df.to_csv(frame_files[i])
    return frame_files

def load_presentations_from_csv(csv_files):
    """Load list of dataframes from csv files"""
    presentation_dfs = []
    for fn in csv_files:
        df = pd.read_csv(fn)
        presentation_dfs.append(df)
    return presentation_dfs

def compare_dataframes(df_list1, df_list2):
    """Compare all dataframes with each other to make sure that the two functions indeed produce the same result"""
    results_match = [np.all(df_list1[i] == df_list2[i]) for i in range(len(df_list1))]
    if np.all(results_match):
        print("All dataframes matched!")
    else:
        print("Only %i of %i dataframes matched" % (np.sum(result_match), len(results_match)))

# # Compare the timings of the two load functions
print(timeit.timeit('load_presentations(nwbfile)', number=1, globals=globals()))
print(timeit.timeit('load_presentations_V2(nwbfile)', number=1, globals=globals()))


# # Compare the result of the two load functions to make sure the result is the same
df1 = load_presentations(nwbfile)
df2 = load_presentations_V2(nwbfile)
compare_dataframes(df1, df2)

# # Save dataframes as CSV to compare performance
frame_files = save_presentations_as_csv(df1)
print(timeit.timeit('load_presentations_from_csv(frame_files)', number=1, globals=globals()))

# # Compare the results from the CSV to the original data
df3 = load_presentations_from_csv(frame_files)
compare_dataframes(df1, df2)
```

**Comment by oruebel** [comment]
@jsiegle ok, I think I found the the main source of the performance issue in your function. By changing the following line ```presentations[col.name].extend(col.data)``` to ```presentations[col.name].extend(col.data[:])``` performance on my system improves to ```0.232s``` for your function. That is still slower than using the ```DynamicTable.to_dataframe``` approach but still much faster than the original code. What the change does is that it loads the column data into memory in one go. My guess is that ```pd.DataFrame(presentations).replace({'N/A': ''})``` may try to load elements row-wise one-at-a-time, which in turn means lots of small I/O requests to the file.

**Comment by jsiegle** [comment]
Thanks so much for the detailed response! I can confirm that that small change dramatically decreases the loading time.

Not sure why we missed `DynamicTable.to_dataframe` when we were writing this code, that would have been a much simpler solution.

In any case, I will open a pull request to the AllenSDK to get this fixed.
