### ISSUE TITLE
cannot edit attributes of created object

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#148]
I've created an object and I want to change an attribute, but I get an error that the attribute is set and cannot be edited.

![image](https://user-images.githubusercontent.com/1245615/31100878-ff5ce4cc-a77f-11e7-9af1-1e6922f32e70.png)

Is this functionality not supported? Is there a method or function hidden somewhere that I'm missing?

**Comment by ajtritt** [comment]
Yeah, attributes that are specified by the specification can be written only once. Is there a reason you need to overwrite data?

**Comment by neuromusic** [comment]
It hasn't been written. 

I just want to be able to instantiate the object, then update it's attributes (or data) before I write it to the file.

**Comment by neuromusic** [comment]
bumping this issue

``` Python-traceback
AttributeError                            Traceback (most recent call last)
<ipython-input-10-6087a02bb97d> in <module>()
----> 1 optical_channel.description = 'this describes my data'

/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/core.pyc in _func(self, val)
    120             if nwbfield in self.fields:
    121                 msg = "can't set attribute '%s' -- already set" % nwbfield
--> 122                 raise AttributeError(msg)
    123             self.fields[nwbfield] = val
    124         return _func

AttributeError: can't set attribute 'description' -- already set
```

**Comment by neuromusic** [comment]
to clarify one use case:

- I want to create an object with mocked out attributes, then fill in the actual fields later in the script.
