### ISSUE TITLE
clarification on creating TimeSeries

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#149]
I'm trying to create a TimeSeries.

However, the docstring for the TimeSeries object in `pynwb.base` indicates the following:

```
All time series are created by calls to  NWB.create_timeseries().
They should not not be instantiated directly
```

It's not clear what "NWB" here refers to, but the example in the documentation says that this is a method on the NWBFile object:
http://pynwb.readthedocs.io/en/latest/example.html#creating-timeseries

However, my NWBFile object has no such method:
```
AttributeError: 'NWBFile' object has no attribute 'create_timeseries'
```

Are these documentation problems? Is it safe to create a timeseries directly from the base class?

**Comment by neuromusic** [comment]
@nicain tells me that I need to create an extension and define a new type of TimeSeries if my type isn't represented in the ophys/ecephys/etc modules

**Comment by nicain** [comment]
@neuromusic This is my understanding, correct.  This also means that TimeSeries should not be instantiated directly; @ajtritt is this still the intended construction?

**Comment by ajtritt** [comment]
Well, this is a little embarrassing. That's an outdated docstring. You should be instantiating TimeSeries classes directly, and using something like
```python
nwbfile.add_raw_timeseries(TimeSeries(...))
```

**Comment by nicain** [comment]
OK! Sorry to add the confusion!  Thanks!

**Comment by ajtritt** [comment]
No worries. Lets leave this open so I remember to fix this.

**Comment by neuromusic** [comment]
cool. 

So my default here should be to use TimeSeries directly. At what point should I elect to create an extension instead? When I need more arguments? When I need to constrain TimeSeries? Or if I have another class that needs to refer to this object but not general TimeSeries objects?

To give a concrete example, I have two TimeSeries I want to save: an analog signal, which is the raw voltage recorded from a running wheel, and a computed running speed.

I can save the raw signal to acquisition as a TimeSeries and use the name, source, and description fields to explain what it is. 

Or I could extend TimeSeries to create an AnalogSignal. I would probably enforce some constraints (like making it a 1-D array). I want to indicate that the running speed was computed from the analog signal, so I could then extend TimeSeries to define RunningSpeed, which gets saved in a processing module and maintains analog_signal as an attribute that points to the AnalogSignal that it was computed from.

Is this the better approach here?
