### ISSUE TITLE
[Bug]: v2.1.0 ElectrodeTable cols

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/pynwb#1497]
### What happened?

Just ran across this in the NWBInspector CI.

### Steps to Reproduce

```python
from pynwb.file import ElectrodeTable

table = ElectrodeTable(
    name="electrodes",  # default name when building through nwbfile
)
table.add_row(
    x=1.0,
    location="unknown",
    group=ElectrodeGroup(name="test_group", description="", device=Device(name="test_device"), location="unknown"),
    group_name="test_group",
)
```

### Traceback

```python
Traceback (most recent call last):

  File "C:\Users\Raven\AppData\Local\Temp\ipykernel_18220\3595234109.py", line 6, in <cell line: 6>
    table.add_row(

  File "C:\Users\Raven\.conda\envs\nwbinspector\lib\site-packages\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)

  File "C:\Users\Raven\.conda\envs\nwbinspector\lib\site-packages\hdmf\common\table.py", line 595, in add_row
    raise ValueError(

ValueError: row data keys don't match available columns
you supplied 1 extra keys: {'x'}
and were missing 0 keys: set()
```

### Operating System

Windows

### Python Executable

Python

### Python Version

3.9

### Package Versions

[environment_for_issue.txt](https://github.com/NeurodataWithoutBorders/pynwb/files/9067466/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by CodyCBakerPhD** [comment]
Or is this now intended behavior, and you're supposed to add such things as columns only (not by-row?)

**Comment by rly** [comment]
This is a bug and not intended behavior. I'll take a look.

**Comment by rly** [comment]
As an aside, because currently `ElectrodeTable` is not its own neurodata_type (yet), in PyNWB, `ElectrodeTable` is not its own class and is not meant to be initialized on its own. But I can see how that is not obvious. And since we plan to make `ElectrodeTable` its own class, this behavior will need to work anyway.
