### ISSUE TITLE
API to add datasets to NWB analysis

### ISSUE THREAD

**Issue by umayaml** [NeurodataWithoutBorders/pynwb#150]
This is a request for an api call to add datasets (TimeSeries, etc.) to analysis structure in the pynwb generated file. I have an example generated in NWB 1.0 if it would be helpful in coming up with parameters for the api.

- [ ] Update NWBFile schema to allow zero-or-more NWBContainer and zore-or-more NWBData in /analysis
- [ ] Update NWBFile Python class to read/write componenets of analysis
  - [ ] create getter/setter i.e. add the field to __nwbfields__
  - [ ] create place in the constructor for this and update the constructor to set the field using the getter
  - [ ] create a method to append new analysis objects to the object (a list or dict) containing the analysis objects

**Comment by ajtritt** [comment]
I think the best way for us to deal with this it to require that /analysis contain NWBContainer extensions. This would mean that /analysis can no longer be free-form--users would have to define extensions for the data that they are storing in /analysis.

**Comment by oruebel** [comment]
@ajtritt I agree, that makes the most sense.

**Comment by neuromusic** [comment]
on first blush, I like the idea of enforcing extensions for /analysis... what are our use-cases for /analysis? are there any uses that could not be supported by NWBContainer extensions?

**Comment by ajtritt** [comment]
Technically, datasets, but I've created a general neurodata_type called "NWBData". So, /analysis would be allowed to contain zero or more NWBContainer, and zero or more NWBData.

NWBData will be available when I finish the Restructuring of ElectrodeGroup

**Comment by nicain** [comment]
Is NWBData a neurotype in dev?  I am having trouble finding any mention of it in the spec files... should I be looking somewhere else?
