### ISSUE TITLE
HDF5IO flag when adding new datasets

### ISSUE THREAD

**Issue by umayaml** [NeurodataWithoutBorders/pynwb#151]
I'll leave it up to debate whether turning on compression should be global or not but having the option to use a compression filter when adding datasets will be really helpful in keeping the final nwb file size down to a manageable level. Thanks again for all the hard work!

**Comment by oruebel** [comment]
@umayaml allowing users to define I/O parameters (e.g., chunking, compression etc.) for datasets is useful. This will have to be on a per-dataset basis.  Enabling compression globally is not a good idea. Compression in HDF5 depends also on enabling chunking on data. Both compression and chunking can have severe impact on read/write speeds and enabling them blindly for everything is going to lead to problems very quickly. 

@ajtritt and I have talked about this before, but given the list of other todo items, I don't think this will realistically happen before SfN.

**Comment by neuromusic** [comment]
cc @dyf

**Comment by dyf** [comment]
Agreed that this doesn't need to be a requirement for the SfN release.

Some context for my use case for this feature.  Uncompressed our ephys. NWB files can be multiple gigabytes each, which becomes a usability issue for people downloading our data when we have thousands of files.  Also a nontrivial internal storage cost issue.

Either a dataset-level or global-level flag for enabling compression is fine with me.

**Comment by umayaml** [comment]
I just wanted to update this that we have a preliminary implementation of this on enh/compress branch. You have the option to wrap your data in a wrapper class and then provide a flag to have that data compressed in h5py on write out. Example:

```Python
W_ltR_data = DataIO(data=lt_R_data,compress=True)
W_ltR_timestamps = DataIO(data=lt_R_timestamps,compress=True)

lt_R_ts = TimeSeries(name="lick_trace_R", source=lab, data=W_ltR_data, timestamps=W_ltR_timestamps, unit=' ', resolution=float(0.1) )

f.add_acquisition(lt_R_ts)
```

It will use gzip to compress the data you put into a DataIO object. Tested it out and it looks like it works.
