### ISSUE TITLE
No coverage form/monitor.py, pynwb/validate.py and pynwb/io/epoch.py

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#152]
* https://codecov.io/gh/NeurodataWithoutBorders/pynwb/src/dev/src/form/monitor.py

* https://codecov.io/gh/NeurodataWithoutBorders/pynwb/src/dev/src/pynwb/validate.py

* https://codecov.io/gh/NeurodataWithoutBorders/pynwb/src/dev/src/pynwb/io/epoch.py

**Comment by nicain** [comment]
This code coverage report looks amazing!

**Comment by jcfr** [comment]
> This code coverage report looks amazing!

Thanks @nicain

Indeed, thanks to @dorukozturk , we now have consolidated coverage report across Linux, macOS and Windows.

Before adding coverage exceptions and improving existing tests, what is the status on these three files ? 

> form/monitor.py

Should the file be removed ? 

> `pynwb/validate.py`

I suggest we:

* move clis like this one under a `src/pynwb/cli`  or `src/pynwb/tool` 

* update `setup.py` to declare entry points. For example, see [here](https://github.com/scikit-build/cmake-python-distributions/blob/758e4d26e88fc4575f3f26415932231acf9a37c0/setup.py#L45-L49)

* add test using these clis and tools

> `pynwb/io/epoch.py`

Is this a duplicate of `pynwb/epoch.py` ?

Should `pynwb_tests/test_epoch.py` be updated ?

**Comment by neuromusic** [comment]
+1 for entry points
