### ISSUE TITLE
[Bug]: validation from cli results in error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1541]
### What happened?

I ran into an error when trying to run validation from command line on a small NWB test file.

### Steps to Reproduce

```python
python -m pynwb.validate /Users/bendichter/dev/matnwb/dynamic_table_tutorial1.nwb


[dynamic_table_tutorial1.nwb.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/9339916/dynamic_table_tutorial1.nwb.zip)


(the file isn't a zip file, it's just a regular NWB file. I renamed it so github would allow me to attach it)
```

### Traceback

```python
/Users/bendichter/dev/hdmf/src/hdmf/spec/namespace.py:58: UserWarning: Loaded namespace 'AIBS_ecephys' is missing the required key 'version'. Version will be set to 'None'. Please notify the extension author.
  warn(("Loaded namespace '%s' is missing the required key 'version'. Version will be set to '%s'. "
Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/bendichter/dev/pynwb/src/pynwb/validate.py", line 137, in <module>
    main()
  File "/Users/bendichter/dev/pynwb/src/pynwb/validate.py", line 73, in main
    ns_deps = NWBHDF5IO.load_namespaces(catalog, path)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 153, in load_namespaces
    return cls.__load_namespaces(namespace_catalog, namespaces, open_file_obj)
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 187, in __load_namespaces
    d.update(namespace_catalog.load_namespaces(cls.__ns_spec_path, reader=reader))
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 639, in func_call
    return func(args[0], **pargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/spec/namespace.py", line 537, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, resolve=resolve)
  File "/Users/bendichter/dev/hdmf/src/hdmf/spec/namespace.py", line 447, in __load_namespace
    self.__load_spec_file(reader, s['source'], catalog, types_to_load=types_to_load, resolve=resolve)
  File "/Users/bendichter/dev/hdmf/src/hdmf/spec/namespace.py", line 376, in __load_spec_file
    raise ValueError("spec source '%s' already loaded" % spec_source)
ValueError: spec source 'resources' already loaded
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.9

### Package Versions

absl-py==0.14.1
aiobotocore==1.3.3
aiohttp==3.7.4.post0
aioitertools==0.8.0
alabaster==0.7.12
amqp==5.1.1
annexremote==1.5.0
anyio @ file:///opt/concourse/worker/volumes/live/485b0f52-1188-482a-6285-65a36c8fa8a6/volume/anyio_1644481714856/work/dist
appdirs==1.4.4
appnope @ file:///opt/concourse/worker/volumes/live/6ca6f098-d773-4461-5c91-a24a17435bda/volume/appnope_1606859448531/work
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///opt/concourse/worker/volumes/live/42cf1b28-e71f-45ed-47b2-50f828088636/volume/argon2-cffi-bindings_1644569709119/work
arrow==1.2.1
asciitree==0.3.3
asgiref==3.5.2
astunparse==1.6.3
async-timeout==3.0.1
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
audioread==2.1.9
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4==4.11.1
billiard==3.6.4.0
binaryornot==0.4.4
black==19.10b0
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
blessings==1.7
boto==2.49.0
botocore==1.20.106
Bottleneck @ file:///opt/concourse/worker/volumes/live/ac8c8ef3-2ed0-42e9-6ec0-5bb05ad938f6/volume/bottleneck_1607575111469/work
bounded-pool-executor==0.0.3
bqplot==0.12.33
-e git+https://github.com/bendichter/brokenaxes.git@f859521d8f163dbea0da6575f263c05e26b30a3e#egg=brokenaxes
Brotli==1.0.9
brotlipy==0.7.0
-e git+https://github.com/catalystneuro/brunton-lab-to-nwb.git@4f7f8bb42e25dc446480f485f26779940381fbcd#egg=brunton_lab_to_nwb
cachetools==4.2.4
-e git+https://github.com/flatironinstitute/CaImAn.git@07527e12434b27e2b9ad8b93128a67ef1c51e0b0#egg=caiman
ccfwidget==0.5.3
celery==5.2.7
celery-progress==0.1.2
certifi==2022.5.18.1
cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-2p6q7e2r/cffi_1642701115063/work
cfgv==3.3.1
chardet==3.0.4
charset-normalizer==2.0.12
ci-info==0.2.0
clang==5.0
click==8.1.3
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
colorama==0.4.4
colorcet==2.0.6
conda==4.12.0
conda-package-handling @ file:///opt/concourse/worker/volumes/live/8fb3e065-760b-4a9d-4cd9-aca7fc8baf53/volume/conda-package-handling_1618262145611/work
cookiecutter==1.7.3
coreapi==2.3.3
coreschema==0.0.4
coverage==6.4.1
cryptography==37.0.2
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython==0.29.24
cytoolz==0.11.0
dandi==0.39.6
dandischema==0.7.1
dash==2.0.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
dask==2021.10.0
dataframe-image==0.1.1
datajoint==0.13.2
datalad==0.15.4
debugpy @ file:///opt/concourse/worker/volumes/live/fb0af3c0-b0a4-42c5-46e7-6ce9c84da602/volume/debugpy_1637091827531/work
decorator==4.4.2
deeplabcut==2.2.0.2
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
Deprecated==1.2.13
dill==0.3.5.1
distlib==0.3.4
distro==1.6.0
dj-database-url==0.5.0
dj-stripe==2.6.1
Django==3.2.13
django-allauth==0.50.0
django-anymail==8.6
django-hijack==3.2.1
djangorestframework==3.13.1
djangorestframework-api-key==2.2.0
djarchive-client @ git+https://github.com/datajoint/djarchive-client.git@c1a5159f31a8f65b3645a04e3d93bfc56107699a
-e git+https://github.com/DeepLabCut/DLC2NWB.git@1dbe8c8ee65afdb550155b6a3c1174c5e5d0dee4#egg=DLC2NWB
dnspython==2.1.0
docker==5.0.3
docutils==0.16
element-animal==0.1.0b0
element-array-ephys==0.1.0b0
element-interface @ git+https://github.com/datajoint/element-interface.git@23bb10aa43cc7cac0c0958c4e55eed10e85b7aee
element-lab==0.1.0b0
element-session==0.1.0b0
email-validator==1.1.3
entrypoints==0.3
et-xmlfile==1.1.0
etelemetry==0.2.2
fasteners==0.16.3
filelock==3.4.2
filterpy==1.4.5
flake8==4.0.1
Flask==2.0.2
Flask-Compress==1.10.1
flatbuffers==1.12
fonttools==4.25.0
-e git+https://github.com/catalystneuro/froemke-lab-to-nwb.git@f5c513930e9fdca2085f52ffcbdc39f722112e60#egg=froemke_lab_to_nwb
fscacher==0.1.4
fsspec @ file:///opt/conda/conda-bld/fsspec_1642510437511/work
future==0.18.2
gast==0.4.0
geocoder==1.38.1
geographiclib==1.52
geopy==2.2.0
gevent==21.12.0
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.3.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet==1.1.2
grpcio==1.41.0
gunicorn==20.1.0
h5py==3.1.0
h5tree==1.0
hdf5plugin==3.2.0
hdf5storage==0.1.18
-e git+https://github.com/catalystneuro/HDF5Zarr.git@68a52e75ba5180b60f7992d884b022d23a838f72#egg=HDF5Zarr
-e git+https://github.com/hdmf-dev/hdmf.git@7be40229d778dea940134753de957f2457a11e1f#egg=hdmf
hdmf-docutils==0.4.2
humanize==3.11.0
identify==2.4.10
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imagecodecs @ file:///opt/concourse/worker/volumes/live/ab9fe69e-f7d4-471a-6199-cb95a745fb88/volume/imagecodecs_1635529117386/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
imageio-ffmpeg==0.4.5
imagesize==1.2.0
imgaug==0.4.0
importlib-metadata @ file:///opt/concourse/worker/volumes/live/deb4b040-5d3d-417b-6177-7bbc888e23de/volume/importlib-metadata_1638542901294/work
iniconfig==1.1.1
interleave==0.2.0
ipydatawidgets==4.2.0
ipykernel @ file:///opt/concourse/worker/volumes/live/6f6caad4-5c02-4b4a-5243-1eece346c27b/volume/ipykernel_1633545433252/work/dist/ipykernel-6.4.1-py3-none-any.whl
ipympl==0.7.0
ipysheet==0.4.4
ipython @ file:///opt/concourse/worker/volumes/live/4c3cce71-ced8-42c4-43fc-7be66d2225a8/volume/ipython_1643818166775/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipytree @ file:///home/conda/feedstock_root/build_artifacts/ipytree_1614777111309/work
ipyvolume==0.5.2
ipywebrtc==0.6.0
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
iso8601==1.0.2
itk-core==5.2.0.post3
itk-filtering==5.2.0.post3
itk-meshtopolydata==0.7.1
itk-numerics==5.2.0.post3
itkwidgets==0.32.1
itsdangerous==2.0.1
itypes==1.2.0
jedi @ file:///opt/concourse/worker/volumes/live/89be3eb0-a85c-453b-67dd-f706f2fa4c43/volume/jedi_1644315269953/work
Jinja2==3.1.2
jinja2-time==0.2.0
jmespath==0.10.0
joblib==1.0.1
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonfield==3.1.0
jsonpointer==2.1
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter @ file:///opt/concourse/worker/volumes/live/5d55c245-fcac-42f9-4a6c-7e147c07785b/volume/jupyter_1607700866889/work
jupyter-client @ file:///opt/conda/conda-bld/jupyter_client_1643638337975/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1616615302928/work
jupyter-core @ file:///opt/concourse/worker/volumes/live/365b665b-3a8e-478f-5f79-ff4d9b0854bd/volume/jupyter_core_1636537252467/work
jupyter-server @ file:///opt/conda/conda-bld/jupyter_server_1644494914632/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1629114215742/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///opt/conda/conda-bld/jupyterlab_server_1644500396812/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
keras==2.6.0
Keras-Preprocessing==1.1.2
keyring==23.1.0
keyrings.alt==4.1.0
kiwisolver @ file:///Users/builder/miniconda3/envs/prefect/conda-bld/kiwisolver_1638569885739/work
kombu==5.2.4
lazy-ops==0.2.0
librosa==0.9.1
llvmlite==0.37.0
locket==0.2.1
lxml==4.6.5
mamba @ file:///Users/runner/miniforge3/conda-bld/mamba_1629310443605/work
Markdown==3.3.4
markdown-it-py==2.0.1
MarkupSafe==2.1.1
marshmallow==3.15.0
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-suite_1639359007685/work
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mccabe==0.6.1
mdit-py-plugins==0.3.0
mdurl==0.1.0
minio==7.1.2
mip==1.13.0
mistune @ file:///opt/concourse/worker/volumes/live/4217afd5-dad1-438d-6f79-e4992ccda0e5/volume/mistune_1607364880245/work
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/0cda23d8-7460-44b2-7e5d-3c76a8a0ca7e/volume/mkl_random_1626186083266/work
mkl-service==2.4.0
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
moviepy==1.0.3
mpi4py==3.1.1
msgpack==1.0.2
msgpack-numpy==0.4.7.1
multidict==5.1.0
munkres==1.1.4
mypy-extensions==0.4.3
myst-parser==0.17.0
natsort==7.1.1
nbclassic @ file:///opt/conda/conda-bld/nbclassic_1644943264176/work
nbclient @ file:///tmp/build/80754af9/nbclient_1645431659072/work
nbconvert @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-r4wh23j5/nbconvert_1641309205559/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
ndx-dandi-icephys==0.4.0
ndx-events==0.2.0
ndx-grayscalevolume==0.0.2
ndx-icephys-meta==0.1.0
-e git+https://github.com/bendichter/ndx-optogenetics.git@a6a0928f61ed1f6acb0e8a89803b837427310a3c#egg=ndx_optogenetics
-e git+https://github.com/rly/ndx-pose.git@42deb4f6ca87786a822250877f7c027575ec412b#egg=ndx_pose
-e git+https://github.com/catalystneuro/ndx-sound.git@c0843e207a8d718ed03ad3e7740db1b5d1b9f020#egg=ndx_sound
ndx-spectrum==0.2.2
neo==0.10.2
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx @ file:///tmp/build/80754af9/networkx_1633639043937/work
-e git+https://github.com/catalystneuro/neuroconv.git@d28837f0769b33b1420339f1a50b14aba2bf50cb#egg=neuroconv
nibabel==3.2.1
nilearn==0.8.0
nodeenv==1.6.0
notebook @ file:///opt/concourse/worker/volumes/live/55ea25b0-c004-4805-4003-9c10bcdad1c5/volume/notebook_1645002576360/work
numba==0.54.1
numcodecs==0.8.0
numexpr @ file:///opt/concourse/worker/volumes/live/87ac54fe-281a-440d-4d94-26ac99bdabdc/volume/numexpr_1640704258458/work
numpy==1.22.4
-e git+https://github.com/catalystneuro/nwb-conversion-tools.git@0300b60d9657a4d2b69e961cb6f7f0c129c16e32#egg=nwb_conversion_tools
nwbinspector==0.4.12
-e git+https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets.git@d6bbc3994cd2f648893e825183db0eecc1d8e5a9#egg=nwbwidgets
oauthlib==3.2.0
opencv-python==4.5.1.48
opencv-python-headless==4.5.3.56
openpyxl==3.0.9
opt-einsum==3.3.0
otumat==0.3.1
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.4.3
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
param==1.11.1
parameterized==0.8.1
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
pathspec==0.7.0
patool==1.12
patsy==0.5.2
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.0.1
pkgconfig==1.5.5
pkginfo==1.7.1
platformdirs==2.5.0
plotly==5.1.0
pluggy==0.13.1
pooch==1.6.0
poyo==0.5.0
pqdm==0.2.0
pre-commit==2.17.0
probeinterface==0.2.9
proglog==0.1.9
prometheus-client @ file:///opt/conda/conda-bld/prometheus_client_1643788673601/work
prompt-toolkit==3.0.29
protobuf==3.18.1
psutil==5.8.0
psycopg2==2.9.3
psycopg2-binary==2.9.3
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py==1.10.0
pyabf==2.3.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pycryptodomex==3.10.1
pyct==0.4.8
pydantic==1.9.0
pydot==1.4.2
pyflakes==2.4.0
PyGithub==1.55
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
pyintan==0.3.0
PyJWT==2.4.0
PyMySQL==1.0.2
PyNaCl==1.5.0
-e git+https://github.com/NeurodataWithoutBorders/pynwb.git@89d1c1be156ae3b60c68f73517af9b5e1fd53da5#egg=pynwb
pyopenephys==1.1.2
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyout==0.7.1
pyparsing==3.0.9
pyrsistent @ file:///opt/concourse/worker/volumes/live/76cffa60-bd33-4155-4e83-ea03c38b1294/volume/pyrsistent_1636111020441/work
PySocks @ file:///opt/concourse/worker/volumes/live/112288ac-9cb0-4e73-768b-13baf4ca6419/volume/pysocks_1605305820043/work
pytest==6.2.4
pytest-cov==3.0.0
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-gitlab==3.1.0
python-slugify==5.0.2
python3-openid==3.2.0
pythreejs==2.3.0
pytz==2022.1
PyWavelets @ file:///opt/concourse/worker/volumes/live/3cbb6155-7383-45e0-55bb-8641a92939f6/volume/pywavelets_1607645526758/work
PyYAML==5.4.1
pyzmq @ file:///opt/concourse/worker/volumes/live/dbbc086d-2905-496b-54ee-08109e9ced8d/volume/pyzmq_1638435006316/work
qtconsole @ file:///opt/conda/conda-bld/qtconsole_1643819126524/work
QtPy @ file:///opt/conda/conda-bld/qtpy_1643087291789/work
quantities==0.12.5
ratelim==0.1.6
readme-renderer==29.0
redis==4.3.1
regex @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-325xby49/regex_1642021452041/work
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
resampy==0.2.2
rfc3986==1.5.0
rfc3987==1.3.8
roiextractors==0.4.18
rsa==4.7.2
ruamel-yaml-conda @ file:///opt/concourse/worker/volumes/live/e81cf0fe-611a-498e-6e69-a7320057c1ac/volume/ruamel_yaml_1616016689696/work
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
s3fs==2021.7.0
s3transfer==0.3.7
scanimage-tiff-reader==1.4.1
scikit-image==0.18.2
scikit-learn==0.24.2
scipy==1.7.2
seaborn==0.11.2
semantic-version==2.8.5
semver==2.13.0
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
sentry-sdk==1.5.12
Shapely==1.7.1
SimpleITK==2.1.1
simplejson==3.17.6
sip==4.19.13
six==1.15.0
smmap==5.0.0
sniffio @ file:///opt/concourse/worker/volumes/live/38ca9e9e-09d1-4d43-5a0f-b546422e7807/volume/sniffio_1614030472707/work
snowballstemmer==2.1.0
sonpy==1.9.5
SoundFile==0.10.3.post1
soupsieve==2.3.2.post1
Sphinx==4.4.0
sphinx-copybutton==0.5.0
sphinx-design==0.0.13
sphinx-gallery==0.9.0
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
spikeextractors==0.9.10
spikefeatures==0.1.2
-e git+https://github.com/SpikeInterface/spikeinterface.git@622fbb2b0ec637c362c1ab7d97e62ccbedbadf42#egg=spikeinterface
spikemetrics==0.2.4
spikesorters==0.4.5
spiketoolkit==0.7.6
spython==0.2.1
SQLAlchemy==1.4.32
sqlparse==0.4.2
statsmodels==0.13.0
strict-rfc3339==0.7
stripe==3.2.0
tables @ file:///opt/concourse/worker/volumes/live/daa73f70-754b-4f28-73ce-6f96c40f4b9d/volume/pytables_1607975400838/work
tabulate==0.8.9
tenacity==8.0.1
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0
tensorpack==0.11
termcolor==1.1.0
terminado @ file:///opt/concourse/worker/volumes/live/1e61dc32-e381-4730-4e5e-6cfec5c3c4a5/volume/terminado_1644322614203/work
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode==1.3
tf-slim==1.1.0
threadpoolctl==2.2.0
tifffile==2021.7.30
tiffile==2018.10.18
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli==2.0.1
toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work
torch==1.11.0
tornado @ file:///opt/concourse/worker/volumes/live/2c1a63a2-006b-48ee-56b9-0cfe8b4927f9/volume/tornado_1606942321278/work
tqdm==4.60.0
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
traittypes==0.2.1
trimesh==3.9.26
twine==3.4.2
typed-ast @ file:///opt/concourse/worker/volumes/live/c2210c24-bb2d-4474-77f5-1bc9bf1cb79f/volume/typed-ast_1624953683856/work
typing-extensions==3.7.4.3
uritemplate==4.1.1
urllib3==1.26.9
vine==5.0.0
virtualenv==20.13.1
watchdog==2.1.6
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webcolors==1.11.1
webencodings==0.5.1
websocket-client @ file:///opt/concourse/worker/volumes/live/5baed9cd-40fb-4fbe-6721-9568cdd0f2d7/volume/websocket-client_1614804245073/work
Werkzeug==2.0.2
whitenoise==5.2.0
Whoosh==2.7.4
widgetsnbextension @ file:///opt/concourse/worker/volumes/live/8bad7157-f9ed-4ea5-5a30-5ca326558415/volume/widgetsnbextension_1645009368149/work
-e git+https://github.com/datajoint/workflow-array-ephys.git@0dcf5a12dba7f771787814140fae931038a4512b#egg=workflow_array_ephys
wrapt==1.12.1
xarray==0.15.1
xmltodict==0.12.0
yarl==1.6.3
zarr==2.11.1
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
zope.event==4.5.0
zope.interface==5.4.0
zstandard==0.15.2

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
I'll look into it. Initial investigation shows:
![image](https://user-images.githubusercontent.com/310197/184727318-177f54a0-364e-4d6b-8e8e-abccb0f84b99.png)

1. [hdmf-common schema 1.3.0](https://github.com/hdmf-dev/hdmf-common-schema/releases) included ExternalResources but ExternalResources was moved out of hdmf-common namespace and into the new hdmf-experimental namespace in hdmf-common schema 1.4.0. 
2. The file may have been updated or appended to using a newer version of HDMF, and hdmf-experimental was added but for some reason the version of hdmf-common cached in the file was not updated. @bendichter do you know how this file came to be? Was it appended to after the initial write?

In any case, we should catch this error and give the user helpful instructions on what they can do to resolve it.

**Comment by bendichter** [comment]
It could have been that these types were never properly removed from the MatNWB namespace. I'll do a fresh install.

**Comment by bendichter** [comment]
@rly yup, that was the problem. We need to find a better way to clean the namespace of MatNWB for these types of changes. At any rate, the error was not with pynwb.validate. Closing.
