### ISSUE TITLE
[Documentation]: guidance on how to use LabMetaData

### ISSUE THREAD

**Issue by TomDonoghue** [NeurodataWithoutBorders/pynwb#1542]
### What would you like changed or added to the documentation and why?

I've been looking for some documentation on how to use the `LabMetaData` object to potentially add some extra notes and pieces of information to our data files, but I'm having trouble finding clear documentation and examples for how to do so. On the pynwb documentation website, for example, the API listing doesn't really make it clear on how to use this approach to add any information. 

Based on searching for examples of people using this, I think using NWBfile.add_lab_meta_data perhaps also requires using the extensions tool to define a custom LabMetaData object to be added? This makes sense, but I don't find it very clear from looking at pywnb documentation. Based on poking around with `pynwb` it's confusing how it works, since it seems on can only really generate some kind of empty container with a name. I's not obvious that, I think, LabMetaData is some kind of base that should be inherited by some kind of extension (?). Perhaps this functionality is documented somewhere else and I'm missing it, but if not, I think there could be some updated documentation for this functionality. 

For example, some potential documentation updates:
- add some notes to the docstring of `add_lab_meta_data`, `create_lab_meta_data`, and/or `LabMetaData` about what this is / how it works, and update accepted inputs, etc
   - for example, `add_lab_meta_data`, which on the face of it seems like it could take meta data in general (rather than a particular LabMetaData object), says that lists and dicts are acceptable inputs, but I think this really means lists or dicts of LabMetaData objects? Passing in a list of a dict otherwise leads to non-obvious errors. 
- add an example of creating and using a custom lab meta data object, perhaps on the "Extending NWB" page?

### Do you have any interest in helping write or edit the documentation?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by bendichter** [comment]
@TomDonoghue you are exactly right about how to use the class. It's essentially a base (aka abstract) class that you can inherit from in an extension to put metadata in the /general section on an NWB file. Let me see if I can find some good examples

**Comment by bendichter** [comment]
@TomDonoghue 

[Here](https://github.com/catalystneuro/ndx-dandi-icephys) is a good example of proper usage (though this is no longer the recommended way to add `cell_id`, as this field has been added in `IntracellularElectrode`.

**Comment by oruebel** [comment]
> * add an example of creating and using a custom lab meta data object, perhaps on the "Extending NWB" page?

I've added a note about this to this issue https://github.com/NeurodataWithoutBorders/nwb-overview/issues/54

**Comment by oruebel** [comment]
> add some notes to the docstring of `add_lab_meta_data`, `create_lab_meta_data`, and/or `LabMetaData` about what this is / how it works, and update accepted inputs, etc
> 
>     * for example, `add_lab_meta_data`, which on the face of it seems like it could take meta data in general (rather than a particular LabMetaData object), says that lists and dicts are acceptable inputs, but I think this really means lists or dicts of LabMetaData objects? Passing in a list of a dict otherwise leads to non-obvious errors.

Good idea

**Comment by oruebel** [comment]
``add_lab_meta_data`` is an auto-generated function. I've created https://github.com/hdmf-dev/hdmf/pull/758 on HDMF to clarify the docstring for this type of function. With this PR, the doc string for ``add_lab_meta_changes`` to:

```
add_lab_meta_data(*args, **kwargs)
    add_lab_meta_data(lab_meta_data)
    
    Add one or multiple a LabMetaData objects to this NWBFile
    
    Args:
        lab_meta_data (:py:class:`~list` or :py:class:`~tuple` or :py:class:`~dict` or :py:class:`~pynwb.file.LabMetaData`): one or multiple LabMetaData objects to add to this NWBFile

```

I hope this helps clarify the function. I'll create a separate PR on PyNWB to also update the docstring of the ``LabMetaData`` class to clarify how it is intended to be used.

**Comment by oruebel** [comment]
I also now added #1546 to further address this issue. I believe this should resolve this issue on the PyNWB side. And https://github.com/NeurodataWithoutBorders/nwb-overview/issues/54 should then further address this as part of the extension tutorial.
