### ISSUE TITLE
[Feature]: support higher version of numpy

### ISSUE THREAD

**Issue by ZeitgeberH** [NeurodataWithoutBorders/pynwb#1547]
### What would you like to see added to PyNWB?

Hi,
the current numpy version supported by PvNWB is 1.21.5, which triggers a dependency alert:
"Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects."  It is suggested to upgrade it to version 1.22 or later.

### Is your feature request related to a problem?

Yes. it is a dependency alert.  See above. 

### What solution would you like?

Relax numpy version requirment to be above 1.22

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Thanks for the bug report. I will push a bugfix release asap.
