### ISSUE TITLE
docs: Update architecture.rst to document overall CI and software process

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#155]
Proposed sections:

```
Continuous Integration
  Platforms
   * explain which services (Appveyor, travis, ...) are used
   * document any specific steps taken to set things up 
  Coverage
   * What and how
  Type of tests
```

**Comment by jcfr** [comment]
Cc: @mgrauer @dorukozturk @oruebel 

Is `architecture.rst` the right place ? Or should we create a `software_process.rst` doc ?

**Comment by mgrauer** [comment]
I'd prefer `software_process.rst`, or it could be in contributing. Contributing should refer to this at least.

**Comment by oruebel** [comment]
Adding a new ``software_process.rst`` is fine.

**Comment by jcfr** [comment]
* [ ] Explain how to update `requirements.txt`
