### ISSUE TITLE
[Bug]: pynwb 2.1.1 did not get released

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1558]
### What happened?

@CBroz1 wrote:
> I ran into a dependency conflict when working on the DLC2NWB DeepLabCut export. For Apple M1 machines, importing tensorflow requires numpy≥1.23, but pynwb 2.1 pins numpy<1.23

It turns out that the allowed range of numpy versions was increase by #1550. This should have been in the 2.1.1 release, but only the 2.1.1 tag was created; a 2.1.1 release was not created. That is because the CircleCI workflow for making releases requires that the miniconda37 test passes but it failed: https://app.circleci.com/pipelines/github/NeurodataWithoutBorders/pynwb/3403/workflows/277a957e-a20b-412f-9994-77936ed99fa1 due to a certificate mismatch "OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.9/site-packages/certifi/cacert.pem"

This issue with miniconda37 should be resolved in #1511, but that has yet to be merged.

### Steps to Reproduce

```python
n/a
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by CBroz1** [comment]
Thanks for the update!

**Comment by bendichter** [comment]
@rly close?

**Comment by rly** [comment]
Yes. Thanks for going through these! 2.2.0 has been released with the fixes from 2.1.1.
