### ISSUE TITLE
[Documentation]: All docs should load namespaces

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1562]
### What would you like changed or added to the documentation and why?

Until we make `load_namespaces=True` the default setting, all docs should demonstrate `load_namespaces=True` by default.

I cannot see a *common* use case where we would not want to load namespaces.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by stephprince** [comment]
`load_namespaces=True` is now the default `NWBHDF5IO` setting since https://github.com/NeurodataWithoutBorders/pynwb/pull/1748 so I think this no longer applies.
