### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'h5py'

### ISSUE THREAD

**Issue by rcpeene** [NeurodataWithoutBorders/pynwb#1565]
### What happened?

I am running pynwb code in a Jupyter notebook locally to test file streaming with ros3. I ran the commands listed [here](https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html#sphx-glr-download-tutorials-advanced-io-streaming-py) to install the correct versionf of h5py. Within the notebook, `pip show h5py` shows that h5py version 3.7 is present. However, when I run the following line, I get an error;
```from pynwb import NWBHDFIO```

### Steps to Reproduce

```python
1. Open conda shell. Run the commands `conda uninstall h5py` and `conda install -c conda-forge "h5py>=3.2"`
2. Run `jupyter notebook`
3. Run the import line shown in the section above.
```

### Traceback

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [2], line 1
----> 1 from pynwb import NWBHDFIO

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pynwb\__init__.py:8
      6 from copy import deepcopy
      7 from warnings import warn
----> 8 import h5py
     10 from hdmf.spec import NamespaceCatalog
     11 from hdmf.utils import docval, getargs, popargs, get_docval

ModuleNotFoundError: No module named 'h5py'
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Package Versions

aiohttp==3.8.3
aiosignal==1.2.0
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
arrow==1.2.3
asciitree==0.3.3
asttokens==2.0.8
async-timeout==4.0.2
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1659291887007/work
backcall==0.2.0
bidsschematools @ file:///home/conda/feedstock_root/build_artifacts/bidsschematools_1663886665087/work
bqplot==0.12.36
brotlipy @ file:///D:/bld/brotlipy_1648854347500/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
ccfwidget==0.1.0
certifi==2022.9.24
cffi @ file:///D:/bld/cffi_1656782940775/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
ci-info==0.3.0
click @ file:///D:/bld/click_1651215332191/work
click-didyoumean @ file:///home/conda/feedstock_root/build_artifacts/click-didyoumean_1642673782881/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1655412516417/work
contourpy==1.0.5
cryptography @ file:///C:/ci/cryptography_1652101729823/work
cycler==0.11.0
dandi @ file:///D:/bld/dandi_1664204376629/work
dandischema @ file:///home/conda/feedstock_root/build_artifacts/dandischema_1654288351021/work
debugpy==1.6.3
decorator==5.1.1
dnspython @ file:///home/conda/feedstock_root/build_artifacts/dnspython_1646621171513/work
email-validator @ file:///home/conda/feedstock_root/build_artifacts/email-validator-meta_1663557891323/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
etelemetry==0.3.0
executing==1.1.0
fasteners==0.18
fonttools==4.37.4
fqdn==1.5.1
frozenlist==1.3.1
fscacher @ file:///home/conda/feedstock_root/build_artifacts/fscacher_1645566717818/work
fsspec==2022.8.2
h5py @ file:///D:/bld/h5py_1660488207680/work
hdmf @ file:///home/conda/feedstock_root/build_artifacts/hdmf_1664932992385/work
humanize @ file:///home/conda/feedstock_root/build_artifacts/humanize_1663851046445/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imageio==2.22.1
importlib-metadata @ file:///D:/bld/importlib-metadata_1653252994979/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1658604161399/work
interleave @ file:///home/conda/feedstock_root/build_artifacts/interleave_1656809930415/work
ipydatawidgets==4.3.2
ipykernel==6.16.0
ipympl==0.9.2
ipython==8.5.0
ipython-genutils==0.2.0
ipyvolume==0.6.0a10
ipyvue==1.8.0
ipyvuetify==1.8.4
ipywebrtc==0.6.0
ipywidgets==8.0.2
isoduration==20.11.0
jaraco.classes==3.2.3
jedi==0.18.1
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
jsonpointer==2.3
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1662736858348/work
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-widgets==3.0.3
keyring @ file:///D:/bld/keyring_1663458771015/work
keyrings.alt==4.2.0
kiwisolver==1.4.4
markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1650305363826/work
matplotlib==3.6.0
matplotlib-inline==0.1.6
mdurl @ file:///home/conda/feedstock_root/build_artifacts/mdurl_1639515908913/work
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1660060161633/work
msgpack @ file:///D:/bld/msgpack-python_1654260830508/work
multidict==6.0.2
natsort @ file:///home/conda/feedstock_root/build_artifacts/natsort_1662085508562/work
ndx-grayscalevolume==0.0.2
ndx-icephys-meta==0.1.0
ndx-spectrum==0.2.2
nest-asyncio==1.5.6
networkx==2.8.7
numcodecs @ file:///D:/bld/numcodecs_1659408399522/work
numpy==1.22.4
nwbinspector @ file:///home/conda/feedstock_root/build_artifacts/nwbinspector_1663993525299/work
nwbwidgets==0.9.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
pandas @ file:///D:/bld/pandas_1663621248084/work
parso==0.8.3
pickleshare==0.7.5
Pillow==9.2.0
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
plotly==5.10.0
prompt-toolkit==3.0.31
psutil==5.9.2
pure-eval==0.2.2
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pycryptodomex @ file:///D:/bld/pycryptodomex_1657165058058/work
pydantic @ file:///D:/bld/pydantic_1662443224019/work
Pygments==2.13.0
pynwb==2.1.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1663846997386/work
pyout @ file:///D:/bld/pyout_1649788714676/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyrsistent @ file:///D:/bld/pyrsistent_1649013512562/work
PySocks @ file:///D:/bld/pysocks_1661604991356/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pythreejs==2.4.1
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1664798238822/work
PyWavelets==1.4.1
pywin32==304
pywin32-ctypes @ file:///D:/bld/pywin32-ctypes_1648607976563/work
PyYAML @ file:///D:/bld/pyyaml_1648757288117/work
pyzmq==24.0.1
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1661872987712/work
rfc3339-validator==0.1.4
rfc3987==1.3.8
ruamel.yaml @ file:///D:/bld/ruamel.yaml_1649033381790/work
ruamel.yaml.clib @ file:///D:/bld/ruamel.yaml.clib_1649013230263/work
scikit-image==0.19.3
scipy==1.9.1
semantic-version @ file:///home/conda/feedstock_root/build_artifacts/semantic_version_1653579368137/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
stack-data==0.5.1
tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1655900837660/work
tenacity @ file:///home/conda/feedstock_root/build_artifacts/tenacity_1663807083684/work
tifffile==2022.8.12
tornado==6.2
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
traitlets==5.4.0
traittypes==0.2.1
trimesh==3.15.3
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1656706066251/work
uri-template==1.2.0
urllib3==1.26.12
wcwidth==0.2.5
webcolors==1.12
widgetsnbextension==4.0.3
win-inet-pton @ file:///D:/bld/win_inet_pton_1648771897787/work
yarl==1.8.1
zarr @ file:///home/conda/feedstock_root/build_artifacts/zarr_1664515305472/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1659400682470/work

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Instead of opening a jupyter notebook, can you run just `python -c "import h5py"` in the command line in the same conda environment where you ran step 1? This will help determine whether it is due to an environment issue or a jupyter issue or something else.

**Comment by rcpeene** [comment]
This seems like an error that may be unrelated. Here is the output from the above command;
```
Error processing line 1 of C:\Users\carter.peene\Miniconda3\envs\dandi_stream\lib\site-packages\ruamel.yaml-0.17.21-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\carter.peene\Miniconda3\envs\dandi_stream\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 568, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

**Comment by rly** [comment]
@rcpeene something in your environment seems to be broken. Can you try recreating the environment from scratch?

```python
conda deactivate

# remove the dandi_stream environment
conda remove --name dandi_stream --all --yes

# re-create the dandi_stream env from scratch
conda create --name dandi_stream python=3.9 --yes
conda activate dandi_stream

pip install dandi

# reinstall h5py with ros3 streaming enabled
pip uninstall h5py --yes
conda install -c conda-forge "h5py>=3.2" --yes

# test h5py installation
python -c "import h5py"
```

**Comment by rcpeene** [comment]
Unfortunately, no dice! After running those commands, it may have fixed the secondary error but the original one persists.
Outside the notebook `python -c "import h5py"` works and within the notebook `pip show h5py` still shows the installation of h5py 3.7.0 yet `from pynwb import NWBHDF5IO` still yields the same traceback;
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [2], line 1
----> 1 from pynwb import NWBHDFIO

File ~\AppData\Local\Programs\Python\Python39\lib\site-packages\pynwb\__init__.py:8
      6 from copy import deepcopy
      7 from warnings import warn
----> 8 import h5py
     10 from hdmf.spec import NamespaceCatalog
     11 from hdmf.utils import docval, getargs, popargs, get_docval

ModuleNotFoundError: No module named 'h5py'

```

**Comment by rcpeene** [comment]
```python -c "from pynwb import NWBHDF5IO"``` also appears to work via command line

**Comment by rly** [comment]
From where are you starting jupyter? Can you try closing all jupyter instances and then in the same terminal and environment where `python -c "import h5py"` works, run `jupyter lab` or `jupyter notebook` (run `pip install jupyterlab` if jupyter is not installed), and from there create a new notebook where you run `import h5py`?

**Comment by rcpeene** [comment]
I've been running `jupyter notebook` from the same miniconda terminal as the other commands.

**Comment by rcpeene** [comment]
Good news, I have a different error. I ran `pip install jupyter` and `pip install notebook` within the conda environment and then ran the notebook. The new traceback when running `from pynwb import NWBHDFIO` is as follows;
```
ImportError                               Traceback (most recent call last)
Cell In [2], line 1
----> 1 from pynwb import NWBHDFIO

ImportError: cannot import name 'NWBHDFIO' from 'pynwb' (C:\Users\carter.peene\Miniconda3\envs\dandi_stream\lib\site-packages\pynwb\__init__.py)
```

**Comment by rcpeene** [comment]
Perhaps installing dandi via pip and not via conda commands is causing an issue?

**Comment by rcpeene** [comment]
Sometimes (I can't tell under what circumstances) the line `conda install -c conda-forge "h5py>=3.2"` doesn't actually install h5py yet claims it succeeded.

**Comment by rly** [comment]
I'm glad that h5py got installed correctly under one configuration.

> `from pynwb import NWBHDFIO`

This should be NWBHDF5IO

If you're still running into errors, let's find a time to chat and debug in real time. I *think* this is an environment & jupyter issue. Tomorrow I'm free 9-11 and 3-5 PT. Would sometime then work for you? We can also coordinate meeting over the NWB slack.

**Comment by rcpeene** [comment]
Yeah that was a typo above but it was not a typo on my machine.
I think it is fixed. The series of commands I ran were as follows;
```
conda remove --name dandi_stream --all --yes
conda create --name dandi_stream python=3.9 --yes
conda activate dandi_stream
conda install jupyter
conda install notebook
pip install dandi
pip uninstall h5py
conda install -c conda-forge "h5py>=3.2" --yes
python -c "import h5py"
jupyter notebook
```
It must be some problem with running a jupyter notebook whose environment was outside of my conda environment. After installing jupyter _within_ the conda environment the import error no longer arose. I would think that if this was actually the case, we would see others having similar problems as well.

However I do still get an `OSError: Unable to open file (curl cannot perform request)` on the line `with NWBHDF5IO(file_url, mode='r', load_namespaces=True, driver='ros3') as io:` in my notebook.
I believe this to be a different error which I may make a separate issue for.

**Comment by CodyCBakerPhD** [comment]
> However I do still get an OSError: Unable to open file (curl cannot perform request) on the line with NWBHDF5IO(file_url, mode='r', load_namespaces=True, driver='ros3') as io:

`curl` issues like this can and do occur when streaming with the `ros3` driver. We ran into this frequently with the [NWB Inspector streaming functionality](https://github.com/NeurodataWithoutBorders/nwbinspector/issues/197), and our fix was to implement the [Amazon recommendation for iteratively retrying the command](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) in [this PR](https://github.com/NeurodataWithoutBorders/nwbinspector/pull/223/files).

As an aside, have you tried following[ this tutorial for alternative streaming methods](https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html?highlight=streaming#streaming-method-2-fsspec)? I believe is has the automatic retry functionality built-in to avoid this specific issue.

**Comment by bendichter** [comment]
@CodyCBakerPhD fsspec is not working with the latest release of pynwb. We're working on that right now.

**Comment by rcpeene** [comment]
Thanks! I did get my code from that tutorial. I was attempting to get both methods working on my end but ran into different problems with each, I think with accessing embargoed dandisets on dandi, so the automatic retry probably won't resolve that.

**Comment by bendichter** [comment]
@rcpeene fsspec is now working. Can we close this issue?
