### ISSUE TITLE
[Feature]: Add API class for OnePhotonSeries

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1578]
### What would you like to see added to PyNWB?

The upcoming NWB 2.6.0 release contains a new neurodata_type: `OnePhotonSeries`: 
https://github.com/NeurodataWithoutBorders/nwb-schema/pull/523

### What solution would you like?

We should add a PyNWB API class for it. 

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
@CodyCBakerPhD would you be able to add and test an API class for `OnePhotonSeries` to PyNWB? It might be as simple as adding `OnePhotonSeries = get_class("OnePhotonSeries", namespace="core")` in `ophys.py` and adding unit tests and roundtrip tests.

**Comment by stephprince** [comment]
The `OnePhotonSeries` class was added with https://github.com/NeurodataWithoutBorders/pynwb/pull/1593.
