### ISSUE TITLE
Broken Exception Message in __resolve_dtype__ (h5tools.py)

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#158]
https://github.com/NeurodataWithoutBorders/pynwb/blob/be7470b944eb23e3a1d4688a525f6ad3261ad9d2/src/form/backends/hdf5/h5tools.py#L163

```
def __resolve_dtype__(dtype, data):
    # TODO: These values exist, but I haven't solved them yet
    # binary
    # number
    dtype = __resolve_dtype_helper__(dtype)
    if dtype is None:
        try:
            dtype = get_type(data)
        except Exception as exc:
            msg = 'cannot add %s to %s - could not determine type' % (name, parent.name)
            raise_from(Exception(msg), exc)
    return dtype
```

name and parent.name are not in scope, so this message is not behaving as intended.  Probably the result of a refactor,  but should be cleaned up to provide a helpful message

**Comment by nicain** [comment]
@ajtritt I mentioned this to you a few days ago.  I am going to take it out of my current changes, so that we can address it in a bug branch with a simpler merge when there is less time pressure.

**Comment by t-b** [comment]
Looking at the code https://github.com/hdmf-dev/hdmf/blob/8ddc8574123853215a4d6c43d27bd2aec908017d/src/hdmf/backends/hdf5/h5tools.py#L482 this is already fixed.
