### ISSUE TITLE
[Documentation]: TestMapRoundTrip outdated

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1585]
### What would you like changed or added to the documentation and why?

This page: http://localhost:63342/pynwb/docs/_build/html/testing/make_roundtrip_test.html#testmaproundtrip describes the `TestMapRoundTrip` class, but I can't find it in pynwb nor hdmf. Has this been replaced with [`NWBH5IOMixin`](https://github.com/NeurodataWithoutBorders/pynwb/blob/c0ad3e717a1cd268ed91d75a26d97e14ccda46ee/src/pynwb/testing/testh5io.py#L13)?

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by bendichter** [comment]
Yes, it looks like it was: https://github.com/NeurodataWithoutBorders/pynwb/blob/c0ad3e717a1cd268ed91d75a26d97e14ccda46ee/src/pynwb/testing/testh5io.py#L31

**Comment by bendichter** [comment]
@rly

**Comment by oruebel** [comment]
Digging through the history, I believe this was changed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1117

**Comment by bendichter** [comment]
OK I'll take a stab at updating it
