### ISSUE TITLE
[Documentation]: dev installation instructions not working

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1589]
### What would you like changed or added to the documentation and why?

When I follow the instructions [here](https://pynwb.readthedocs.io/en/stable/install_developers.html#install-from-git-repository) and run 

```
$ git clone --recurse-submodules git@github.com:NeurodataWithoutBorders/pynwb.git
```

I get 

```
$ git clone --recurse-submodules git@github.com:NeurodataWithoutBorders/pynwb.git
Cloning into 'pynwb'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Changing this line to 

```
$ git clone --recurse-submodules https://github.com/NeurodataWithoutBorders/pynwb.git
```

works for me.

Can we change this over to http? Are there advantages to using git@github I don't know about?

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
> Can we change this over to http?

Changing the line to https is I think fine. The main difference is that ``git@github.com`` uses ssh and the other uses ``https``. Using ssh has the advantage that you don't need to authenticate every time one wants to write. For the ssh variant you'll  need to setup keys https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by rly** [comment]
I agree; this is fine. I'll make the change.
