### ISSUE TITLE
CI/coverage: Associate form, pynwb and integration tests with a different flag

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#159]
From @ajtritt 

> I was wondering if there was a way to figure out which new code needs unit tests by running just the unit tests.

It is indeed possible. See https://docs.codecov.io/docs/flags

I suggest we run the test driver three times:

1.  with `--form` , associating the coverage flag `form`

2.  with `--pynwb`, associating the coverage flag `pynwb`

3.  with `--integration`, associating the coverage flag `integration`

**Comment by oruebel** [comment]
Closing. Was resolved in #160.
