### ISSUE TITLE
Add functionality for writing from other languages

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#16]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

As a step in the direction of allowing individuals to stream into NWB files, provide some functionality to create an NWB file with empty datasets, which can then be written to by other APIs used in acquisition systems.

Also, provide ways of moving existing HDF5 datasets into correct locations to comply with NWB format specification.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/16

**Comment by rly** [comment]
@stephprince is working on this with the C++ API as one language. Other languages will be handled as requested by the community.

**Comment by t-b** [comment]
@rly @stephprince Is there a repo I can follow for the C++ version?

**Comment by oruebel** [comment]
> Is there a repo I can follow for the C++ version?

Hi @t-b, unfortunately not yet. We are currently working through the LBL approval process to make the repo public. I'll ping you once we are through the legal process. I expect us to be able to make the repo public in the next few weeks.
