### ISSUE TITLE
create docval macros for acceptable data types

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#162]
When specifying a type for an argument in docval, we must list out (in a tuple) all acceptable types for the argument. For example, the `data` argument to `TimeSeries` takes three types.

```python
...
    {'name': 'data', 'type': (Iterable, 'TimeSeries', DataChunkIterator), 'doc': '...'}
...
```

to make it easier to maintain, we should be able to use something like this:

```python
...
    {'name': 'data', 'type': ('array', 'TimeSeries'), 'doc': '...'}
...
```

and docval will know `'array'` translates to `(Iterable, DataChunkIterator)`

**Comment by oruebel** [comment]
Closing, this issue has been resolved in https://github.com/NeurodataWithoutBorders/pynwb/commit/5d44359c0c2ad6cbae7e329ba12181c0f4f91eb2 . See the ``__macros`` dict and ``docval_marcro`` function in ``pynwb/src/pynwb/form/utils.py``
