### ISSUE TITLE
test tutorials across python versions

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1659]
We are currently limiting the test matrix of the tutorials due to the AllenSDK. 

https://github.com/NeurodataWithoutBorders/pynwb/blob/cc5fd34240891e14a6b82552a4b8c3c259fcafae/.github/workflows/run_all_tests.yml#L92-L107

The latest AllenSKD claims to support Python 3.9: https://github.com/AllenInstitute/AllenSDK/blob/1caa779b517eeb2428282919d0fb8a65e7217791/setup.py#L92

And anyway I don't think at this point we should be limiting our entire testing suite based on the Allen SDK.

**Comment by rly** [comment]
I created a new issue for this in #1679
