### ISSUE TITLE
[Bug]: pynwb 2.3.1 not available on conda-forge

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1663]
### What happened?

2.2.0 is the latest version available there. Not sure why the conda bot did not make a PR. We will have to do it manually.
https://github.com/conda-forge/pynwb-feedstock

@mavaylon1 could you please look into this next week? Fixing this falls outside of the typical release schedule.

### Steps to Reproduce

```python
see git repo
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by mavaylon1** [comment]
Sure

**Comment by rly** [comment]
PyNWB 2.3.1 was released on conda-forge here https://github.com/conda-forge/pynwb-feedstock/pull/47
