### ISSUE TITLE
[Bug]: Error on parsing nwb_version attribute

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#1668]
### What happened?

I'm in the process of updating our CI pipeline to validate the IPNWB/MIES generated NWB.
pynwb is updated from 2.1.0 to 2.3.1.

The file passes validation.

See also https://github.com/AllenInstitute/MIES/pull/1650.

Now the problem is that the file can not be opened anymore because `/nwb_version` has an unexpected HDF5 format. This was not an issue with 2.1.0. a1f472b1 (Check nwb_version on read (#1612), 2022-12-18) seems to be culprit.

```
HDF5 "E:\projekte\mies-igor\HardwareBasic_1-V2.nwb" {
ATTRIBUTE "nwb_version" {
   DATATYPE  H5T_STRING {
      STRSIZE 5;
      STRPAD H5T_STR_NULLPAD;
      CSET H5T_CSET_UTF8;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "2.2.4"
   }
}
}
```

### Steps to Reproduce

```python
import pynwb

io = pynwb.NWBHDF5IO("HardwareBasic_1-V2.nwb", 'r', load_namespaces=True)
nwbfile = io.read()
```

### Traceback

```python
C:\users\thomas\Anaconda3\lib\site-packages\hdmf\spec\namespace.py:531: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
C:\users\thomas\Anaconda3\lib\site-packages\hdmf\spec\namespace.py:531: UserWarning: Ignoring cached namespace 'core' version 2.2.4 because version 2.6.0-alpha is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
Traceback (most recent call last):
  File "read.py", line 4, in <module>
    nwbfile = io.read()
  File "C:\users\thomas\Anaconda3\lib\site-packages\hdmf\utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "C:\users\thomas\Anaconda3\lib\site-packages\pynwb\__init__.py", line 280, in read
    file_version_str, file_version = self.nwb_version
  File "C:\users\thomas\Anaconda3\lib\site-packages\pynwb\__init__.py", line 262, in nwb_version
    nwb_version_parts = nwb_version_string.replace("-", ".").replace("_", ".").split(".")
TypeError: a bytes-like object is required, not 'str'
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.8

### Package Versions

[HardwareBasic_1-V2.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/10996295/HardwareBasic_1-V2.zip)

[environment_for_issue.txt](https://github.com/NeurodataWithoutBorders/pynwb/files/10996306/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
@t-b thanks for reporting this issue. With the file you provided I am able to reproduce the issue. 

Just for a bit more details on the issue, when comparing the ``nwb_version`` attribute from the sample file with a file written by PyNWB it seems that the main difference is that the example file uses a fixed-length string and PyNWB writes as a variable-length string. As a result, reading the ``nwb_version`` attribute results in a ``class 'numpy.bytes_`` object rather than a Python ``str`` object, which results in an error in the ``nwb_version`` check function. I'll see what I can do to fix this issue to allow reading with a fixed-length string in PyNWB.

**Test file**
```
ATTRIBUTE "nwb_version" {
   DATATYPE  H5T_STRING {
      STRSIZE 5;
      STRPAD H5T_STR_NULLPAD;
      CSET H5T_CSET_UTF8;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "2.2.4"
   }
}
}
```

**PyNWB file**
```
ATTRIBUTE "nwb_version" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_UTF8;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SCALAR
   DATA {
   (0): "2.6.0"
   }
}
}
```

**Comment by oruebel** [comment]
@t-b  I implemented a fix in #1669

**Comment by t-b** [comment]
@oruebel Thanks for the quick fix, works nicely here.

**Comment by t-b** [comment]
I can report that pynwb 2.3.1 with the patch can read IPNWB/MIES NWBv2 files again. See https://github.com/AllenInstitute/MIES/pull/1650.

**Comment by rly** [comment]
Great. I will prepare a 2.3.2 release.
