### ISSUE TITLE
[Documentation]: Searching any terms on https://pynwb.readthedocs.io/en/stable/ does not work 

### ISSUE THREAD

**Issue by jeromelecoq** [NeurodataWithoutBorders/pynwb#1670]
### What would you like changed or added to the documentation and why?

Searching any terms on https://pynwb.readthedocs.io/en/stable/ does not work .

Whenever I search for a keyword, it seems to spin forever.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Thanks for the bug report @jeromelecoq ! 

The console says:
```
Uncaught ReferenceError: jQuery is not defined
```

This may have to do with the Sphinx update to version 6 which removes bundled jquery https://blog.readthedocs.com/sphinx6-upgrade/ . However, jquery should be bundled with sphinx_rtd_theme-1.2.0 which is installed and sphinxcontrib_jquery-4.1 is also installed. I will investigate.
