### ISSUE TITLE
Writing an NWB file from a ros3 stream hangs

### ISSUE THREAD

**Issue by colleenjg** [NeurodataWithoutBorders/pynwb#1673]
I have some files I need to work with locally. I wrote a little script to stream them, then save them after popping out the largest module (`acquisition`, accounting for 95% of the file size). I'm able to write the file without the acquisition module almost completely, but then it hangs indefinitely. I can't quite figure out why. Minimum example included below. Thank you in advance!

**Extra info**
- I _think_ that the error may be occurring with the `SegmentationImages` or `ImageSegmentation` module of the `Fluorescence` interface.
- I encountered the same problem when I tried with another file.
- FYI, I was able to do this using `ffspec` without any problem, so I don't think I've critically broken the file by popping out the acquisition module. It seems like this is specific to how I'm streaming with `ros3`.
- Running on Ubuntu Ubuntu 22.04.2 LTS with the following package versions (though tested with multiple recent `pynwb` and `dandi` versions):
   - `h5py==3.8.0` # installed via conda
   - `hdf5==1.12.2` # installed via conda
   - `pynwb==2.3.1` # installed via pip
   - `dandi==0.51.0` # installed via pip

**Minimum example code**
```
#!/usr/bin/env python
"""
Adapted from https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html
Downloads and saves a partial NWB file from a dataset, after popping out the large acquisition module.
"""

from dandi.dandiapi import DandiAPIClient
import pynwb

dandiset_id = "000054"
filepath = "sub-F1/sub-F1_ses-20190407T210000_behavior+ophys.nwb"
savepath = "sub-F1_ses-20190407T210000_behavior+ophys_small.nwb"

with DandiAPIClient() as client:
    asset = client.get_dandiset(dandiset_id, "draft").get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=1, strip_query=True)

with pynwb.NWBHDF5IO(s3_url, mode="r", load_namespaces=True, driver="ros3") as read_io:
    read_nwbfile = read_io.read()
    read_nwbfile.acquisition.pop("TwoPhotonSeries")
    with pynwb.NWBHDF5IO(savepath, "w") as write_io:
        write_io.export(src_io=read_io, nwbfile=read_nwbfile,  write_args={"link_data": False}) # hangs here, at ~462.3 MB
```

**Comment by oruebel** [comment]
@colleenjg thanks for reporting this issue. This approach interleaves the read from remote with write. My first guess would be that a web request is failing at some point and I'm not sure if the ros3 driver in h5py/HDF5 does automatic retries. ffspec on the other hand, I believe, automatically does retries if a web-request is failing. This might explain why it works with ffspec and fails with ros3.

**Comment by CodyCBakerPhD** [comment]
> My first guess would be that a web request is failing at some point and I'm not sure if the ros3 driver in h5py/HDF5 does automatic retries.

I suspect @oruebel is correct, we ran into similar issues in the NWB Inspector (`ros3` does _not_ automatically retry; `fsspec` _does_ retry automatically) and made this helper function to resolve it:

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/utils.py#L158-L172

Though I admit we have no tutorials or other user-friendly documentation for how to harness this function for general-purpose (only used for internal purposes throughout that project), so please let me know if you have any questions about how to use it

**Comment by CodyCBakerPhD** [comment]
Although now I think about it, what we found was an explicit `cannot curl` error on certain 'failed' responses, not an error-less hang operation, so I'm not even sure if that would necessarily fix the issue here 😕

**Comment by colleenjg** [comment]
Thank @oruebel and @CodyCBakerPhD for getting back to me. I'm not sure where I might be able to use `robust_s3_read()` here. I haven't found that the step where I read the NWB file, `read_nwbfile = read_io.read()` fails. It may  be failing inside the `write()` operation, but I don't have control on how the reading is done within. 

Notably, it also consistently fails right before finishing writing the file, which might be too consistent for a web-request failure. What do you think?

**Comment by colleenjg** [comment]
Resuscitating this issue, just in case! I tried again, now a year and a half out and the same problem persists. Any thoughts on what may be preventing the write operation from completing using `ros3`? 

As mentioned above, the problem really seems to be at the very end, so it doesn't look like a random web-request failure to me. And as Cody mentioned, there's no error - it just hangs.

Running on Ubuntu 22.04.2 LTS with the following now updated package versions:
- `h5py==3.10.0` # installed with conda
- `hdf5==1.14.3` # installed with conda
- `pynwb==2.8.3` # installed with pip
- `dandi==0.64.0` # installed with pip

**Comment by colleenjg** [comment]
Resuscitating this issue, just in case there is new insight. I tried again, now a year and a half out and the same problem persists. Any thoughts on what may be preventing the write operation from completing using `ros3`? 

As mentioned above, the problem really seems to be at the very end, so it doesn't look like a random web-request failure to me. And as Cody mentioned, there's no error - it just hangs.

It's too bad because streaming with `ros3` seems simpler than with `fsspec`.

Running on Ubuntu 22.04.2 LTS with the following now updated package versions:
- `h5py==3.10.0` # installed with conda
- `hdf5==1.14.3` # installed with conda
- `pynwb==2.8.3` # installed with pip
- `dandi==0.64.0` # installed with pip

**Comment by colleenjg** [comment]
By the way, if anyone coming across this issue is trying to do this kind of thing (stream, pop out a module and save), it does work with `fsspec`, as mentioned above. The following code was written based on the [PyNWB streaming tutorial](https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/streaming.html)

**Issue-relevant note:** Should have tested this the first time around. The biggest the file ever gets with `ros3` is 464.7 MB. The file created with `fsspec` is 477.8 MB. So whatever the `ros3` method is doing is stopping short of the last 13 MB, for whatever reason.

```
import fsspec
from fsspec.implementations.cached import CachingFileSystem
from dandi.dandiapi import DandiAPIClient
import h5py
import pynwb

dandiset_id = "000054"
filepath = "sub-F1/sub-F1_ses-20190407T210000_behavior+ophys.nwb"
savepath = "sub-F1_ses-20190407T210000_behavior+ophys_small.nwb"

# obtain the URL for the file, based on the filepath
with DandiAPIClient() as client:
    asset = client.get_dandiset(dandiset_id, "draft").get_asset_by_path(filepath)
    asset_url = asset.get_content_url(follow_redirects=1, strip_query=True)

# create a cache folder
cache_store = "nwb-cache"
fs = CachingFileSystem(
    fs=fsspec.filesystem("http"),
    cache_storage=cache_store,
)

# stream file, pop out large module and save
with fs.open(asset_url, "rb") as f:
    with h5py.File(f, load_namespaces=True) as h5_handle:
        with pynwb.NWBHDF5IO(file=h5_handle) as read_io:
            read_nwbfile = read_io.read()
            read_nwbfile.acquisition.pop("TwoPhotonSeries")
            with pynwb.NWBHDF5IO(savepath, "w") as write_io:
                write_io.export(src_io=read_io, nwbfile=read_nwbfile,  write_args={"link_data": False})
    
fs.clear_cache() # seems to prevent a memory leak when running this for multiple files in a row.
```

**Comment by oruebel** [comment]
> By the way, if anyone coming across this issue is trying to do this kind of thing (stream, pop out a module and save), it does work with `fsspec`

@colleenjg thank you for the addition information! I'm not sure if the `ros3` issue is something we can fix on our end; I suspect that this may be due to network errors and `ros3` not retrying connections. The streaming tutorial already recommends `ffspec`. Are there maybe any changes to the streaming tutorial that would have helped avoid this issue? Since `ffspec` is working, do you think we can close this issue?

**Comment by colleenjg** [comment]
Sure!

**Comment by rly** [comment]
I suspect this has to do with how the NWB files in this particular dandiset 000054 were chunked. 

When I ran the MWE, most of the 477.8 MB was written, but the rate of growth of the file started slowing down significantly at around 462 MB and I had to kill hte process.

The dataset at `/processing/ophys/ImageSegmentation/PlaneSegmentation/image_mask` has dtype float32 and shape (1003, 796, 512). The chunk shape is (1, 100, 64). And it is compressed with zstd level 9 (!!!). That means there are 64,003 small chunks that each have to be requested from DANDI and decompressed in an expensive manner. (Note @oruebel @mavaylon1: the ophys file in the NWB benchmarks comes from this dandiset...). Reading that entire dataset using ros3 and doing nothing else takes over an hour. I killed the process. I suspect reading that dataset from S3 and writing it to disk is the issue.

As an aside, it seems that when reading data with ros3, ctrl-c does not kill the process in the Mac terminal... :\

In the past couple years, we have been recommending much larger chunk sizes than (1, 100, 64) to address this issue.

**Comment by colleenjg** [comment]
@rly I see - thank you for checking this out. Do you have an idea of why the chunking and compression would make things so slow with ros3, but not with fsspec?

**Comment by oruebel** [comment]
> Do you have an idea of why the chunking and compression would make things so slow with ros3, but not with fsspec?

The principle issue is likely: 1) how many web-requests and 2) how much data ros3 vs. fsspec need to transfer. E.g., ffspec is setup with a local cache, which helps to reduce web-requests for repeat access (e.g. to metadata). We are working on more detailed benchmarks to profile the differences between ros3, fsspec, Zarr, Lindi, remfile etc. as part of the nwb benchmarks https://nwb-benchmarks.readthedocs.io/en/latest/

**Comment by colleenjg** [comment]
I see - interesting! Well thank you both for looking into this. It was bothering me that I couldn't get it to work, and couldn't figure out why.
Also @rly, I noticed that too: ctrl+c did not kill the process in the Linux terminal either.
