### ISSUE TITLE
[Bug]: `test_mock.py::test_mock[mock_OnePhotonSeries]` fails with a TypeError on `=pynwb-2.3.1`

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/pynwb#1676]
### What happened?

One test fails when running the test suite.

### Steps to Reproduce

```python
Full build log: https://ppb.chymera.eu/1fd947.log
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.10

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
This issue was fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1660. We are preparing a patch release of PyNWB that includes this and other bug fixes.
