### ISSUE TITLE
Visualize table in pyNWB ("ValueError: Not a dataset (not a dataset)")

### ISSUE THREAD

**Issue by GoktugAlkan** [NeurodataWithoutBorders/pynwb#1699]
Hello,

Currently, I am double-checking our nwb files, i.e., I am trying to see whether our nwb files that we created with `matNWB` can be opened and used in full extend in `pyNWB`. 

The nwb files that I am investigating contain the a trials field (`nwb.intervals_trials` in `matNWB` and `nwb.trials` in `pyNWB`). By executing `toTable(nwb.intervals_trials)` we can visualize the trials as a table in `matNWB`. However, when I run the analogous command in `pyNWB`, i.e., when I execute `nwb.trials.to_dataframe()` in `pyNWB`, the table is not visualized. I get the following error message: `ValueError: Not a dataset (not a dataset)`. 

When I execute `type(read_nwbfile.trials)`, the following is shown: `pynwb.epoch.TimeIntervals`.

Many thanks in advance!

**Comment by rly** [comment]
That error suggests that the file has been closed when you run `nwb.trials.to_dataframe()`.
Are you keeping the file open in PyNWB when that command is run? It needs to stay open for that command to work because the data are read lazily from the file, and the file needs to be open for that to work.

**Comment by GoktugAlkan** [comment]
@rly Thanks a lot! That solves the problem! I'll close this issue
