### ISSUE TITLE
Add functionality to reformat old NWB files

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#17]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

Existing NWB users will need a way to reformat their old files to comply with new schema and layout.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/17

**Comment by oruebel** [comment]
@ajtritt is this in part addressed by the legacy data read (i.e., at least for the Allen data)?

**Comment by t-b** [comment]
@nicain Do you know more about that?

**Comment by oruebel** [comment]
@t-b I closed this issue, because it was an old ticket from early on in the project (even before we moved to GitHub). The legacy read support that @nicain added addressed this issue for the Allen data.
