### ISSUE TITLE
[Feature]: enh mock to include nwbfile

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1705]
### What would you like to see added to PyNWB?

in response to https://github.com/NeurodataWithoutBorders/pynwb/issues/1701

change all mock functions to include an nwbfile parameter

e.g.

```python
def mock_ElectrodeGroup(
    name=None,
    description="description",
    location="location",
    device=None,
    position=None,
    nwbfile: Optional[NWBFile] = None,
):

    electrode_group = ElectrodeGroup(
        name=name or name_generator("ElectrodeGroup"),
        description=description,
        location=location,
        device=device or mock_Device(nwbfile=nwbfile),
        position=position,
    )

    if nwbfile is not None:
        nwbfile.electrode_groups.append(electrode_group)

    return electrode_group
```

### What solution would you like?

do for all neurodata types and add tests

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by mavaylon1** [comment]
I'll tackle this starting Monday
