### ISSUE TITLE
[Feature]: Make pynwb conda package for powerlinux available on conda-forge

### ISSUE THREAD

**Issue by dfsp-spirit** [NeurodataWithoutBorders/pynwb#1714]
### What would you like to see added to PyNWB?

It would be great if a `pynwb` package for architecture `linux-ppc64le` was available on [pynwb conda-forge](https://anaconda.org/conda-forge/pynwb).

We tried to add `pynwb` as a dependency to our project, but this is not possible since it will break support of our application for powerlinux. The only possible workaround is to remove pynwb as a dependency (what we did for now), and check for availability of the package at runtime when users try to call functions from our software that rely on pynwb. This will then result in an exception being thrown under powerlinux. For us, powerlinux is an essential architecture as our institute has powerlinux machines with 1000+ cores and 2TB of RAM, which are used frequently to run our software.

### Is your feature request related to a problem?

We tried to add pynwb as a dependency to our project, but this is not possible since it will break support of our application for powerlinux.

### What solution would you like?

Make `pynwb` package for architecture `linux-ppc64le` available on conda-forge.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
Thanks for the bug report. I submitted a PR to add builds for powerlinux here: https://github.com/conda-forge/pynwb-feedstock/pull/51 . It is on hold due to what should be an unrelated issue with HDMF and versioning. We should be able to get that sorted out in the next few days and then make a new conda-forge release for pynwb.

**Comment by bendichter** [comment]
Is there a reason you can't just use pip in the meantime?

**Comment by dfsp-spirit** [comment]
@rly Thanks for the quick response.

@bendichter You mean by mixing conda and pip in the conda environment? I am not the biggest fan, but that's indeed an option. I will give it a try on our CI system while waiting for the conda release. Thanks! _UPDATE_: It works to install via pip. Great!

**Comment by rly** [comment]
This is fixed now. Please try the latest conda-forge version of pynwb and let me know if that works for you.
