### ISSUE TITLE
[Feature]: add testing for beta release of Python 3.12

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1716]
### What would you like to see added to PyNWB?

We should start adding continuous integration testing for the beta release of Python 3.12 to try to get ahead of the official release and identify any possible hurdles.

### What solution would you like?

See above

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by stephprince** [comment]
I think all CI testing was updated for Python 3.12 with https://github.com/NeurodataWithoutBorders/pynwb/pull/1853.
