### ISSUE TITLE
Removing master branch

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#173]
Keeping the `master` branch around is confusing (there is only 4 commits), unless there is plan to merge `dev` into master I suggest we remove it.

**Comment by jcfr** [comment]
Cc: @dorukozturk @oruebel @mgrauer

**Comment by ajtritt** [comment]
We can remove it. I created it early on, per a convention I have used in previous projects. Since releases will be cut from dev, I don’t see a purpose for master.

**Comment by jcfr** [comment]
Great. `master` branch has been removed.
