### ISSUE TITLE
[Feature]: Run sphinx build in nitpicky mode to check internal links

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1731]
### What would you like to see added to PyNWB?

We can run `sphinx-build -n ...` to have sphinx check internal links. We currently check external links through the sphinx --linkcheck option but this does not check whether references like `pynwb.base.ProcessingModules` exists. When running this locally, I get over 100 broken internal links in docstrings, and about 30 broken internal links in tutorials.

### What solution would you like?

Update Makefile and make.bat in docs to use the sphinx option `-n`. Run `make html`. Fix all the warnings about broken links.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
We can also set this option and configure ignores in `conf.py` : https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky

**Comment by bendichter** [comment]
Would you clarify this? If I run

sphinx-build -n source build html

I don't see any errors
