### ISSUE TITLE
[Feature]: Read linked files with only warnings rather than errors 

### ISSUE THREAD

**Issue by tuanpham96** [NeurodataWithoutBorders/pynwb#1742]
### What would you like to see added to PyNWB?

It would be nice to be able to read files that are created by linking with only warnings rather than errors, when one of the files is missing, for example. For example, sharing a file with only processed data to others and they can still read the files, rather than they only have to also download the raw files that tend to be big.

### What solution would you like?

As @oruebel mentioned, when loading in a file that's supposed to link to a missing file, pynwb can just throw warnings as `MISSING` and still allow users to read the data inside that file.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
Thanks for creating this issue @tuanpham96. This issue will need to be addressed in HDMF. Unfortunately GitHUb does not allow transferring issues between repos in different organizations. I, therefore, create a corresponding new issue on HDMF here https://github.com/hdmf-dev/hdmf/issues/920.
