### ISSUE TITLE
[Feature]: Support stimulus_template column in IntracellularRecordingsTable

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#1747]
### What would you like to see added to PyNWB?

See https://github.com/NeurodataWithoutBorders/nwb-schema/pull/545

### What solution would you like?

Update StimulusTable to support the new optional column

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by stephprince** [comment]
Support for the stimulus_template column was added when schema 2.7.0 changes were merged - https://github.com/NeurodataWithoutBorders/pynwb/pull/1820
