### ISSUE TITLE
CI: Upload to pypi

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#176]
@ajtritt  While we are finalizing the process, would be great if you could add @dorukozturk and myself as package maintainer on pypi. See https://pypi.python.org/pypi/pynwb

My pypi username is `jcfr`

**Comment by jcfr** [comment]
Cc: @mgrauer @oruebel

**Comment by dorukozturk** [comment]
My pypi username is "dorukozturk"

**Comment by ajtritt** [comment]
Done
