### ISSUE TITLE
[Feature]: Warn on read rather than error

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#1786]
### What would you like to see added to PyNWB?

In `TimeSeries` (and likely a few other places) additional error checks are performed on `__init__` to ensure the data is valid. E.g,.:

https://github.com/NeurodataWithoutBorders/pynwb/blob/eb585063b3e035d68f206c49ff19200f9f25fa43/src/pynwb/base.py#L175-L191

This makes sense when creating a new file to ensure that we don't create invalid files. However, on read it would be useful to warn instead and continue to attempt to read the file to try and give access to the data if at all possible. 

### Is your feature request related to a problem?

Related to https://github.com/NeurodataWithoutBorders/helpdesk/discussions/62

### What solution would you like?

Use the `self._error_on_new_warn_on_construct` method instead of `ValueError` in the `TimeSeries` constructor. 

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
See 
https://github.com/NeurodataWithoutBorders/pynwb/tree/dev/src/pynwb/image.py#L112C14-L118
for example
