### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by dorukozturk** [NeurodataWithoutBorders/pynwb#180]
https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/io/core.py#L14 Should this line be def carg_data?

**Comment by nicain** [comment]
Yes! Nice catch

**Comment by ajtritt** [comment]
Yes, it should be, but it doesn't matter, the name of the methods decorated with `ObjectMapper.constructor_arg` and `ObjectMapper.obj_attr` does not matter.
