### ISSUE TITLE
[Feature]: load nwb file without initial preload step

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/pynwb#1814]
### What would you like to see added to PyNWB?

@rly If I am remembering correctly I think you provided an example where you could load an nwb file without preloading all the metadata... so that it is not as time-consuming on initial load. This is relevant when loading remote files.

### What solution would you like?

It's possible I am imagining it. But if that is possible, how do you do it? If not, this would be an important feature for what I am working on. Otherwise I will need to continue working directly with the h5py object. Thanks.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
I don't think this is possible right now. We are working on options to support kerchunk and Zarr with consolidated metadata, which should help. Supporting read without constructing the full hierarchy would require some work. I'm not exactly sure right now what the best way would be to implement this, maybe some option that would only read the first level of the hierarchy and then have wrappers for delayed read of groups, but I don't think this is trival to implement. Happy to discuss.

**Comment by magland** [comment]
Okay that makes sense - yeah it seems that would be difficult. I just thought there might be something existing. Feel free to close.

**Comment by rly** [comment]
Yes, @oruebel is correct.
