### ISSUE TITLE
[Bug]: Invalidation of typical session ID

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/pynwb#1819]
### What happened?

Very strange/silly bug just discovered by the JazLab; not sure how long this has technically been around (I usually use underscores in session IDs personally)

### Steps to Reproduce

```python
from pynwb.testing.mock.file import mock_NWBFile
from pynwb import NWBHDF5IO

with NWBHDF5IO(path=".../Downloads/test_invalid.nwb.hdf5", mode="w") as io:
    io.write(mock_NWBFile(session_id="2024-01-01"))
```

### Traceback

```python
- found the following errors:
root/general/session_id (general/session_id): incorrect type - expected 'text', got 'isodatetime'
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.11

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
This looks like an issue with the validator. I'll create a ticket on HDMF.

**Comment by rly** [comment]
This has been fixed in https://github.com/hdmf-dev/hdmf/pull/1026 and will be available in the next HDMF release sometime next week.
