### ISSUE TITLE
[Documentation]: Need tutorial for writing in Zarr

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1832]
### What would you like changed or added to the documentation and why?

I just did a search over the PyNWB RDT for "Zarr" and came up with nothing. This seems like it would be a common route for users, so we should provide some guidance.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
We have the following two tutorials in the HDMF-Zarr docs;

- https://hdmf-zarr.readthedocs.io/en/latest/tutorials/plot_nwb_zarrio.html#sphx-glr-tutorials-plot-nwb-zarrio-py
- https://hdmf-zarr.readthedocs.io/en/latest/tutorials/plot_convert_nwb_hdf5.html#sphx-glr-tutorials-plot-convert-nwb-hdf5-py

I think adding a short tutorial here is a good idea to make this easier to find for users
