### ISSUE TITLE
[Feature]: Warn to use index argument on call to add_trial (or add_row)

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/pynwb#1856]
### What would you like to see added to PyNWB?

From https://github.com/NeurodataWithoutBorders/helpdesk/discussions/71#discussioncomment-8638454

User was confused by HDMF level error during `io.write`. Caused by not declaring a column to be 'indexed' and giving it ragged input across different rows (which worked fine to add to the in-memory NWBFile object)

### What solution would you like?

Warn or error on trying to add the value while still in-memory rather than waiting until writing to disk

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by oruebel** [comment]
@stephprince can you help with this issue? I believe this is will most likely need to be addressed in HDMF so we may want to transfer the issue to HDMF.

**Comment by stephprince** [comment]
This was fixed in hdmf (https://github.com/hdmf-dev/hdmf/pull/1066) and will be available at the next release.
