### ISSUE TITLE
editing nwb file -- is the recommended way to use h5py?

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/pynwb#1874]
Tagging @yarikoptic who is also interested

Suppose I want to modify something in an existing nwb file, like modifying the subject information).

Apologies if this is covered in a different issue. I did a quick search and came across this issue:
https://github.com/NeurodataWithoutBorders/pynwb/issues/1773

and this notebook
https://gist.github.com/rly/be7bee420b482b9ddcd084f57cc4115e

It seems this is not possible using pynwb. So do we use h5py manually instead? In that case it requires special knowledge of the spec to know that we are not breaking the validation. Is this the recommended approach?

**Comment by CodyCBakerPhD** [comment]
See this tutorial: https://pynwb.readthedocs.io/en/stable/tutorials/advanced_io/plot_editing.html#sphx-glr-tutorials-advanced-io-plot-editing-py

For anything outside of that, `h5py` must be used. With extreme caution. It's easy to create an invalid or even corrupt NWB file this way
