### ISSUE TITLE
Question: why is `grid_spacing` not a field in `ImagingPlane`?

### ISSUE THREAD

**Issue by h-mayorquin** [NeurodataWithoutBorders/pynwb#1885]
I would like to understand the logic of why some attributes of the class are fields and others are not. For the `ImagingPlane` we are missing `grid_spacing` and `origin_coords`

https://github.com/NeurodataWithoutBorders/pynwb/blob/2259bede338f2f202229bda0af15d7e3cea47369/src/pynwb/ophys.py#L33-L46

This is related to the html representation of the object. We use the fields to generate the html representation (that is very handy for exploring) and therefore some attributes are not displayed because they are not fields which I think is a big miss.

https://github.com/hdmf-dev/hdmf/blob/d85d0cbc36d2e0fdb25e8fbea14d58ba7bf24a40/src/hdmf/container.py#L685-L693

**Comment by oruebel** [comment]
@rly thoughts?

**Comment by h-mayorquin** [comment]
For future reference I discussed this with @rly in person. This is a bug and attributes here mentioned should be fields. https://github.com/NeurodataWithoutBorders/pynwb/pull/1892 should solve this.

It is still unclear to me if all the arguments of a constructor in pynwb should be fields. Is that the case?
