### ISSUE TITLE
[Bug]: Numpy 2.0

### ISSUE THREAD

**Issue by mavaylon1** [NeurodataWithoutBorders/pynwb#1896]
### What happened?

Numpy 2.0 deprecated some functions, leading to tests not passing in the run all tests workflow. The simple fix I have planned in hdmf-zarr/hdmf is to just pin numpy below 2.0 until python 3.8 is deprecated in October. We can then update the deprecations then.

### Steps to Reproduce

```python
run all tests workflow
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

lower version (unsupported)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
HDMF now supports numpy 2.0. @mavaylon1 said that he will bump up the requirements in pynwb to include numpy 2.0 and coordinate with @stephprince on a new bugfix release in the next two weeks.
