### ISSUE TITLE
Some functions have high cyclomatic complexity

### ISSUE THREAD

**Issue by dorukozturk** [NeurodataWithoutBorders/pynwb#191]
[This](https://en.wikipedia.org/wiki/Cyclomatic_complexity) is a nice complexity check for functions. This is optional but I believe it is good practice to have lower numbers. Here is a list of complex functions in pynwb currently:

- ./src/pynwb/form/utils.py:10:1: C901 '__type_okay' is too complex (13)
- ./src/pynwb/form/utils.py:82:1: C901 '__parse_args' is too complex (16)
- ./src/pynwb/form/backends/hdf5/h5tools.py:423:5: C901 'HDF5IO.__list_fill__' is too complex (15)
- ./src/pynwb/form/spec/spec.py:190:5: C901 'BaseStorageSpec.__init__' is too complex (14)
- ./src/pynwb/form/spec/spec.py:758:5: C901 'GroupSpec.is_inherited_spec' is too complex (16)
- ./src/pynwb/form/spec/namespace.py:267:5: C901 'NamespaceCatalog.load_namespaces' is too -
- complex (13)
- ./src/pynwb/form/validate/validator.py:262:5: C901 'GroupValidator.validate' is too complex (17)
- ./src/pynwb/form/build/map.py:489:5: C901 'ObjectMapper.__add_groups' is too complex (13)

It would be fantastic if we could lower them by doing some refactoring.

**Comment by bendichter** [comment]
@dorukozturk what tool did you use to compute cyclomatic complexity?

**Comment by t-b** [comment]
@bendichter 

```
$ git diff setup.cfg
diff --git a/setup.cfg b/setup.cfg
index cbd08fba..0529670b 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -10,7 +10,7 @@ tag_prefix = *.*.*

 [flake8]
 max-line-length = 120
-max-complexity = 17
+max-complexity = 13

 [metadata]
 description-file = README.rst

thomas@thomas-win7-x64 MINGW64 /e/projekte/pynwb (master)
$ flake8 src/
src/pynwb\base.py:91:5: C901 'TimeSeries.__init__' is too complex (14)
src/pynwb\core.py:761:5: C901 'MultiContainerInterface.__build_class' is too complex (16)
src/pynwb\form\array.py:96:5: C901 'AbstractSortedArray.__eq__' is too complex (17)
src/pynwb\form\backends\hdf5\h5tools.py:313:5: C901 'HDF5IO.__read_dataset' is too complex (14)
src/pynwb\form\build\map.py:773:5: C901 'ObjectMapper.__add_groups' is too complex (15)
src/pynwb\form\build\map.py:856:5: C901 'ObjectMapper.__get_subspec_values' is too complex (16)
src/pynwb\form\spec\spec.py:300:5: C901 'BaseStorageSpec.__init__' is too complex (14)
src/pynwb\form\spec\spec.py:613:5: C901 'DatasetSpec.__init__' is too complex (15)
src/pynwb\form\spec\spec.py:828:5: C901 'GroupSpec.resolve_spec' is too complex (16)
src/pynwb\form\spec\spec.py:940:5: C901 'GroupSpec.is_inherited_spec' is too complex (16)
src/pynwb\form\spec\spec.py:975:5: C901 'GroupSpec.is_overridden_spec' is too complex (17)
src/pynwb\form\validate\validator.py:365:5: C901 'GroupValidator.validate' is too complex (17)
```

**Comment by dorukozturk** [comment]
@bendichter 

There are other metrics such as [cognitive complexity](https://www.sonarsource.com/docs/CognitiveComplexity.pdf).

I have ran something called [codeclimate](https://codeclimate.com/) against pynwb repo and here are the results. 

https://dorukozturk.github.io/pynwb-codeclimate/

I think following this blindly is not necessarily a good approach but at least fixing/refactoring the 
high complexity functions is a good start for the long term maintainability of the project.

**Comment by rly** [comment]
Except for a function in the legacy module which is no longer used, we have fixed or moved to HDMF all high complexity functions that fail flake8 check C901.
