### ISSUE TITLE
[Feature]: Set default identifier to UUID

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1917]
### What would you like to see added to PyNWB?

The NWB schema says that the identifier should be unique. https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.file.yaml#L27-L31

To simplify the creation of an NWB file, I suggest that we set the default identifier to be `str(uuid4())`. Users can still customize this if they want. 

### What solution would you like?

^

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by stephprince** [comment]
maybe related to this discussion: https://github.com/NeurodataWithoutBorders/pynwb/issues/954?

**Comment by rly** [comment]
Oh. Oops. That's the same issue and a better resolution, because NWBFile already has an object id. Thanks. I propose we make that potentially breaking change in the API in the next major release.
