### ISSUE TITLE
Clean up repo organization

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#192]
In the interest of keeping the repository clean, move all CI/CD config and other files into a subdirectory. 

If this breaks CI/CD platforms or causes too many problems, we can close it out.

**Comment by dorukozturk** [comment]
The CI/CD services have standard locations. I think it is not impossible to move them, but by convention keeping them is a better idea. Almost all big projects have appveyor, travis, circle or tox files in their repository. Here are few examples ([numpy](https://github.com/numpy/numpy), [scipy](https://github.com/scipy/scipy), [jupyter](https://github.com/jupyter/notebook),  etc.)
