### ISSUE TITLE
Update install instructions on getting_started page

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#196]
Once PyNWB is available on PIP / CONDA, the install instructions in docs/source/getting_started.rst should be updated. Also, the requirements on that page need to be updated (e.g., currently it still lists Python 3 only). @dorukozturk would you be able to do this before SfN?

**Comment by dorukozturk** [comment]
I think updating the docs is doable. One thing that I am not sure about is the conda-forge recipe. Once we submit it, we will wait for someone from their end to review and approve. The following will be the command. But first it has to be published on conda-forge. 
```
conda install -c conda-forge pynwb
```
This might not be ready for sfn.

**Comment by neuromusic** [comment]
the channel could still be created on anaconda cloud and installed with

```
conda install -c pynwb pynwb
```

see e.g. this random channel hosting seaborn builds: https://anaconda.org/mutirri/seaborn

once/if it gets approved on conda-forge, then it's just one line to change in the docs

**Comment by dorukozturk** [comment]
@neuromusic thanks. Then the answer is yes. We can create our own channel and see how it goes.
