### ISSUE TITLE
[Feature]: Add new Device fields from NWB schema 2.8.0

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1987]
### What would you like to see added to PyNWB?

https://github.com/NeurodataWithoutBorders/nwb-schema/pull/594 added new optional `Device` neurodata type metadata fields. The corresponding `Device` class needs to be updated.

### What solution would you like?

See above.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by h-mayorquin** [comment]
This is great.

**Comment by rly** [comment]
Fixed by #1997
