### ISSUE TITLE
[Documentation]: Update text describing LFP and FilteredEphys in ecephys tutorial.

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/pynwb#2005]
### What would you like changed or added to the documentation and why?

I am working through the matnwb tutorial and the following seems inaccurate:

About LFP:
> LFP data is typically considered processed data because the raw data was filtered and downsampled to generate the LFP.

About FilteredEphys
> If the derived data is filtered, but not downsampled, you can store the data in an ElectricalSeries object in a FilteredEphys object instead of a object.

Filtered ephys refers to filtering in general, and does not concern resampling. The schema description seems accurate:

> Overview: Electrophysiology data from one or more channels that has been subjected to filtering. Examples of filtered data include Theta and Gamma (LFP has its own interface). 

https://nwb-schema.readthedocs.io/en/latest/format.html#filteredephys

Suggestions for new text [edited]

**LFP:**
LFP refers to data that has been low-pass filtered, typically below 300 Hz. This data may also be downsampled. Because it is filtered and potentially resampled, it is categorized as processed data.

**FilteredEphys:**
If your data is filtered for frequency ranges other than LFP—such as Gamma or Theta—you should store it in an ElectricalSeries and encapsulate it within a FilteredEphys object.

@bendichter @stephprince @oruebel 
Please let me know your opinions

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by ehennestad** [comment]
From the documentation:

> Filter properties should be noted in the ElectricalSeries ‘filtering’ attribute.
https://nwb-schema.readthedocs.io/en/latest/format.html#lfp

This seems like a key property that should be highlighted and exemplified in these examples

**Comment by bendichter** [comment]
Oh yeah good point!

Ben Dichter, PhD
Data Science Consultant
personal website <http://bendichter.com/>

**Comment by stephprince** [comment]
> > If the derived data is filtered, but not downsampled, you can store the data in an ElectricalSeries object in a FilteredEphys object instead of a object.

> Filtered ephys refers to filtering in general, and does not concern resampling.

I think you're suggesting we remove the "but not downsampled" statement? If so I agree, in my experience at least theta/gamma filtering is often applied to the downsampled LFP data, and filtered ephys should not concern resampling.

I think demonstrating the `filtering` attribute is also a good idea!

**Comment by rly** [comment]
Just to add:
- You can also store multiple filtered time series data in a single `DecompositionSeries` object: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/473fcc41e871288767cfb37d83315cca7469b9d1/core/nwb.misc.yaml#L103
- I admit I did not realize NWB had a `FilteredEphys` type. It is used in only one public dandiset, 000070, and has never featured prominently in tutorials or use cases I have seen. 

I like @ehennestad 's  proposed new text. For `FilteredEphys`, if it's not clear in the surrounding text, it should be made clear that that is typically also considered processed data...

I also think demonstrating the `filtering` attribute is a good idea.

**Comment by ehennestad** [comment]
> You can also store multiple filtered time series data in a single DecompositionSeries object

I think the decomposition series is meant for the results of spectral analysis, which is a different operation than filtering

> For FilteredEphys, if it's not clear in the surrounding text, it should be made clear that that is typically also considered processed data...

good point!

**Comment by rly** [comment]
> I think the decomposition series is meant for the results of spectral analysis, which is a different operation than filtering

You are right! My mistake.
