### ISSUE TITLE
 [Documentation]: "Designating Electrophysiology Data" Section in Ecephys Tutorial

### ISSUE THREAD

**Issue by ehennestad** [NeurodataWithoutBorders/pynwb#2006]
### What would you like changed or added to the documentation and why?

The following text does not make much sense to me:

As mentioned above, ElectricalSeries objects are designed for storing specific types of extracellular recordings. In addition to this TimeSeries class, NWB offers Processing Modules to help designate the type of data being stored. We will briefly discuss these modules here and refer the reader to the API documentation and NWB File Basics for more details on using these objects.

Do others agree? @bendichter @stephprince @oruebel 

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by ehennestad** [comment]
Realising that this is removed from the latest version of the [.py tutorial](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/gallery/domain/ecephys.py) file, but it is still present in the pynwb reathedocs page: https://pynwb.readthedocs.io/en/latest/tutorials/domain/ecephys.html#designating-electrophysiology-data

**Comment by oruebel** [comment]
> but it is still present in the pynwb reathedocs

I just manually initiated a rebuild of the ReadTheDocs. It looks like the "latest" version was build 5 month ago, so maybe a trigger failed. Hopefully that will fix the issue.
