### ISSUE TITLE
warnings package not imported (OS X / anaconda)

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#201]
Trying to create an extension to ElectrodeGroup that adds an Epoch datatype:
`FL_ElectrodeGroup_ext = NWBGroupSpec('Frank Lab Electrode Group',
								 groups=[NWBGroupSpec('valid_times', 'time range over which this electrode group is defined', 'Epoch')],
								 neurodata_type_inc='ElectrodeGroup',
								 neurodata_type_def='FL_ElectrodeGroup')
`
produces

`/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.post1273+g851f171-py3.6.egg/pynwb/form/spec/spec.py in __init__(self, **kwargs)
    188         if default_name:
    189             if name is not None:
--> 190                 warn("found 'default_name' with 'name' - ignoring 'default_name'")
    191             else:
    192                 self['default_name'] = default_name

NameError: name 'warn' is not defined`

Presumably this is because the warnings package is not included.

**Comment by dorukozturk** [comment]
@lfrank Thank you. I was able to reproduce the error and pushed a fix. Can you try now?

**Comment by lfrank** [comment]
@dorukozturk That did it; thanks...
