### ISSUE TITLE
remove get_build_manager dependency from validator

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#203]
pynwb/validate.py still calls get_build_manager. This code needs to be updated to call pynwb.get_manager

**Comment by oruebel** [comment]
Pull request #187 I believe fixes that part

**Comment by jcfr** [comment]
Closing, This is fixed in https://github.com/NeurodataWithoutBorders/pynwb/commit/f2d12e6bd155cb52331c1f11b58e4737317d4adc
