### ISSUE TITLE
Add I/O Gist to examples/tutorials

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#206]
Add the I/O Gist from #171

https://gist.github.com/ajtritt/11f2bda4846a96eb67cd9e9a7e1b2bdc

As part of an I/O tutorial for PyNWB

**Comment by ajtritt** [comment]
I think this is obsolete. The gist is also not runnable, so it can't be tested.  Most of this functionality is taken care of elsewhere in the docs, so I will close for now.
