### ISSUE TITLE
docs: Update "Getting Started"

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#215]
See https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/source/getting_started.rst

* [ ] prerequisites are also incorrect
* [ ] since we will have package available on pypi, pip should be used

* [ ] To install the latest dev version, the following should be documented:

```
 pip install pynwb --find-links https://github.com/NeurodataWithoutBorders/pynwb/releases/tag/latest  --no-index
```

Installing the dev package is pending resolution of #216

**Comment by dorukozturk** [comment]
Fixed by #223
