### ISSUE TITLE
docs: Ensure documentation build locally match readthedocs theme.

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#219]
Ensure documentation build locally match readthedocs theme.

For example:

https://github.com/scikit-build/cmake-python-distributions/blob/a6ed3f1c89a88c3968792d167313716dbb96b33b/docs/conf.py#L343-L351

**Comment by dorukozturk** [comment]
@jcfr Can you clarify this issue a little bit more.

**Comment by jcfr** [comment]
I originally posted this because I didn't see the "usual" construct I am used to at the end of the conf file.

This used to be the recommendation: https://pypi.python.org/pypi/sphinx_rtd_theme/0.2.4#using-this-theme-locally-then-building-on-read-the-docs

But is not anymore in the latest version: https://pypi.python.org/pypi/sphinx_rtd_theme/0.2.5b1#via-package 

It became easier to integrate with https://github.com/rtfd/sphinx_rtd_theme/commit/f539c0e1f2001558ee29ea117585c1d864aa9cf7 

Also this approach seems to be outdated https://github.com/rtfd/sphinx_rtd_theme/commit/dc9d3d732e4f56a5c8dbda8c41967019fd8ae4c8 but can be found in a lot of project ...
