### ISSUE TITLE
ci: Consolidate Makefile  and make.bat

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#221]
Since Makefile are not supported across platform and we would like to support developer on windows.

I suggest to:

* remove the top level Makefile
* use only docs/Makefile or docs/make.bat for documentation generation

**Comment by oruebel** [comment]
@jcfr I personally find the makefile very useful from a developer perspective because it provides shorthands for many calls that I otherwise might forget. My personal vote is to keep it or at least have an alternative for it.

**Comment by nicain** [comment]
I've been bitten several times by the make file; my vote is to use a platform independent alternative.

**Comment by jcfr** [comment]
Thanks for the feedback, I will think about our options and try to propose something accommodating both of you and minimizing inconsistencies.

**Comment by oruebel** [comment]
Since the Makefile is mainly a collection of convenient shorthands for other command-line calls a possible solution may be to just turn it into a Python script instead. @ajtritt do you have any preferences on this?

**Comment by jcfr** [comment]
Thanks for the feedback. Closing for now.

To have a cross platform convenient way, an approach could be to:

* introduce dependency on `ninja`. See https://pypi.python.org/pypi/ninja, replace Makefile and make.bat. with a `build.ninja`

this would avoid to have to maintain multiple "build" files.
```
