### ISSUE TITLE
docs: Use consistent keywords/tags/topics associated with GitHub, readthedocs and setup.py

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#224]
So far, we have:

* [x] readthedocs:  ~pynwb, nwb, python~  
  * **Updated**: See https://readthedocs.org/projects/pynwb/
* [x] setup.py: PyNWB NWB Neuroscience HDF NeurodataWithoutBorders
  * **Updated:**: See https://github.com/NeurodataWithoutBorders/pynwb/pull/225
* [x] github: ~None~
  * **Updated**: See https://github.com/NeurodataWithoutBorders/pynwb

~I plan to update the list to:~

**Updated** list is:

```
Neuroscience
python
HDF
HDF5
cross-platform
open-data
data-format
open-source
open-science
reproducible-science
PyNWB
NWB
NWB:N
NeurodataWithoutBorders
```

For GitHub where only letters, numbers and dashes:

```
neuroscience
python
hdf
hdf5
cross-platform
open-data
data-format
open-source
open-science
reproducible-research
pynwb
nwb
nwb-n
neurodata-without-borders
```

~ @oruebel @nicain @ajtritt @mgrauer @dorukozturk  Let me know what you think ?~

**Comment by ajtritt** [comment]
Please add `HDF5`, too

**Comment by oruebel** [comment]
Please add ``NWB:N`` as well

**Comment by jcfr** [comment]
Updated list:
```
Neuroscience
python
HDF
HDF5
cross-platform
open-data
data-format
open-source
open-science
reproducible-science
PyNWB
NWB
NWB:N
NeurodataWithoutBorders
```

**Comment by jcfr** [comment]
Since on github:
* the ":" is not allows in topic name: is `NWB-N` ok ? We can also omit it there.
* lower case is the convention. Would `neurodata-without-borders` work instead of `neurodatawithoutborders` ?

For Github, the list would then be:

```
neuroscience
python
hdf
hdf5
cross-platform
open-data
data-format
open-source
open-science
reproducible-research
pynwb
nwb
nwb-n
neurodata-without-borders
```

**Comment by jcfr** [comment]
`reproducible-science` -> `reproducible-research`

**Comment by jcfr** [comment]
* GitHub:

![pynwb-github-project](https://user-images.githubusercontent.com/219043/32630159-a4ae1386-c569-11e7-8975-a3112fb11263.png)

**Comment by jcfr** [comment]
* ReadTheDocs:

![pynwb-rtd-tags-v2](https://user-images.githubusercontent.com/219043/32631180-6ef51600-c56d-11e7-8063-253b6b2de1d5.png)
