### ISSUE TITLE
Relationship encoding

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#23]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

1. Need to be able to link data and timestamps between TimeSeries

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/23

**Comment by oruebel** [comment]
Related to https://github.com/hdmf-dev/hdmf/pull/192

**Comment by rly** [comment]
This topic has been expanded on in #626.
