### ISSUE TITLE
Fix CodeCov environment to match one of the test environments

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#240]
## 1) Bug

When CircleCI runs codecov, it seems to be running with a different environment. Unit tests for both Py2 and Py3 pass, but codecov fails when running the same code.

See [this build](https://circleci.com/gh/NeurodataWithoutBorders/pynwb/414?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

## 2) Feature Request
Ensure that codecov runs the in the same environment

### Problem/Use Case
Deployment gets held up, even though all tests pass.

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by jcfr** [comment]
Closing. Superseded by #245
