### ISSUE TITLE
ci: Upstream customization of python-versioneer

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#250]
### Problem/Use Case

We currently use a locally modified of `python-versioneer`. See https://github.com/NeurodataWithoutBorders/pynwb/commit/03408642ee51c47e2302bbd76d01b477f0b9b9f2

```
[This commit] customizes versionner so that it supports "tag_prefix"
specified as glob pattern.

Doing so allows to specify a glob pattern like "*.*.*" ensuring that
only tag matching our convention are considered.
```
The idea is to submit a PR against the upstream project https://github.com/warner/python-versioneer and with the maintainers to get the functionality integrated.

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by rly** [comment]
We are now using hatch-vcs instead of versioneer in pynwb
