### ISSUE TITLE
Update read-Allen-Brain-Oservatory notebook

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#253]
As notebook are usually considered a great source of examples, researchers will often copy snippet as a starting point.

Here are few suggestions to improve them:

* [x] add a cell briefly explaining the different between NWB 1.0 and NWB 2.0. And reference documentation
* [x] select a style. See #251
* [x] re-organize import. See below
* [x] Use print as a function. ``print(foo)`` instead of ``print foo``

### Import order

See https://www.python.org/dev/peps/pep-0008/#imports

Instead of:

```
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
import warnings
import pynwb
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
```

prefer

```
import warnings

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import pynwb
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
```

**Comment by nicain** [comment]
Consolidating feedback from @neuromusic for my own reference here:

> session_data_dict = {}
> for session_type, nwb_file_name in session_filename_dict.iteritems():
>    
>     legacy_map = pynwb.legacy.get_type_map()
>     nwbio = pynwb.NWBHDF5IO(nwb_file_name, extensions=legacy_map, mode='r')
>     with warnings.catch_warnings(record=True) as w:  # If nwb_version < 2.0, some warnings will be thrown
>         nwb_data = nwbio.read() 
>         session_data_dict[session_type] = nwb_data
>     
> pd.DataFrame(session_data_dict, index=[0])
> 
> This presumes a lot of knowledge: Pandas, pynwb's split between IO and NWB objects, type maps, context manager to suppress warnings.

- [x] Reduce complexity of this component.

> You never access the files for session A or session B. Can you kill the loop and open *one* file, breaking each of these steps into a separate cell with clear comments preceding each & explaining what they do?

- [x] Refactor example to only consider session_b (less to download and cache too...) 

defining the legacy type map
creating the IO instance
using the IO instance to read the file

How bad is it to let the warnings show here?

And if you do this, do you really need all of the space up above on querying w/ the allensdk? I'd suggest moving nearly everything under "Using allensdk to access the Brain Observatory" to the END of the notebook & strip this down to a simple "boc.get_ophys_experiment()" with your oeid hardcoded. Get into pynwb ASAP, then close with a broader description of the allensdk (no example code) and link out to our other notebooks that describe querying, etc.

- [x] Remove querying the allensdk

**Comment by nicain** [comment]
xref https://github.com/NeurodataWithoutBorders/pynwb/pull/252

- [x] add ! pip install pynwb and allensdk to first cell in jupyter notebook
