### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#261]
On http://pynwb.readthedocs.io/en/latest/example.html
`from form.backends.hdf5 import HDF5IO`

should be

`from pynwb.form.backends.hdf5 import HDF5IO`

**Comment by lfrank** [comment]
And as a follow-up: it would be great if someone could go through and try executing all of the example code to make sure it all works. I think there may be other typos / errors as well.

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/NeurodataWithoutBorders/pynwb/commit/3a03d4ae63d81d3eb25c1d78d091756db919c659

@neuromusic  @lfrank  See https://github.com/NeurodataWithoutBorders/pynwb/issues/260#issuecomment-344694677
