### ISSUE TITLE
docs: Update AnnotationSeries and AbstractFeatureSeries docstrings: Remove reference to create_timeseries

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#263]
This function has been removed in 9f07c23c3119d8b0a8bb49b3e0eaac8fcf787bab

**Comment by nicain** [comment]
Possibly related: on http://pynwb.readthedocs.io/en/latest/overview.html, the bullet points under "The following TimeSeries objects are provided by the API and NWB specification:" used to be clickable, but appear to no longer be links.  If resolving #263 doesn't cure this too, this will need its own issue.

**Comment by oruebel** [comment]
See http://pynwb.readthedocs.io/en/latest/pynwb.misc.html

**Comment by bendichter** [comment]
looks like this as been fixed.
