### ISSUE TITLE
docs: Fix ReadTheDocs so that it includes API documentation

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#267]
### Steps to Reproduce

See https://pynwb.readthedocs.io/en/latest/api_docs.html

### Suggested changes

Two approaches:

* ensure `make apidocs` is called on the readthedocs worked

* commit generated API rst files  (look if we could be added to and include from `docs/source/api`)

**Comment by nicain** [comment]
I am trying to implement some backwards compatibility for a different type of file (xref https://github.com/NeurodataWithoutBorders/pynwb/issues/275) and having the module documentation is really helpful
