### ISSUE TITLE
ci/test: Improve example testing harness

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#270]
* [ ] Change the test file names so that they are importable
* [ ] Moving creating-and-writing-nwbfile-2.py and creating-and-writing-nwbfile.py under tests/integration
* [ ] Importing them when needed rather than "load_source"ing them.
* [ ] Adding some assertions as opposed to just creating files and removing them? It might be better to make sure we check the integrity of the files(without testing the h5py library).

**Comment by oruebel** [comment]
This is an old issue. The testing harness has been improved significantly since this issue was created. I
