### ISSUE TITLE
Fixing flake8 warnings

### ISSUE THREAD

**Issue by dorukozturk** [NeurodataWithoutBorders/pynwb#277]
### Steps to Reproduce
Remove the #noqa comments and run:
```
flake8
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** All
- **Python Version:** All
- **Operating System:** All
- **Pynwb Version:** All

### Problem/Use Case
Flake8 does not just check styling of the code, but also does static code analysis. I suggest we go through all the # noqa comments in the code and slowly fix them since they might be red flags for the future. Some of them like F405 can be fixed by any developer but some of them requires deep PyNWB knowledge since some side effecty things are happening during imports. 

A project wide grep of those strings can be done with something like:
```
 grep -rP --include="*.py" "# noqa.*\d+" .
``` 

| Error Code  | Number of occurrences | Error Message |
| --------------- | -------------------------------- | ---------------------|
| F405  | 84  | name may be undefined, or defined from star imports: module |
| E402  | 26  | module level import not at top of file |
| F841  | 23  | local variable name is assigned but never used |
| F821  | 19  | undefined name |
| F401  | 14  | module imported but unused |
| F403  | 6  | ‘from module import *’ used; unable to detect undefined names |
| F811  | 4  | redefinition of unused name from line N |
| E501  | 4  | max line length > 120 |

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by oruebel** [comment]
Most of these have been fixed. The main that remain are in ``src/pynwb/__init__.py`` and are to pull main classes from the different modules to the main module.
