### ISSUE TITLE
request: microphone data type

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#282]
I'm trying to import the Chang lab data into NWB, and I can't find any audio data types.  It would be useful to have this type as it would help distinguish between auditory stimuli presented with a speaker, microphone behavioral recording, and other analog recordings such as button presses.

I can of course use the generic type `pynwb.behavior.BehavioralTimeSeries` or extend it to create my own type, and this is what I plan to do for now, but I wanted to see if the group thought specific microphone (and speaker) data type would be worthwhile to add to the standard NWB data types. It could be added to the Behavior module, which IMHO already contains more specialized data types than this. It could also contain optional fields that describe the microphone type, model, position, etc.

**Comment by neuromusic** [comment]
Hi Ben,

I don't know what the formal process is for adding to the schema, but there are a number of proposed changes at the nwb-schema repo:
https://github.com/NeurodataWithoutBorders/nwb-schema/issues

For example see the conversation about running speed here:
https://github.com/NeurodataWithoutBorders/nwb-schema/issues/97

For now, I think that creating your own extension & proposing a change on the nwb-schema issues makes the most sense.

**Comment by bendichter** [comment]
got it, thanks!
