### ISSUE TITLE
Builder instead of link for read-then-write use case

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#283]
Feature Request

Currently Brain Observatory files can be read by using a legacy type map, and written back out as 2.0 compliant files by creating a second NWBHDF5IO object.  However, the file that is generated a collection of external links, and doesn't move the data over.  Implementing a copy option would allow the use of this read/write functionality as a 1.x to 2.0 migration too.

Code snippet to start:
```
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
import pynwb

brain_observatory_cache_manifest_file = '~/boc/manifest.json'

ophys_experiment_id = 570014520
boc = BrainObservatoryCache(manifest_file=brain_observatory_cache_manifest_file)
exp = boc.get_ophys_experiment_data(ophys_experiment_id)
legacy_map = pynwb.legacy.get_type_map()
io2 = pynwb.NWBHDF5IO(exp.nwb_file, extensions=legacy_map, mode='r')
nwb_data = io2.read()

io2 = pynwb.NWBHDF5IO('tmp.nwb', extensions=legacy_map, mode='w')
io2.write(nwb_data) 
```

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by neuromusic** [comment]
So the code snippet you have above currently will dump a bunch of external links into `tmp.nwb`? Is that right?

**Comment by nicain** [comment]
@neuromusic Thats correct.
 In https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/form/backends/hdf5/h5tools.py :: write_dataset, execution follows:

```
 elif isinstance(data, Dataset):
    data_filename = os.path.abspath(data.file.filename)
    parent_filename = os.path.abspath(parent.file.filename)
    if data_filename != parent_filename:
        link = ExternalLink(os.path.relpath(data_filename, os.path.dirname(parent_filename)), data.name)
    else:
        link = SoftLink(data.name)
    parent[name] = link
```

isinstance(data, Dataset) is True, so links are created

**Comment by neuromusic** [comment]
that is super un-intuitive. 

my preferred behavior would be that what you did copied all of the data to the new file.

if the user wants external links to existing data, they should turn "copy" off with a flag when they create the writer. e.g.

``` Python
from allensdk.core.brain_observatory_cache import BrainObservatoryCache
import allensdk.brain_observatory.stimulus_info as si
import pynwb

brain_observatory_cache_manifest_file = '~/boc/manifest.json'

ophys_experiment_id = 570014520
boc = BrainObservatoryCache(manifest_file=brain_observatory_cache_manifest_file)
exp = boc.get_ophys_experiment_data(ophys_experiment_id)
legacy_map = pynwb.legacy.get_type_map()
reader = pynwb.NWBHDF5IO(exp.nwb_file, extensions=legacy_map, mode='r')
nwb_data = reader.read()

writer = pynwb.NWBHDF5IO(
    'tmp.nwb',
    extensions=legacy_map, 
    mode='w',
    copy=False,
)
writer.write(nwb_data) 
```

I'm open to other semantics. `link_existing_data=True` etc

**Comment by nicain** [comment]
I tried to take a shot at this this morning, but started to write every copy of the timestamps to disk, without respecting the fact that they are internal softlinks.  @ajtritt is there a clever/simple way to avoid doing this?

**Comment by oruebel** [comment]
Essentially this is a result of the lazy load. Here a couple of options:

1) we could add a mechanism that forces all data to be loaded into memory before write, e.g., via a flag on the ``.read()``. This would be fine for small files but problematic for large files. I.e., the default should be lazy load.
2) we could add a mechanism to force copy of the data on write, e.g., via a flag on the ``.write()``. This would mean that data read operations will occur during write, but would avoid loading all at once. This is the option that @neuromusic mentioned.
3) we could wrap the h5py datasets in an abstract array container to control on a per-dataset basis whether external links should be created or not. 

1), 2) are global options, whereas 3) would provide users fine-grained control of what is written how. 

@ajtritt  what are your thoughts on the best way to address this issue?

**Comment by neuromusic** [comment]
I suspect that this isn't the only place that the hard association between the NWBFile object that is loaded and the backend might bite a user.

I could also imagine a "copy" method on NWBFile that loads the full file into memory and breaks any existing association with the source file. This gives you a "clean" object, like you just created it from scratch & writing it anew works as expected.

**Comment by neuromusic** [comment]
jinx! thanks @oruebel 

now that I read your comment, a general purpose `.copy()` could be leveraged to support both 1 & 2

**Comment by oruebel** [comment]
@neuromusic I think the ``.copy()`` method you mentioned would be variant 1. My guess is we may ultimately end up needing options for 1,2, and 3, but let's see if can't get @ncain problem solved with one of them. @ncain, just to clarify, if I understand your comment correctly, ``...write every copy of the timestamps to disk, without respecting the fact that they are internal softlinks...`` then you actually want to preserve some links but break others? I'd suggest we have a one-on-one chat with @ajtritt to see what the best option will be to address your problem.

**Comment by nicain** [comment]
Thanks all, ill try and summarize:

Issue to be dealt with is that writing-after-reading has no options other than creating external links to the original data.  I would like to have the option (which could potentially be the default option) of copying data from the source, breaking the dependence on keeping the old file.  This would allow a read/write to act as an adapter that could update a file from 1.x to 2.0 (or other variants, if the user provides a different TypeMap).

The issue I ran into with a naive implementation of this is that I ended up copying way more data than the original file, because I didn't respect the fact that the source had internal softlinks.  So my new file had many copies of some aspects of the data; no bueno.

The suggestion is an option to copy-on read with default off (1), or copy-on-write with default either on or off (2).  I favor copy-on-write, default on.

**Comment by neuromusic** [comment]
> copy-on-write, default on

+1

@oruebel I mean that if there is a general purpose `.copy()` it could be called within `.write()` or `.read()` or anywhere else it is needed.

e.g. in https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/form/backends/io.py#L35

``` Python
    @docval({'name': 'container', 'type': Container, 'doc': 'the Container object to write'},
            {'name': 'copy', 'type': bool, 'doc': 'copy the data before writing','default':True})
)
    def write(self, **kwargs):
        container = getargs('container', kwargs)
        if getargs('copy', kwargs)==True:
            container = container.copy()
        f_builder = self.__manager.build(container, source=self.__source)
        self.write_builder(f_builder)
```

or wherever else it would be best to apply such a method.

**Comment by nicain** [comment]
@neuromusic this could be tricky; I think we would want to copy the data associated with the container, but perhaps not loose the association of the container with its parent; if it loses this association, it will be really difficult to not duplicate data on write.

**Comment by oruebel** [comment]
Another complication is that a ``.copy()`` on the container would load all data into memory at once. This is fine if a users calls the method explicitly (because they'll know what is going on), but we should avoid doing it in the background in the I/O backend. Here we should ideally only load the data incrementally as arrays are being written to avoid running out of memory when dealing with large files.

**Comment by neuromusic** [comment]
all fair points.

"copy-on-write, default on" <- this is the important piece, however you want to implement it. I could see broad utility in a `.copy()` method, but that's not critical at this point.

**Comment by JFPerkins** [comment]
@nicain I don't think your round trip example was writing way more data than was in the original file. I was playing around with trying to convert a brain observatory nwb to 2.0, and noticed that all of the timestamps in the Allen nwbs are unique datasets; they aren't soft or hardlinks despite the data in many of them being identical. What I did notice is that the naive implementation of copy-on-write writes without compression, while the Allen nwbs are all gzip compressed. When I hacked in compression the converted file was actually smaller than the original (it also seems to be missing running speed).

**Comment by oruebel** [comment]
@nicain https://github.com/NeurodataWithoutBorders/pynwb/pull/400 added the ``link_data`` flag to define the default behavior for how HDF5 datasets are treated on write, i.e., whether they should be linked to or copied. I.e., if you set ``link_data=False`` when calling ``HDF5IO.write()`` then the data should now be copied on write.

https://github.com/NeurodataWithoutBorders/pynwb/pull/400 also expanded the ``H5DataIO`` class in ``/pynwb/form/backends/hdf5/h5_utils.py`` so that you can wrap individual H5Dataset objects and control on a per-dataset basis whether it should be linked to or copied on write. 

Give it a try, but I believe this should address this issue. Feel free to reopen the issue in case #400 did not fix it.
