### ISSUE TITLE
Error when creating extensions with 'str' datatype

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#289]
The following code: 

```python
from pynwb.spec import NWBGroupSpec, NWBAttributeSpec, NWBLinkSpec, NWBNamespaceBuilder
from pynwb import get_class, load_namespaces
import os
import warnings


ext_path = '/home/loren/Src/NWB/franklabnwb/fl_extensions'
ns_name = 'franklab'
ns_path = '%s/%s.namespace.yaml' % (ext_path, ns_name)
ext_source = "%s.extensions.yaml" % ns_name

ns_builder = NWBNamespaceBuilder('Extensions for use in the the Frank Laboratory', 'franklab')
FL_ClusterQuality_ext = NWBGroupSpec('Frank Lab Cluster Quality Class',
                                                                     attributes=[NWBAttributeSpec('name',
                                                                                                                          'cluster id',
                                                                                                                           'str',
                                                                                                                            required=True),
												 NWBAttributeSpec('isolation_distance',
																  'mountainsort isolation distance metic',
																  'float',
																  required=False),
												 NWBAttributeSpec('noise_overlap',
																  'mountainsort noise overlap metric',
																  'float',
																  required=False)],
									 neurodata_type_def='FL_ClusterQuality',
									 neurodata_type_inc='NWBContainer')


# add the class to the namespace builder
ns_builder.add_spec(ext_source, FL_ClusterQuality_ext)
# create a builder for the namespace
ns_builder.export(ns_path)



# test
load_namespaces(ns_path)

FL_ClusterQuality = get_class('FL_ClusterQuality', ns_name)
help(FL_ClusterQuality)

```

Produces 

> Help on class FL_ClusterQuality in module abc:
> 
> class FL_ClusterQuality(pynwb.core.NWBContainer)
>  |  The base class to any NWB types.
>  |  
>  |  The purpose of this class is to provide a mechanism for representing hierarchical
>  |  relationships in neurodata.
>  |  
>  |  Method resolution order:
>  |      FL_ClusterQuality
>  |      pynwb.core.NWBContainer
>  |      pynwb.core.NWBBaseType
>  |      pynwb.form.container.Container
>  |      builtins.object
>  |  
>  |  Methods defined here:
>  |  
>  |  __init__(*args, **kwargs)
>  |      __init__(source, name, parent=None, container_source=None, isolation_distance=None, noise_overlap=None)
>  |      
>  |      
>  |      
>  |      Args:
>  |          source (str): a description of where this NWBContainer came from
>  |          name (None): cluster id
>  |          parent (NWBContainer): the parent Container for this Container
>  |          container_source (object): the source of this Container e.g. file name
>  |          isolation_distance (float): mountainsort isolation distance metic
>  |          noise_overlap (float): mountainsort noise overlap metric

Note the (None) datatype for name.  As a result, attempting to save an NWBFile with this object in it fails. 

I think this means that the 'str' datatype isn't properly assigned when the extension is created.

**Comment by oruebel** [comment]
@lfrank it looks like the type gets written correctly on export but it seems that something is going wrong on import. Changing `str` to `text` works for me. Using `text` also has the advantage that it uses UTF instead of ASCII strings. 

That being said, it looks like both `str` and `ascii` dtype do not show up after loading. @ajtritt I only took a quick look but I suspect the fix is that we simply need to update ``pynwb.form.build.map.TypeMap._type_map`` to include corresponding types for ``str`` and ``ascii``. My guess is that we are missing a few more and/or we need to update the docs of the specification language:

http://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype

Also, does ``pynwb.form.validate.validator.__valid_dtypes `` need to be updated as well?
