### ISSUE TITLE
Errors in documentation for extensions 

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#290]
As far as I can tell, the documentation for the extensions is still incorrect. An an example,

`spec = NWBAttributeSpec('bar', 'float', 'a value for bar')`

should be 

`spec = NWBAttributeSpec('bar', 'a value for bar', 'float')`

As otherwise the description and dtype variables are backwards.

I'm not sure which other parts of the documentation are problematic, but a single pass through should be enough to find the errors and fix them, I think...

**Comment by neuromusic** [comment]
should this have been fixed in #262? or is a similar approach needed for the extension docs?
