### ISSUE TITLE
Cannot import name NWBNamespaceBuilder

### ISSUE THREAD

**Issue by hluetck** [NeurodataWithoutBorders/pynwb#293]
Hello,
I am following the tutorial at http://pynwb.readthedocs.io/en/stable/tutorials.html. I installed pynwb with pip (`pip install -U pynwb`) in a Conda virtual env. When running the following from the tutotorial:
`from pynwb import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec`

I receive an import error:
ImportError                               Traceback (most recent call last)
<ipython-input-2-dffbf0507e8b> in <module>()
----> 1 from pynwb import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec

ImportError: cannot import name NWBNamespaceBuilder

Thanks for some hints how to address this.

Best regards, Henry

### Steps to Reproduce
```
import pynwb
from pynwb import NWBNamespaceBuilder
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 2.7
- **Operating System:** macOS
- **Pynwb Version:** I tried with the stable version installed by pip and the latest pre-release

**Comment by oruebel** [comment]
@hluetck you should be able to simply do:

``from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec``

i.e., import the classes directly from the ``pynwb.spec`` module where they are defined. 

 @dorukozturk @ajtritt  it looks like in https://github.com/NeurodataWithoutBorders/pynwb/commit/436c444471650d812102dcbe71e1042f094b8fed NWBNamespaceBuilder was removed as import in the pynwb/__init__.py which broke the tutorial. Should NWBNamespaceBuilder (and NWBAttributeSpec and NWBLinkSpec) be added back to the top-level init or should the examples in the docs be updated to fix this issue?

**Comment by hluetck** [comment]
@oruebel  this works. thanks!

**Comment by dorukozturk** [comment]
@oruebel I think updating the docs is better for the sake of explicity. pep8 recommends explicit imports instead of implicit ones (unless there are namespace restrictions).
