### ISSUE TITLE
Where should pynwb validate schema relationships?

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#306]
I'm currently working on getting a bunch of calcium imaging data into pynwb. I've got additional behavior data streams and stimulus streams, but currently, I'm just trying to build out a minimal file with calcium traces.

My short term problem is that I have no clean way to check whether I'm writing files correctly.

But I feel like this problem highlights broader issues with when and where pynwb enforces the schema & I'm hoping this issue can open a discussion about how we might be able to improve pynwb for users.

To start, pynwb won't let me mock up a single object without having it's dependencies specified. Practically speaking, this means I have to build out a script to write data backwards... I want to save calcium traces, but I can't create the RoiResponseSeries until I've created an ImageSegmentation, so I try to make a ImageSegmentation, but pynwb won't let me until I've created a PlaneSegmentation, etc, etc, etc.

now I've got dozens of objects in memory (6+n, where 'n' is the number of neurons in my recording) and I want to save them which means I need to register them with the NWBFile container.

This happens by creating a module and running "add_container" over and over again.

``` Python
# now let's create the processing module to store this in
ophys_module = nwb_file.create_processing_module(
    name="ophys",
    description="calcium responses",
    source="my rig",
)

ophys_module.add_container(dFF_wrapper)
ophys_module.add_container(dFF_series)
ophys_module.add_container(seg_interface)
ophys_module.add_container(segmentation)
ophys_module.add_container(imaging_plane)
for roi in roi_list:
    ophys_module.add_container(roi)
ophys_module.add_container(max_proj)
ophys_module.add_container(optical_channel)
```

Note: at this point, pynwb does absolutely zero validation or inspection of the chain of dependencies. This means that if I have a bug and lose track of the set of required objects and they don't get passed into the `add_container` method on the processing module object, **pynwb lets me save an invalid file**

https://github.com/NeurodataWithoutBorders/pynwb/issues/146

It should be impossible to save an invalid file. I need to be able to trust that every file I save with pynwb is valid and can be read back out.

And while this is true, I have no quick way to check whether or not this is true because "validate.py" is broken:

https://github.com/NeurodataWithoutBorders/pynwb/issues/127

While fixing these bugs will go a long way toward giving users some peace of mind that they will be able to read their data back out, 

## Where should pynwb validate the data model? 

- If on object creation (as it is now), can pynwb take advantage of this when registering objects with a module by inspecting the relationships, traversing the tree, and adding all of the relevant objects instead of making the user call `add_container` over and over?
- Alternatively, if we want pynwb to do another round of validation when objects get registered with NWBFile, can pynwb be a bit lighter on validation when creating objects? For example, letting the user build the objects they need without specifying the relationships, then register them with one another later & validate against the schema when they get added to the NWBFile?

**Comment by ajtritt** [comment]
@neuromusic Can you be more specific wrt the "chain of dependencies" you refer to? 

It might help to give a little background on the architecture of PyNWB objects. Every PyNWB object is an instance of an [NWBBaseType](http://pynwb.readthedocs.io/en/latest/pynwb.core.html#pynwb.core.NWBBaseType), which has the attribute `parent`. This attribute, which can only be set once i.e. you can't move around Containers, is responsible for maintaining the hierarchical relationship of NWB data. This attribute is leveraged to ensure all data dependencies are written according to the specification. So, if a container has no parent, writing will break. (If you are not having this experience, please create an issue specific to this.) 

I have gone back and forth on how strict to be when enforcing specification compliance during write, and in the end, I have decided that pynwb should allow writing invalid files. I want to avoid situations where data that takes significant resources to generate cannot be written because it doesn't meet the specification. This situation would occur as NWB becomes more than an exchange format and analysis tools are writing directly to NWB, which is part of our long-term vision.

**Comment by neuromusic** [comment]
"I have decided that pynwb should allow writing invalid files."

I wholly disagree on this decision.

I wouldn't use Excel if I didn't have confidence that a spreadsheet I saved could be loaded back up in Excel. This is one of the most fundamental things that a package designed to write files according to a standard should do: write files according to the standard.

**Comment by neuromusic** [comment]
re the "chain of dependencies"...

- `DfoverF` depends on `RoiResponseSeries`
- `RoiResposneSeries` depends on `ImageSegmentation`
- `ImageSegementation` depends on `PlaneSegmentation`
- `PlaneSegmentation` depends on 
  - a list of `ROI`s 
  - an `ImagingPlane`
  - an `ImageSeries`
- each ROI requires an `ImageSeries`
- an `ImagingPlane` requires an `OpticalChannel`

**Comment by neuromusic** [comment]
> So, if a container has no parent, writing will break. (If you are not having this experience, please create an issue specific to this.)

This is exactly the issue I'm having. It does not break. See #146

**Comment by neuromusic** [comment]
Note that the "chain of dependencies" also means that we cannot actually perform "true" unit tests on any objects that have other objects as required attributes, since they can't be created until the "upstream" object is created, and it can't be created until it's upstream object is created, etc, etc.

For example, the current unit test for DfOverF creates the following just to test the DfOverF class

- 1 `RoiResponseSeries`
- 1 `ImageSegmentation`
- 1 `PlaneSegmentation`
- 2 `ROI`s 
- 1 `ImagingPlane`
- 1 `ImageSeries`
- 1 `OpticalChannel`

An error in any of these classes will cause the "unit test" for DfOverF to fail.

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/tests/unit/pynwb_tests/test_ophys.py#L81

This is a side effect of pushing schema validation (via docval) to object creation.

**Comment by ajtritt** [comment]
@neuromusic Thanks for the information. 

Assuming #146 were addressed, can you suggest some modifications that would satisfy your requirements for making the ophys stuff easier to use? The structure of the ophys classes is a naive translation of how things were structured in NWB 1.x. As someone that has a better understanding of optophysiology data workflows, I would appreciate your input on this.

**Comment by nicain** [comment]
CC @mtv2101; Matt is another opto scientist (and he graciously shares his cubicle with me at AIBS)

**Comment by neuromusic** [comment]
I'd be happy to. I've expressed my grievances with this aspect of the schema here https://github.com/NeurodataWithoutBorders/nwb-schema/issues/61, but I think there are ways pynwb can alleviate the pain for users.

A key feature that will make the "chain of dependencies" easier is to allow users to create individual objects in memory before their "upstream" objects have been created. 

Specifically: 
- I want to be able to create an RoiResponseSeries object, then add the ImageSegmentation object to it.
- I want to be able to edit the attributes of my in-memory RoiResponseSeries object before saving it. See #148
- If I try to save the RoiResponseSeries object (or do something else that needs valid NWB) before adding the ImageSegmentation, I should get a friendly error.

There is good precedence for this pattern for ORMs like SQLalchemy, where you aren't required to specify foreign key relationships on object creation, but they must be specified before getting committed to the database.

**Comment by ajtritt** [comment]
@neuromusic What do you think about creating an extension of [ProcessingModule](http://pynwb.readthedocs.io/en/latest/pynwb.base.html#pynwb.base.ProcessingModule) that handles the dependency issues?  Something like CaImagingModule, with setters that represent the workflow better and take care of the dependency structure.

We can make the required arguments in the relevant constructors optional if it makes this easier.

**Comment by bendichter** [comment]
I have a similar issue for ephys. What if we have placeholder objects used for mocking up and testing?

We could have a `MockImageSeries`, and a `MockPlaneSegmentation` that depends on it, and a `MockImageSegementation` that depends on that, etc. These mock objects could just inherit from their non-mock forms and have placeholder values
