### ISSUE TITLE
add check for existing file

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#31]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

form.backend.FORMIO should check for an existing file before writing

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/31

**Comment by oruebel** [comment]
Closing as this is an old issue and the backend does support this by now.
