### ISSUE TITLE
enhanced repr

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#312]
### Problem/Use Case
Constructing NWBFiles in interactive environments like Jupyter would be facilitated by a more comprehensive __repr__ which displays the values of the attributes saved in the file

for example, printing an xarray DataArray or Dataset displays important information about the dimensions and metadata associated with the data object 

```
In [5]: data = xr.DataArray(np.random.randn(2, 3), coords={'x': ['a', 'b']}, dims=('x', 'y'))
In [6]: data
Out[6]: 
<xarray.DataArray (x: 2, y: 3)>
array([[-1.294524,  0.413738,  0.276662],
       [-0.472035, -0.01396 , -0.362543]])
Coordinates:
  * x        (x) <U1 'a' 'b'
Dimensions without coordinates: y
```

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
@neuromusic Good idea. Can you take a stab at this?
