### ISSUE TITLE
reader for NWB files?

### ISSUE THREAD

**Issue by mschachter** [NeurodataWithoutBorders/pynwb#318]
I feel like an idiot for asking this question - but how does one read an .nwb file with pynwb? I've spent like a week getting my .nwb files written, and now I have no idea what to do.

I tried this code, which fails:

io = pynwb.NWBHDF5IO('/some/path.nwb')
something = io.read()

this is the error:

Exception: Could not construct SpikeEventSeries object
    incorrect type for 'electrodes' (got 'str', expected 'ElectrodeTableRegion'): SpikeEventSeries (Chan1 Code0)

**Comment by ajtritt** [comment]
How was the file written? NWB has undergone some significant changes. If you didn’t write your NWB file with PyNWB, you will have to use legacy read functionality, which is not yet documented or completed. Depending on what’s in your files though, it might work in the current state

**Comment by nicain** [comment]
@mschachter How hard would it be for you to try and reproduce the exception (both the file-construction code, and the read code) you are seeing with a minimal piece of code (so not your full data writing script, just the smallest possible version that still illustrates the exception)?  This would help us figure out exactly what might be going wrong.

**Comment by mschachter** [comment]
Thank you both @ajtritt and @nicain for your prompt responses!

Unfortunately I can't narrow it down, but I can share the actual data file that is causing the issue. It's around 900MB, I created it using pynwb:

https://drive.google.com/open?id=1W0w-7VtHWXv9LEIlYw7meInxvF2sYpv0

Note that I did have to modify the source code in order to create this file, as described in issue #317 .

**Comment by neuromusic** [comment]
@mschachter can you provide a script for reproducing this error? it seems likely that the changes you introduced might be the culprit here.

**Comment by mschachter** [comment]
Um I'll continue working on this if somebody would please tell me what is the standard way of reading an .nwb file that has been written with pynwb? The file has epochs, electrode table regions, spike event series and electrical series objects in it. Am I missing something obvious in the documentation? I've spent alot of time trying to convert a lab's data to .nwb and am getting frustrated! Happy to follow up and dig deeper but I need some help.

**Comment by nicain** [comment]
Borrowing from https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/notebooks/read-Allen-Brain-Oservatory.ipynb, try something like:

```
import pynwb
io = pynwb.NWBHDF5IO("nwb_file.nwb", mode='r')
nwb_data = io.read()
```

EDIT: Oh, thats what you tried.  Sorry, I forgot; this is the standard way. 

> Note that I did have to modify the source code in order to create this file

 Was your file (that you are trying to read with pynwb) written with the version of the API that you changed, or unmodified?

**Comment by ajtritt** [comment]
@mschachter As @nicain has said, the two lines you shared look correct, but without being able to see what else your code is doing, and without knowing the state of the API (since you hacked it to get write to work), we can't offer you much help. 

I was able to get the example you provided in #317 working. I suspect this issue is caused either the problems causing #317, or by the modifications you made to get your files to write. Regardless, I have fixed the underlying problem and shared a Gist in PR #325. The code I shared writes exactly what you provided in #317 and reads it back in.

Please discard your changes, update from the dev branch.

**Comment by mschachter** [comment]
Thank you @ajtritt , the code changes on the dev branch have fixed both my reading and writing problems! Thanks also to @nicain as well, your quick responses are much appreciated.
