### ISSUE TITLE
Compression broken

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#340]
Looking through the issues/PRs I found out how to do it (#319), but there's nothing in the documentation about it

**Comment by bendichter** [comment]
It's also not very user-friendly. If I have this right, if I want to compress an `LFP` I have to 
1) get my `data`
2) wrap it in `iodata = H5DataIO(data, compress=True)`
3) wrap that in `ts = TimeSeries(..., iodata)`
4) wrap that in `LFP(..., ts)`

I'd much rather have `compress` as an optional argument of `TimeSeries` and have `LFP` inherit from `TimeSeries` so you could just do `LFP(..., data, compress=True)`. This would compress both the timestamps and the data of the `TimeSeries` object. We could keep around the `H5DataIO` interface in case a user wants to compress one and not the other.

**Comment by neuromusic** [comment]
note: developing this documentation is currently a proposed project for the April 3 hackathon:

## Tutorial Development: Data I/O

1. Writing large data iteratively
1. Writing data with compression
1. Create a new data store backend for FORM/NWB
1. Converting data from one store to another (There and back again)

https://github.com/orgs/NeurodataWithoutBorders/teams/hck04/discussions

**Comment by bendichter** [comment]
@neuromusic ah ok that's great, thanks

**Comment by neuromusic** [comment]
I don't know if anyone has taken the ownership of that project though... might want to leave this open until it happens :D

**Comment by bendichter** [comment]
@neuromusic 

actually, we have bigger issues. Compression doesn't even work.
```python
from pynwb.form.backends.hdf5 import H5DataIO
from pynwb.form.data_utils import DataIO
from pynwb import NWBFile
from pynwb import TimeSeries

data = [0,1,2,3,4]
timestamps = [0.1, 0.2, 0.3, 0.4]
TimeSeries('test', 'example use', H5DataIO(data, compress=True), 
           timestamps=H5DataIO(timestamps, compress=True), unit=' ')
```

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-32d1703d2c1c> in <module>()
      7 timestamps = [0.1, 0.2, 0.3, 0.4]
      8 TimeSeries('test', 'example use', H5DataIO(data, compress=True), 
----> 9            timestamps=H5DataIO(timestamps, compress=True), unit=' ')

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    344                     msg = ', '.join(parse_err)
    345                     raise_from(TypeError(msg), None)
--> 346                 return func(self, **parsed['args'])
    347         else:
    348             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/base.py in __init__(self, **kwargs)
    142             self.fields['num_samples'] = -1
    143         elif isinstance(data, DataIO):
--> 144             this_data = data.getdata()
    145             self.fields['num_samples'] = len(this_data)
    146         else:

AttributeError: 'H5DataIO' object has no attribute 'getdata'
```

I think it should be `this_data = data.data` on line 144 of `~/dev/pynwb/src/pynwb/base.py`
