### ISSUE TITLE
naming channels

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#364]
## Feature Request
I have 64 channels of LFP and I'd like to assign a unique name to each channel. One way I could accomplish this might be to use the dimensional scales that are already part of hdf5. Is there support for using dimensional scales within NWB?

Alternatively, could I enter in one 64-channel electrical_series object and then define LFP objects for each channel using referencing within HDF5? What would this look like?

**Comment by ajtritt** [comment]
@bendichter we do not provide a way to use HDF5 dimension scales. 

Can you explain what you're trying to accomplish? ElectricalSeries.electrode provides a way of labelling the second dimension (i.e. channel dimension) of ElectricalSeries.data.

**Comment by bendichter** [comment]
Yeah, that works, thanks.
