### ISSUE TITLE
add functionality for analyzing data streams

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#38]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

Within the specification, there are fields that can be determined from other datasets that might be written from a DataChunkIterator. For example, the field <TimeSeries>.num_samples can be determined from <TimeSeries>.data. If data is passed in as a DataChunkIterator, num_samples can only be determined when the DataChunkIterator is exhausted. 

We need a class that can analyze a DataChunkIterator while it is being read from. Once the DataChunkIterator is closed, this class should be able to call back to some other object for further processing (e.g. setting a variable), or provide a way for its result to be read.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/38

**Comment by rly** [comment]
Closing because not a priority requested by users, though @CodyCBakerPhD et al are working on improved progress bars around DataChunkIterator.
