### ISSUE TITLE
`nwbfile.create_ogen_site` device argument expects string

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#380]
the `device` argument of `nwbfile.create_ogen_site` takes a string that is the name of the device. I think it should also take the device object. This will make usage more consistent with `nwbfile.create_electrode_group` and `nwbfile.add_electrode` (with `electrode_group`) where the object is given, not the name of the object. Is there a reason the name of the device is used here?

**Comment by ajtritt** [comment]
Good catch. Would you mind taking a stab at this?

**Comment by bendichter** [comment]
Sure

**Comment by bendichter** [comment]
@ajtritt `Device` is currently in `ecephys`. I can import it from there, but it seems like if we are going to use `Device` to represent both ephys and ophys, it might make sense to move it out of `ecephys`.
