### ISSUE TITLE
fix miniconda builds

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#385]
## 1) Bug

Some miniconda builds have broken, miniconda27 and miniconda36. 

https://circleci.com/gh/NeurodataWithoutBorders/pynwb/2044?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/NeurodataWithoutBorders/pynwb/2040?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

All other tests pass. See #382 for details.

**Comment by dorukozturk** [comment]
@ajtritt I am investigating.
