### ISSUE TITLE
Create Generic NWBContainer class

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#39]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

We need a generic NWBContainer class that users can use to read and write extensions without defining a new NWBContainer subclass. 

We might need a generic TimeSeries class and a generic Interface class.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/39

**Comment by oruebel** [comment]
This issue has been resolved by the addition of support to dynamically create classes for extensions.
