### ISSUE TITLE
request: enumerated types

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#390]
## Feature Request
I would like to store categorical data like cell type. It seems to be like the most natural way to store this in hdf5 would be enumerated data types. Oddly, enumerated data types are not supported in numpy, but are supported in hdf5. I'd like the ability to define an extension that expects an enumerated data type.

**Comment by oruebel** [comment]
Is this addressed by the ``EnumData`` type in HDMF? https://github.com/hdmf-dev/hdmf/blob/ae1c99bbd220bcb6bdaad0bfcb6273db53cc6458/src/hdmf/common/table.py#L1341-L1342
