### ISSUE TITLE
Implement IndexSeries

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#4]
Originally reported by: **dcamp_lbl (Bitbucket: [dcamp_lbl](https://bitbucket.org/dcamp_lbl), GitHub: Unknown)**

----------------------------------------

Create the base ImageSeries class

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/4

**Comment by ajtritt** [comment]
*Original comment by* **dcamp_lbl (Bitbucket: [dcamp_lbl](https://bitbucket.org/dcamp_lbl), GitHub: Unknown)**:

----------------------------------------

IndexSeries basic class is done and basic test case.

Need save and load functions.

**Comment by oruebel** [comment]
Save and load should be handled by default mapping.
