### ISSUE TITLE
ImagingPlane device argument should be link to device, not str

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#412]
https://github.com/NeurodataWithoutBorders/pynwb/blob/ddeaacc464e567f3fc123ca74a6d8cecbfbbce15/src/pynwb/ophys.py#L59

Correct me if I'm wrong, but I think for consistency with ephys, the device argument of ImagingPlane should expect a Device type, not a str.

**Comment by ajtritt** [comment]
This was missed during conversion from 1.x, but it should be a Device, not a string

**Comment by t-b** [comment]
Same issue applies to the `device` in intracellular ephys electrodes. This is still a string and should also be a device.

**Comment by t-b** [comment]
@bendichter Have you already started working on that? If not I'd volunteer to handle it.

**Comment by t-b** [comment]
create_ic_electrode should then also accept a Device object.

**Comment by bendichter** [comment]
I have not, please go ahead

**Comment by bendichter** [comment]
@t-b I've been slow to fix these types of issues that cause schema changes because I'm not sure the best practice for breaking schema backwards compatibility. I'm dealing with this on another issue and I'm curious what your thoughts are. This change will break `read` for all previously saved ophys and icephys datasets. Do you think there should be a special way we announce this change? Should we keep some sort of legacy `read`? Any other special considerations for these types of changes?

**Comment by bendichter** [comment]
Changes will need to be made to:

* schema yaml files
* container classes
* unit and integration tests
* test nwb files that are read during tests

**Comment by t-b** [comment]
@bendichter 

Thanks for getting back so quickly.

> Do you think there should be a special way we announce this change?

Yes we should mention that in the release notes of the schema and pynwb.

> Should we keep some sort of legacy read? Any other special considerations for these types of changes?

As we are still in the beta phase, from what I understand, we can break the compatibility any time.  So I would not add any support for reading the existing files. Would be nice to get more opinions, or even definite answers, here though.
