### ISSUE TITLE
ability to prototype sphinx-gallery examples

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#414]
### Problem/Use Case
Prototype sphinx-gallery examples quickly, without having to build out the entire documentation to make a change.

**Comment by nicain** [comment]
@oruebel This issue is to help track the integration of that executable I told you about.  Ill make a feature branch based on this issue so you can see my WIP.

**Comment by ajtritt** [comment]
@nicain can you provide some more details on this? 

Adding a gallery example requires adding a sphinx-gallery formatted Python script that to anywhere in docs/gallery, and then running `make htmldoc` to build the documentation.  If it's in there, the test suite will pick it up and execute it.

**Comment by nicain** [comment]
Closed in favor in of https://github.com/NeurodataWithoutBorders/nwb-docutils/issues/1
