### ISSUE TITLE
add_roi requires redundant information

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#418]
after the ROI refactor in #391 ....

`plane_segmentation.add_roi` requires BOTH an img_mask and a pix_mask to define an ROI

these are two different ways of representing the same data & both should not be required.

if I were to be bold, I would suggest dropping the pix_mask entirely, but this is a legitimate way of representing this data that some people prefer.

**Comment by bendichter** [comment]
links to https://github.com/NeurodataWithoutBorders/nwb-schema/issues/60

**Comment by bendichter** [comment]
You can now specify either img_mask or pix_mask
