### ISSUE TITLE
ImageSeries should not require timestamps

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#422]
this has come up before (e.g. #124) but image.ImageSeries should have timestamps as an optional attribute

in #124 @oruebel argued that ImageSeries does not need to support this, but this is clearly not the case from the documentation, e.g. for image.IndexSeries...

> Stores indices to image frames stored in an ImageSeries. The purpose of the ImageIndexSeries is to allow a static image stack to be stored somewhere, and the images in the stack to be referenced out-of-order. **This can be for the display of individual images**, or of movie segments (as a movie is simply a series of images). The data field stores the index of the frame in the referenced ImageSeries, and the timestamps array indicates when that image was displayed.

http://pynwb.readthedocs.io/en/latest/pynwb.image.html#pynwb.image.IndexSeries

The specific use-case here is that we have multiple static images that are presented as a visual stimulus in an experiment. We need to store these images (which are NOT a TimeSeries and therefore do not have timestamps or a start_time), then maintain a timeseries of which image was presented (referenced by the IndexSeries)

cc @bendichter

**Comment by ajtritt** [comment]
I think we should create a new type, or modify IndexSeries to replace ImageSeries. ImageSeries is supposed to be a TimeSeries. If it has no field for time, then, to me, it doesn’t seem like this is really a time series. 

I believe there is a type called “Images” that’s pretty barebones. I put it there as a placeholder for future development of image-related things. We could just add everything but time-related fields from ImageSeries to Images. IndexSeries could then point to an Images type

**Comment by neuromusic** [comment]
ImageSeries makes sense as a timeseries (e.g. we collect behavioral videos or present movies as stimuli).

Maybe the concern here is what IndexSeries should reference your new Images type.

e.g. the `indexed_timeseries` kwarg should become `indexed_image_stack` or something of the sort?

**Comment by neuromusic** [comment]
ok, with more discussion with others here, this is a core need....

- there should be an Image type that allows storing arbitrary n-dimensional images
- ImageIndexSeries should index into this type

**Comment by bendichter** [comment]
We now have `GrayscaleImage`, `RGBImage`, and `RGBAImage`, which are all a subclass of `Image` and meant for storing static images.

**Comment by bendichter** [comment]
It looks like I should not have closed this, because the solution really did not address the underlying problem, which has reappeared in new datasets. `Images` now is a collection, which allows it to contain individual image objects of different forms. It's essentially just a bag of images with no constraint about the forms of those images being the same. You can even put grayscale images next to RGB ones. I think there is value in having that, but it does not address this problem, where we need a stack of images we can index into. My suggestion would be for now to continue to use `ImageSeries`, but set `ts.rate` and `ts.starting_time` to `NaN`.

**Comment by stephprince** [comment]
This should be addressed with the `order_of_images` field being added to Images: https://github.com/NeurodataWithoutBorders/nwb-schema/pull/459, https://github.com/NeurodataWithoutBorders/pynwb/pull/1483
