### ISSUE TITLE
issue template: reference contributing guidline

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#425]
See https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/ISSUE_TEMPLATE.md

**Comment by davidsteuerman** [comment]
Is this the preferred fix?

https://blog.github.com/2012-09-17-contributing-guidelines/

**Comment by oruebel** [comment]
I think maybe both, i.e., have it appear as a banner as well as have the check box in the template itself in the same way we have the check box in the pull request template.
