### ISSUE TITLE
Generalize cluster quality metrics

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#427]
The [clustering container](https://pynwb.readthedocs.io/en/latest/pynwb.ecephys.html#pynwb.ecephys.Clustering) has a dataset called "peak_over_rms". This is a metric of the quality of clustered units. Such metrics will likely be produced by every extracellular ephys experiment, but will not necessarily be peak_over_rms.  The peak_over_rms field should probably be replaced by a more generic quality metric field.

I will take a stab at this if there are no objections.

**Comment by NileGraddis** [comment]
from a conversation with @ajtritt and @tjd2002:

1. we should be using Unittimes rather than Clustering
2. The plan for cluster metrics is now to create a new dataset subclass called UnitMetric. This class will have a flexible tag (e.g. peak_over_rms) and description, as well as an nunits long array of data. Extension writers can produce specializations of this class which fix the tag and description and some examples of such specializations will be made in core.

**Comment by rly** [comment]
`Clustering` has been deprecated in favor of `Units`
