### ISSUE TITLE
Ensure objects are registered when assigning them to other objects

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#43]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

The problem this ticket describes is the following. In serveral cases, NWBContainers are closely tied to the parent container E.g, SpikeUnit to UnitTimes, Device to NWBFile etc. In these cases, the API often provides dedicated methods on the main type to create these contained types, however, if the user creates the contained objects independently using the corresponding class then we need to make sure that the parent gets set correctly to ensure the objects are written correctly. For example: 

* The function NWBFile.create_device works but when creating a Device directly and setting it only on the ElectrodeGroup then the Device may not be registered with the NWBFile so that the link for device in ElectrodeGroup will be borken because the device is not written. To avoid this we need to register the Device with the NWBFile as well. 
* UnitTimes requires a list of SpikeUnit as input. However, the user needs to make sure that both the SpikeUnit are assigned to UnitTimes as well as that the parent on SpikeUnit is set correctly in order for the SpikeUnit. 

```
#!python

    spike_unit_objs = [SpikeUnit(....) for s in spike_unit_data]
    unit_times = UnitTimes(source="Data as reported in the original crcns file",
                           spike_units=spike_unit_objs)
    for i in spike_unit_objs:   # We now need to set the parent for the spike_unit_obj
        i.parent = unit_times
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/43

**Comment by oruebel** [comment]
@ajtritt should this issue be closed?
