### ISSUE TITLE
Write/use format specification data to NWB files

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#44]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

NWB files contain a currently freeform area in /general/specifications for storing specifications. To ease use of the specification data it would be useful to:

- [x] Assign a neurodata_type to /general/specifications and create a custom NWBContainer class to manage specifications
- [x] Possible create a new neurodata_type to be stored in /general/specifications to structure the storage of namespace and associated specification files rather than requiring that specs be stored in a single dataset
- [x] Automatically write all specs used by (or registered with) PyNWB to the NWB file when a file is written. This will help ensure that the spec for all objects are always stored in the file. 
- [x] Add ability to use use specifications (including custom extensions) from the HDF5 directly on read. We possibly need an option here to allow the user decide whether to use specs from the HDF5 file or the specs currently registered with PyNWB.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/44

**Comment by jcfr** [comment]
Closing. This is addressed by #242 

Please, re-open or create a more specific issue if it should not have been closed.
