### ISSUE TITLE
Make setUpBuilder optional in test case

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#441]
Having to write out the builders manually makes writing roundtrip tests more cumbersome, though it is helpful for debugging new containers. It would be nice (and make contributing easier!) if this were optional. As far as I can tell, the relevant class is tests.integration.ui_write.base.TestMapNWBContainer - specifically the setUp and test_build methods.

thoughts?

**Comment by ajtritt** [comment]
relates to #440

**Comment by bendichter** [comment]
Agreed. Thanks for bringing this up, Nile!

**Comment by ajtritt** [comment]
closed by #456
