### ISSUE TITLE
Device class used for ecephy, icephys and ophys but lives in ecephys.py

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#443]
The class `Device` is used for Intracellular Ephys and Extracellular Ephys. See https://github.com/NeurodataWithoutBorders/pynwb/blob/3afc38fce1cad67c54efa55068c01486ff15478f/src/pynwb/data/nwb.ecephys.yaml#L312 and https://github.com/NeurodataWithoutBorders/pynwb/blob/3afc38fce1cad67c54efa55068c01486ff15478f/src/pynwb/data/nwb.icephys.yaml#L194.

But it lives in https://github.com/NeurodataWithoutBorders/pynwb/blob/3afc38fce1cad67c54efa55068c01486ff15478f/src/pynwb/ecephys.py#L14.

**Comment by ajtritt** [comment]
relates to #412

**Comment by oruebel** [comment]
The accompanying schema issue is here https://github.com/NeurodataWithoutBorders/nwb-schema/issues/166
