### ISSUE TITLE
UnitTime roundtrip changes type returned by `get_unit_spike_times`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#449]
## Bug

Before IO, `UnitTimes` returns spike times as a list. After IO, spike times are returned as a numpy array. I guess either is fine. I prefer np.arrays, but it should be consistent. 

### Steps to Reproduce
```python
from pynwb.misc import UnitTimes
from base import ContainerRoundTrip

ut = UnitTimes('UnitTimes add_spike_times unit test')
ut.add_spike_times(0, [0, 1, 2])
print(type(ut.get_unit_spike_times(0)))

with ContainerRoundTrip(ut) as ut2:
    print(type(ut2.get_unit_spike_times(0)))
```

```
<class 'list'>
<class 'numpy.ndarray'>
```

(ContainerRoundTrip is in #450)
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** macOS
- **Pynwb Version:** latest dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
Growing numpy arrays takes significantly longer than growing generic Python list. PyNWB uses generic lists during write for this reason. 

h5py returns numpy arrays on read.

Is this consistency important enough to sacrifice performance and add code overhead?

**Comment by bendichter** [comment]
Look at how I solved it. I'm not storing as a numpy array, I'm storing as a list and converting to numpy array on retrieval. Does this work for you?
