### ISSUE TITLE
Managing /general/subject

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#45]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

To ease use/management of subject metadata in /general/subject we should (similar to the other groups in /general):

* assign a neurodata_type to /general/stimulus and
* create a corresponding NWBContainer class for managing /general/stimulus

This would also help keep the NWBFile interface simpler

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/45

**Comment by oruebel** [comment]
@ajtritt I think this issue is complete, but I wanted to confirm first that it can indeed be closed.
