### ISSUE TITLE
Complete Epoch.links()

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#46]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

Need to complete the implementation of Epoch.links function in pynwb.epoch.py. The function should return a list of strings of the form  “’ <TimeSeries_X> is path_to_TimeSeries ‘” (see http://nwb-schema.readthedocs.io/en/latest/format.html#epoch)

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/46

**Comment by oruebel** [comment]
Epoch.links has been removed now as part of the removal of autogen datasets and should, therefore, also be removed from the API, rather than completing the implementation of the property.
