### ISSUE TITLE
Timeseries: Using starting_time and rate parameters.

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#47]
Originally reported by: **maxdougherty (Bitbucket: [maxdougherty](https://bitbucket.org/maxdougherty), GitHub: [maxdougherty](https://github.com/maxdougherty))**

----------------------------------------

Currently a TimeSeries requires the **timestamps** parameter to be specified, even if a **start_time** and **rate** have been specified. This contradicts [the example](http://pynwb.readthedocs.io/en/latest/example.html#creating-timeseries) shown in the pyNWB docs.

----------------------------------------
-#47

**Comment by t-b** [comment]
@oruebel This is resolved according to my tests and looking at https://github.com/NeurodataWithoutBorders/pynwb/blob/67a3bca2c37c42cb963b2ea1509952567bdf35cd/src/pynwb/base.py#L173.
