### ISSUE TITLE
workflow to add `Subject` deviates from pattern

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#472]
There seem to be two alternative workflows to add data to an `NWBFile` object. The first is to construct the file with the minimum required arguments:
```python
from pynwb import NWBFile
from datetime import datetime
NWBFile(source='source', session_description='session_description',
        identifier='identifier', session_start_time=datetime.now())
```
and then add data as you build it. This is the strategy demonstrated in the tutorials. The second method is to build up the data first and then construct the `NWBFile` object later with the data as arguments. As far as I can tell, all of the data types can be put into the `NWBFile` using either method, except `Subject`, which must be added the second way: constructed beforehand and added during construction of `NWBFile`, because there is no `add_subject` or `create_subject` method in `NWBFile`. I think it's fine that we have two options, and I don't really have a preference for either workflow. You can currently add Subject using the second workflow no problem, even if the rest of the data uses the first, but if I think if the tutorials only teach the first then we should make all of the datatypes compatible with that workflow. Was this an intentional design decision?

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
```python
nwbfile = NWBFile(...)
nwbfile.subject = Subject(...)
```
