### ISSUE TITLE
Dynamic class still buggy

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#48]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

So far, this issue exists:

https://gist.github.com/nicain/8965460ebcab2075fb478839843cad9f

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/48

**Comment by bendichter** [comment]
this is expected behavior.
