### ISSUE TITLE
sphinx not linking internally

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#488]
## 1) Bug

Sphinx is not building links to types defined within PyNWB, but it can link to other types found outside of PyNWB. 

For example, on the TimeSeries API doc, the allowable types for the *data* argument don't provide links to anything defined within NWB e.g. AbstractDataChunkIterator, but it links to the h5py API docs for Dataset. 
http://pynwb.readthedocs.io/en/latest/pynwb.base.html#pynwb.base.TimeSeries

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
@ajtritt @jcfr How would one start tackling that issue?

**Comment by t-b** [comment]
The code to look at is `__builddoc` in hdm/utils.py:

https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/utils.py#L428
