### ISSUE TITLE
Migrate repos to NeurodataWithoutBorders GitHub

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#49]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

[Hackathon] All source repos should be migrated to common GitHub 

* Chris Martin will organize the GitHub team
* Kitware will help with the migration
* Need to coordinate on when to migrate once the place and names are finalized

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/49

**Comment by oruebel** [comment]
Completed base migration of PyNWB and nwb-schema repos (including issue tracker and ReadTheDocs) to GitHub. 

Contacted Kitware team for help with remaining migration issues (e.g., setup of CI etc.)
