### ISSUE TITLE
flake8 config not ignoring gallery example

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#491]
In https://github.com/NeurodataWithoutBorders/pynwb/commit/72883b017b0eb0ae4fb3e37630db09b5c2082ab5 I added a line to ignore line-too-long (i.e. E501) to the flake8 circle build.  However, it looks like this ignore is not actually working, for some reason.  I had to force-merge PR https://github.com/NeurodataWithoutBorders/pynwb/pull/490 to get my changes for my tutorial through for the hackathon, but this needs to be sorted out. @dorukozturk am I missing something obvious?

As a side note, I need this long line so that sphinx gallery can find the natural line break to use for typesetting the documentation in the html and jupyter notebooks that it creates; I could tell it where to line break, but it is better to let those platforms figure it out for themselves depending on monitor resolution, etc.  If I add noqa inline at the end of the line, it gets rendered inside the documentation as plaintext :/

**Comment by dorukozturk** [comment]
Yes, this is confusing. This is happening because the tool that checks styling (pep8speaks) is not running flake8 (even it is much better) but running pep8. That is why even if the flake8 tests are passing pep8speaks fails. If you run pep8 locally you can reproduce this error. Maybe it is time to say goodbye to pep8speaks and rely on circle running flake8. @jcfr @mgrauer @ajtritt What do you think?

**Comment by dorukozturk** [comment]
@nicain The correct syntax is https://github.com/NeurodataWithoutBorders/pynwb/blob/846c26d95ab05fe73f439e2c9c13c5d3aeeca6b0/.circleci/config.yml#L8

**Comment by jcfr** [comment]
> Maybe it is time to say goodbye to pep8speaks and rely on circle running flake8

:+1: 

Unless we contribute to pep8speaks and help address `https://github.com/OrkoHunter/pep8speaks/issues/56` , only maintaining falke8 validation seems reasonable.

**Comment by dorukozturk** [comment]
I am leaning towards removing it. :smile:
