### ISSUE TITLE
Write spec to nwb file by default (change `cache_spec` default to true)

### ISSUE THREAD

**Issue by tjd2002** [NeurodataWithoutBorders/pynwb#497]
By default we should save the spec into the nwb file. Especially helpful if an nwb file includes custom extensions.

According to #379 pynwb errors on read if cache_spec is enabled.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
@tjd2002 Sounds like a good idea. #379 is already closed, so we can just flip the bit I guess.

**Comment by rly** [comment]
Implemented by #981
