### ISSUE TITLE
how do I specify specific data_types for extensions instead of importing all of core?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#498]

**Comment by oruebel** [comment]
In the YAML itself, I think all you need to do is to add the  key``neurodata_types`` for the ``source`` or ``namespace``:

```
- source: nwb.base.yaml
- source: nwb.ephys.yaml
  neurodata_types: ElectricalSeries
- namespace: core
  neurodata_types: TimeSeries
```

I'm not sure right now how this is specified in the API. 

https://schema-language.readthedocs.io/en/latest/specification_language_description.html#schema

**Comment by bendichter** [comment]
OK. @ajtritt is this possible using the python tools?

**Comment by ajtritt** [comment]
Yes, see [NamespaceBuilder.include_type](http://pynwb.readthedocs.io/en/latest/pynwb.form.spec.write.html#pynwb.form.spec.write.NamespaceBuilder.include_type)
