### ISSUE TITLE
end-to-end tutorial

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#505]
### Problem/Use Case
Write a tutorial that explains how to:
    1. define an extension
    2. define a Container class for the extension
    3. write instances of the Container class 
    4. read the Container class(es) instances back in

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
See my pr on extensions. I think we can build off of that

**Comment by bendichter** [comment]
does https://github.com/NeurodataWithoutBorders/pynwb/pull/574 qualify?

**Comment by ajtritt** [comment]
@bendichter yes
