### ISSUE TITLE
Implementing a flexible ControlledVocabulary extension to label NWB data

### ISSUE THREAD

**Issue by neurosutras** [NeurodataWithoutBorders/pynwb#513]
During the 2018 NWB Hackathon at LBNL, the Stanford/Soltesz Lab group looked into implementing an NWB extension that would allow users to specify a ControlledVocabulary as a container of Categories (lists of allowed labels). 

https://neurodatawithoutborders.github.io/nwb_hackathons/HCK05_2018_Berkeley/projects/FilterReadByLabel/

This issue is a report of our findings and a placeholder for discussion regarding the best way to implement this.

Ideally, objects of the datatypes Category and ControlledVocabulary could be placed in the "general" module, like ElectrodeTable. However, currently there are not general methods to append arbitrary datasets or containers to the "general" module. Both datatypes should be mutable, so that users can append new labels to existing Category objects, and new Category objects to existing ControlledVocabulary objects. This appears plausibly by defining a python class that contains internal methods to append and validate input data.

Then, another new datatype, DataCategoryLabels, would be used to associate validated labels from a ControlledVocabulary with validated identifiers for data stored in a container like an IndexedVector or SpikeTimes. A DataCategoryLabels object would be instantiated with a valid pointer to an existing ControlledVocabulary, and a valid pointer to an existing data container like an IndexedVector, or SpikeTimes. The class associated with DataCategoryLabels would have methods to validate input labels and input data identifiers, so that only valid labels associated with an existing category could be assigned to data identifiers that are present in the referenced data. Presumably both the IndexedVector and the associated DataCategoryLabels would reside in "processing" or "analysis" modules, but refer to a ControlledVocabulary in "general".

**Comment by bendichter** [comment]
This is closely related to #15

**Comment by oruebel** [comment]
Closing this issue in favor of #15 . Also,  a solution for this is currently being developed in HDMF:
- https://hdmf.readthedocs.io/en/stable/tutorials/External_Resources.html#sphx-glr-tutorials-external-resources-py
