### ISSUE TITLE
trouble writing extensions with str type

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#520]
update:

```python
name = 'test_str'
ns_path = name + ".namespace.yaml"
ext_source = name + ".extensions.yaml"


test_type = NWBGroupSpec(neurodata_type_def='TestType', datasets=[
    NWBDatasetSpec(name='str_type', dtype='text', doc='genotype',
                   quantity='?')
], doc='doc')


ns_builder = NWBNamespaceBuilder(name + ' extensions', name)
ns_builder.add_spec(ext_source, test_type)
ns_builder.export(ns_path)


from pynwb import load_namespaces, get_class

load_namespaces(ns_path)
test_type = get_class('TestType', name)

test_type(name='test_name', str_type='hello')
```

error:
```python
Traceback (most recent call last):
  File "/Users/bendichter/Library/Preferences/PyCharmCE2019.1/scratches/scratch_17.py", line 24, in <module>
    test_type(name='test_name', str_type='hello')
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'str_type' (got 'str', expected 'ndarray, list, tuple, Dataset, AbstractDataChunkIterator, HDMFDataset or DataIO')

```

**Comment by bendichter** [comment]
@ajtritt

**Comment by oruebel** [comment]
@bendichter try to change ``dtype='str'`` to ``dtype='text'``. I think ``str`` was removed when we cleaned up the specification language. 

BTW, generally I would discourage using datasets to store single single strings and small fixed-size data in general. While it's perfectly Ok to it, in HDF5 Attributes are typically the better choice for this kind of small data.

**Comment by bendichter** [comment]
Thanks!

On May 28, 2018 1:57 AM, "Oliver Ruebel" <notifications@github.com> wrote:

@bendichter <https://github.com/bendichter> try to change dtype='str' to
dtype='text'. I think str was removed when cleaned up the specification
language.

BTW, generally I would discourage using datasets to store single single
strings and small fixed-size data in general. While it's perfectly Ok to
it, in HDF5 Attributes are typically the better choice for this kind of
small data.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NeurodataWithoutBorders/pynwb/issues/520#issuecomment-392389149>,
or mute the thread

**Comment by bendichter** [comment]
changing to `'text'` didn't work.

**Comment by bendichter** [comment]
neither 'str' nor 'text' work for Datasets. For Attributes, both 'str' and 'text' work, as well as any other string, since there doesn't appear to be any checking of strings (#521)

**Comment by oruebel** [comment]
`__get_type` in src/pynwb/form/build/map.py should be modified to check for scalars

**Comment by bendichter** [comment]
It appears from [the spec language docs on dtype](http://schema-language.readthedocs.io/en/latest/specification_language_description.html#dtype) that 'str' and 'text' and both acceptable

**Comment by oruebel** [comment]
@bendichter the spec language docs are out of sync with PyNWB. I'm working on updating them right now. 

The issue in your case is that the autogenerated classes don't recognize right now that``shape: null`` means scalar. To fix this ``__get_type`` in ``src/pynwb/form/build/map.py`` should be modified to check for scalars. 

You could simply use ``test_type(str_type=['hello',])`` in your example as a work-around for now until this bug is fixed.

**Comment by oruebel** [comment]
Just to update status on this. The following issues have been fixed:
* Validate dtype string when creating an Attribute/Dataset spec
* Updated specification language docs 

The following items still require attention for this issue:
* ``__get_type`` in ``src/pynwb/form/build/map.py`` should be modified to check for scalars (i.e., attributes/datasets with shape: None)
