### ISSUE TITLE
nwbfile.create_epoch timeseries arg

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#533]
If I input a list of `TimeSeries` objects as the `timeseries` arg of `nwb.create_epoch` and I look at the file with HDFView, the timeseries column says *unsupported*. Is this argument supposed to support a list of timeseries objects? An epoch rarely refers to a single timeseries. You'd use epochs to mark things like trials and experimental blocks, which apply to all of the synchronized TimeSeries objects in the file: LFP, position, spikes, etc. You might want to indicate which of these TimeSeries objects the epoch times are derived from, but that's a different question.

**Comment by ajtritt** [comment]
The `timeseries` argument to [nwb.create_epoch](http://pynwb.readthedocs.io/en/latest/pynwb.file.html#pynwb.file.NWBFile.create_epoch) can take a list of TimeSeries object. Will that work?
