### ISSUE TITLE
argument `timeseries` of EpochTable takes type RegionSlicer

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#535]
https://github.com/NeurodataWithoutBorders/pynwb/blob/337d268178d89b070a241ad296edf929ac427bad/src/pynwb/epoch.py#L16

In all other cases, `electrical_series`, `spatial_series`, and `timeseries` arguments take the type of the same name. In this case, the `timeseries` argument expects a `RegionSlicer` object, which I think is confusing.

More broadly, if I want to create epochs, the most convenient way is to use `nwbfile.create_epoch`, however this does not allow me to create multiple `EpochTable`s nor to name the `EpochTable`s. If I want to name them, I think I need to use `EpochTable()` and `EpochTable.add_row`, however this requires me to do the `TimeSeries` slicing myself. I'm not that crazy about this slicing business in the first place, because, as I have said previously, it doesn't make sense to associate epochs with a single `TimeSeries` object.  Is there a way of defining multiple named EpochTable without doing the slicing myself? If not, could we create one? Maybe call it `EpochTable.add_epoch`.

**Comment by ajtritt** [comment]
Try Epochs.add_epoch
