### ISSUE TITLE
Issues with cutting a release

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#543]
## 2) Feature Request

We should make a release in order to get the new support for trials that was introduced in #536 accessible for end users. This will hopefully also help to address https://github.com/NeurodataWithoutBorders/nwb-schema/issues/174

@jcfr can you help with cutting the release?

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
not quite yet though. There's a bug #541 I think we should fix first

**Comment by oruebel** [comment]
@jcfr @dorukozturk could you help me out and cut a release for PyNWB today? Thanks

**Comment by dorukozturk** [comment]
@oruebel We added step by step documentation on how to cut a release. It would be great if either you or @ajtritt exercises that. Keep me posted with any problems or confusion and I will clarify and help out. That way we can improve the documentation if something is confusing for a first time "releaser". Also having more developers who can cut a release is a good long term goal. We should also make sure current master is passing all the tests before we cut a release though. It seems like some tests are failing.

**Comment by bendichter** [comment]
@dorukozturk or @jcfr I'm trying to follow the direction to cut a release. Can you please add documentation for how to get an API associated with nwb-bot?

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/source/make_a_release.rst#prerequisites

**Comment by jcfr** [comment]
> how to get an API associated with nwb-bot?

I just sent you an encrypted email with the token. Note that the link to decrypt and access the message will expire in one hour.

**Comment by bendichter** [comment]
```
cd /tmp && git clone git@github.com:NeurodataWithoutBorders/pynwb && cd pynwb
```

error:
```
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jcfr** [comment]
This would work:

Git clone git://github.com/NeurodataWithoutBorders/pynwb && cd pynwb


Then.


pushURL=https://$GITHUB_TOKEN@github.com/NeurodataWithoutBorders/pynwb

git config --add remote.origin.pushURL $pushURL

**Comment by bendichter** [comment]
`mkvirtualenv: command not found`

**Comment by jcfr** [comment]
If you don't have virtualenv wrapper, you could do:

python -m venv /temp/venv
. /temp/venv/bin/activate

**Comment by bendichter** [comment]
`python -m venv /temp/venv`
error:`Error: [Errno 13] Permission denied: '/temp'`

also 

`sudo python -m venv /temp/venv` 
error:`Error: Command '['/temp/venv/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

**Comment by jcfr** [comment]
Choose a folder in your home directory then

**Comment by bendichter** [comment]
I end up with the other error:
`Error: Command '['/Users/bendichter/tmp/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

**Comment by jcfr** [comment]
Here is what I do on macOS using the default python version available on the system:

Make sure you use python 3.x

```
$ sw_vers -productVersion 
10.11.6
$ python --version 
Python 2.7.10
$ python3.6 --version
Python 3.6.4
$ python3.6 -m venv ~/pynwb-release
$ . ~/pynwb-release/bin/activate
(pynwb-release) $ pip install tox twine
Collecting tox
[...]
Collecting twine
[...]
Installing collected packages: six, virtualenv, pyparsing, packaging, py, pluggy, tox, tqdm, certifi, urllib3, chardet, idna, requests, requests-toolbelt, pkginfo, twine
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.7 packaging-17.1 pkginfo-1.4.2 pluggy-0.6.0 py-1.5.4 pyparsing-2.2.0 requests-2.19.1 requests-toolbelt-0.8.0 six-1.11.0 tox-3.1.2 tqdm-4.24.0 twine-1.11.0 urllib3-1.23 virtualenv-16.0.0
```

**Comment by bendichter** [comment]
```
bash-3.2$ sw_vers -productVersion
10.13.5
bash-3.2$ python --version
Python 3.6.3 :: Anaconda, Inc.
bash-3.2$ python3.6 --version
Python 3.6.3 :: Anaconda, Inc.
bash-3.2$ python3.6 -m venv ~/pynwb-release
Error: Command '['/Users/bendichter/pynwb-release/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Comment by bendichter** [comment]
When I want to create a virtual environment I use `conda create`. I've also used `virtualenv`, but I guess `venv` is different and doesn't come with anaconda? Would it be OK if I used `conda create` instead?

**Comment by jcfr** [comment]
> venv is different and doesn't come with anaconda?

venv comes with python3

virtualenv is available in both python 2 and python 3

Using conda, you could then do the following:

```
conda create -n pynwb-release
conda config --add channels conda-forge
conda install tox twine
```

or you could do 

```
conda install pip
```

and then 

```
pip install twine tox
```
We do something similar in the CI: https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.circleci/config.yml#L63-L72

**Comment by bendichter** [comment]
I think you missed `source activate pynwb-release`

**Comment by bendichter** [comment]
```
  py27: commands succeeded
ERROR:  py35: InterpreterNotFound: python3.5
  py36: commands succeeded
```

tests passed. New error though:

```
(pynwb-release) bash-3.2$ ls -1 dist/*
ls: dist/*: No such file or directory
```

I guess I need a py35 environment that tox can see? How do I set that up?

**Comment by jcfr** [comment]
I suggest we streamline the process and have the wheel automatically uploaded on PyPI when a tag is pushed.

This discussion demonstrate that it is hard to have the right environment working locally.

**Comment by bendichter** [comment]
that sounds fine to me

**Comment by bendichter** [comment]
but I think I'm almost there? How would I install python35? Could I just create a new conda env for it?

**Comment by jcfr** [comment]
I am not very familiar with conda, since I don't think you can install multiple python into the same conda env, you would have to create one conda env per version of python.

This is overkill here ... since we know the test pass on the CI

Assuming you:
* already **created the tag**, 
* activated a python env (e.g pynwb-release)
instead, you could simply do this:

```
cd pywnb
pip install --upgrade pip
pip install -r requirements.txt -r requirements-dev.txt
pip install wheel
pip install -e .
python ./test.py
python setup.py sdist bdist_wheel
```

then

```
$ ls -1 dist/
pynwb-0.3.0.post0.dev212-py2.py3-none-any.whl
pynwb-0.3.0.post0.dev212.tar.gz
```

-> in your case, it should probably be  (or whatever tag you chose)

```
pynwb-0.4.0-py2.py3-none-any.whl
pynwb-0.4.0.tar.gz
```

And finally (the --sign argument is optional now):

```
twine upload -r pypitest dist/*
```

**Comment by bendichter** [comment]
```
(pynwb-release) bash-3.2$ python ./test.py
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    import unittest2 as unittest
ModuleNotFoundError: No module named 'unittest2'
```

edit: resolved with `conda install unittest2`, but maybe that should be added to `requirements-dev.txt`?

**Comment by jcfr** [comment]
>  that should be added to requirements-dev.txt?

It is already there:

https://github.com/NeurodataWithoutBorders/pynwb/blob/17fc799529b14c3bad5f0e0188c37743b678bc4f/requirements-dev.txt#L19

If you following the instruction above, it should install it. I suggest you use pip and not conda to install the dependency:

```
conda install pip
```

then

```
pip install --upgrade pip
pip install -r requirements.txt -r requirements-dev.txt
pip install wheel
pip install -e .
python ./test.py
python setup.py sdist bdist_wheel
```

**Comment by bendichter** [comment]
yeah I ran those lines.. not sure why unittest2 was missed

**Comment by bendichter** [comment]
did you mean `pypitest` or `pypi`?

**Comment by jcfr** [comment]
Try pypitest first, to see how the package look. Then, if it looks good .. upload to the regular pypi

**Comment by bendichter** [comment]
HTTPError: 403 Client Error: The user 'bendichter' isn't allowed to upload to project 'pynwb'. See https://test.pypi.org/help/#project-name for more information. for url: https://test.pypi.org/legacy/

**Comment by jcfr** [comment]
@ajtritt Could you add ben as a maintainer of pynwb on both test.pypi.org and pypi.org ? 

As a owner, you are the only one who can grant us more power or add ben directly


![image](https://user-images.githubusercontent.com/219043/43292271-8b3aa74c-9102-11e8-8360-6a681fd8cd3f.png)

![image](https://user-images.githubusercontent.com/219043/43292300-a7b91e62-9102-11e8-8602-6cde86d96787.png)

**Comment by jcfr** [comment]
Okay, I revised the release process so that pushing a tag of the form `X.Y.Z` is the only things required to have release published.

Currently being tested with https://github.com/NeurodataWithoutBorders/pynwb/commits/dev-test

If works as expected, anyone with push access should be able to create a new release.

**Comment by jcfr** [comment]
When changes will be pushed to `dev` (currently `dev-test` for testing purpose), we will have the following workflow:

![image](https://user-images.githubusercontent.com/219043/43295418-bc092b40-9112-11e8-9b1e-f9e2973c582b.png)

**Comment by jcfr** [comment]
The (test) release process works great: 

It allowed me to catch an issue with rendering of the description: #569

![image](https://user-images.githubusercontent.com/219043/43296199-f68a1af4-9117-11e8-91f8-04ea6acb3d27.png)


![image](https://user-images.githubusercontent.com/219043/43296209-04d79078-9118-11e8-9ef3-febe6fa33db2.png)

![image](https://user-images.githubusercontent.com/219043/43296224-206640c8-9118-11e8-8b8e-c9c741153970.png)


![image](https://user-images.githubusercontent.com/219043/43296287-88c63772-9118-11e8-8d21-3dd22181e448.png)

**Comment by jcfr** [comment]
There is still one issue with the upload of packages to GitHub when merged to master. Addressing this now, then we should be all set.

**Comment by ajtritt** [comment]
@bendichter is now a pynwb maintainer on pypi.org. I don't own or even see pynwb on test.pypi.org

**Comment by jcfr** [comment]
> @bendichter is now a pynwb maintainer on pypi.org.

:+1: 

>  I don't own or even see pynwb on test.pypi.org

It is here: https://test.pypi.org/manage/project/pynwb

I just added @dorukozturk  and @bendichter 

It looks like you do not have an account on test.pypi.org

**Comment by bendichter** [comment]
@jcfr 

```
cd pynwb-feedstock &&   git checkout -b $release
error: switch `b' requires a value
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -q, --quiet           suppress progress reporting
    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --detach              detach HEAD at named commit
    -t, --track           set upstream info for new branch
    --orphan <new-branch>
                          new unparented branch
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -f, --force           force checkout (throw away local modifications)
    -m, --merge           perform a 3-way merge with the new branch
    --overwrite-ignore    update ignored files (default)
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
    --ignore-other-worktrees
                          do not check if another worktree is holding the given ref
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules
    --progress            force progress reporting
```

`release` is not defined in the conda setup guide. I think `$ release=X.Y.Z` should be moved outside of the pypi guide since it applies to both pypi and conda

**Comment by bendichter** [comment]
@jcfr also, I get this error in conda step 3:

```
bash-3.2$ sed -i "2s/.*/{% set version = \"$release\" %}/" recipe/meta.yaml
sed: -i may not be used with stdin
```

**Comment by dorukozturk** [comment]
@bendichter You have to specify a release varialbe
```sh
release=X.Y.Z
```
so that release is available in your terminal.

As a check you can do 
```sh
echo $release
```

**Comment by bendichter** [comment]
@dorukozturk yes but the instructions do not tell me to do that so they should be adjusted. Once I set that variable I get an error on the next line as well

**Comment by dorukozturk** [comment]
Oh ok I see. While we were doing the release we did tye pypi and conda one after another. That explains why the variable release was defined in my case. I am checking the steps now and I will add the missing step.

**Comment by dorukozturk** [comment]
@bendichter I tried to clarify some steps in the docs. https://github.com/NeurodataWithoutBorders/pynwb/pull/572. Please take a look and let me know if you have any trouble following.

**Comment by bendichter** [comment]
```
bash-3.2$ cd /tmp && git clone https://github.com/bendichter/pynwb-feedstock.git
Cloning into 'pynwb-feedstock'...
remote: Repository not found.
fatal: repository 'https://github.com/bendichter/pynwb-feedstock.git/' not found
```

**Comment by bendichter** [comment]
ok working on it...

**Comment by bendichter** [comment]
```
bash-3.2$ cd /tmp && \
>   wget https://github.com/NeurodataWithoutBorders/pynwb/releases/download/$release/pynwb-$release.tar.gz
--2018-07-30 12:52:24--  https://github.com/NeurodataWithoutBorders/pynwb/releases/download/0.4.0/pynwb-0.4.0.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-30 12:52:24 ERROR 404: Not Found.
```

I think you still need to do steps 5 and 6 from Pypi

**Comment by dorukozturk** [comment]
That is happening because release 0.4.0 is not published. Once you follow the PyPI: Step-by-step section in the docs and actually release pynwb 0.4.0 on pypi and github, 0.4.0 will be available [here](https://github.com/NeurodataWithoutBorders/pynwb/releases) and [here](https://pypi.org/project/pynwb/#history) that the rest will work. :)

**Comment by bendichter** [comment]
Yes, but the instructions need to be corrected

**Comment by dorukozturk** [comment]
@bendichter I added a warning as part of the [pr](https://github.com/NeurodataWithoutBorders/pynwb/blob/f83a3afb03c8a2dd181ad645e47c74414d4b1b68/docs/source/make_a_release.rst). Is this clear enough or should we reword it?

**Comment by bendichter** [comment]
@dorukozturk @jcfr I'm having trouble cutting a release again. I followed the steps in the docs and I wa able to push version 0.5.0 to pynwb, but I think the release is not working because some of the tests are failing. I think these tests are failing because the Allen Institute server is not responding when we try to download the data for the conversion tests. I think I remember you guys talking about caching these datasets. Is that still on the to-do list? (@nicain and @neuromusic maybe you can help with the server issue or direct me to someone who can).
