### ISSUE TITLE
how to add an additional dynamic table

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#546]
I'd like to include data on sleep states. I want to use the same dynamic table structure that was used for trials. My code looks like this:

```python
table = DynamicTable(name='states', source='source', description='sleep states of animal')
table.add_column(name='start', description='start time')
table.add_column(name='end', description='end time')
table.add_column(name='state', description='sleep state')

for name in matin.dtype.names:
    for row in matin[name][0][0]:
        table.add_row({'start': row[0], 'end': row[1], 'state': name})

module_behavior.add_container(table)
```

but I get the following error:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/Buzsaki/convert_yuta.py", line 323, in <module>
    module_behavior.add_container(table)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 329, in func_call
    raise_from(TypeError(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'container' (got 'DynamicTable', expected 'NWBDataInterface')
```

Is there a way for me to add an additional dynamic table to the file other than trials?

**Comment by oruebel** [comment]
I think there may be a bug. In the API DynamicTable inherits from NWBContainer

https://github.com/NeurodataWithoutBorders/pynwb/blob/9fe2e920e46bb641b05f2d25229094a7fd9edda5/src/pynwb/core.py#L749

whereas in the spec it inherits from NWBDataInterface:

https://github.com/NeurodataWithoutBorders/pynwb/blob/9fe2e920e46bb641b05f2d25229094a7fd9edda5/src/pynwb/data/nwb.base.yaml#L254-L255

I'm not 100% sure which is the right way to treat the DynamicTable (i.e., as a NWBContainer or NWBDataInterface) but I think we probably just need to change ``class DynamicTable(NWBContainer)``  to ``class DynamicTable(NWBDataInterface)`` in the API. In which case your example should work.

**Comment by bendichter** [comment]
oh good catch! Let me give that a try

**Comment by bendichter** [comment]
Yes that fixed the problem. Now I'm running tests to see if it broke anything
