### ISSUE TITLE
Accessing /general/stimulus

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#547]
According to the [NWB schema](https://nwb-schema.readthedocs.io/en/latest/format.html#groups-general), there is a `stimulus` dataset in the `/general` group which optionally allows general descriptions of stimuli. However, I cannot see how to access this through the API. Setting it directly through the `stimulus` attribute of an `NWBFile`  (the same way as other datasets under `/general`, e.g. `experimenter`) does not work:

```python
>>> nwbf = NWBFile("source", "description", "id",   '2018-06-01T00:00:00')
>>> nwbf.experimenter = "Me"  # works as expected
>>> nwbf.experimenter
'Me'
>>> nwbf.stimulus = "Stimulus description"
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-150-d9786b889810> in <module>()
----> 1 nwbf.stimulus = "Stimulus description"

~/anaconda/envs/pynwb/lib/python3.5/site-packages/pynwb/form/utils.py in func_call(*args, **kwargs)
    344                 if parse_err:
    345                     msg = ', '.join(parse_err)
--> 346                     raise_from(TypeError(msg), None)
    347                 return func(self, **parsed['args'])
    348         else:

~/anaconda/envs/pynwb/lib/python3.5/site-packages/six.py in raise_from(value, from_value)

TypeError: incorrect type for 'val' (got 'str', expected 'list, tuple or dict')
```

From this and [the pyNWB docs](http://pynwb.readthedocs.io/en/latest/pynwb.file.html#pynwb.file.NWBFile.stimulus), it seems like `NWBFile.stimulus` corresponds to the `/stimulus` group, which makes sense. Is there a way of accessing `/general/stimulus` instead? Or is this an issue (known or unknown) with the schema?

I am using the latest version from PyPI:
```bash
$ pip freeze | grep pynwb
pynwb==0.3.0
```

Apologies if I'm missing something!

**Comment by bendichter** [comment]
Try nwbfile.add_stimulus

**Comment by ageorgou** [comment]
Thanks. This seems to be doing the same, i.e. adding a timeseries under `/stimulus`:

```python
>>> nwbf.add_stimulus("Stimulus description")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-155-ae3a85560c4c> in <module>()
----> 1 nwbf.add_stimulus("Stimulus description")

~/anaconda/envs/pynwb/lib/python3.5/site-packages/pynwb/form/utils.py in func_call(*args, **kwargs)
    344                 if parse_err:
    345                     msg = ', '.join(parse_err)
--> 346                     raise_from(TypeError(msg), None)
    347                 return func(self, **parsed['args'])
    348         else:

~/anaconda/envs/pynwb/lib/python3.5/site-packages/six.py in raise_from(value, from_value)

TypeError: incorrect type for 'stimulus' (got 'str', expected 'list, tuple, dict or TimeSeries')
```

**Comment by bendichter** [comment]
Oh I understand your issue now. Let me take a look

**Comment by bendichter** [comment]
So the trickiness here is that there is a `/general/stimulus` as well as a `/stimulus`. If you use `nwbf.stimulus` or `nwbf.add_stimulus`, it is trying to add to `/stimulus`, which expects a `TimeSeries` and throws an error. It looks like the same will happen if you try to include a string as an arg to the `NWBFile` constructor. I don't see a way to set the field you want.

**Comment by ageorgou** [comment]
Thanks for confirming @bendichter.

We are trying to see what metadata we should include in code that uses pyNWB, so I'm interested in people's views about this. Is this intended behaviour (perhaps `/stimulus` should be considered deprecated in NWB2)? Or is it something that should be addressed by the NWB schema, or by adding a new method to the API?

**Comment by bendichter** [comment]
I think we should keep `/general/stimulus` because there might be descriptions of how the stimulus is presented that would go best there. It seems like this would be a pretty easy fix, we just need to decide how to change the API. Maybe we could call this "stimulus_description" instead to minimize confusion in the future

**Comment by oruebel** [comment]
From what I can tell the issue is that ``/general/stimulus`` needs to be added to ``pynwb.file.NWBFile`` and we probably need to also update ``pynwb.io.file.NWBFileMap`` in this case to avoid name collision between ``/stimulus`` and ``/general/stimulus``.  I.e., this is an API issue not a schema issue.

**Comment by ageorgou** [comment]
Thanks for the input @bendichter and @oruebel. Adding an extra field (with a different name) and udpating the mapping sounds like it'd solve the confusion. Does it make sense to work on a PR for that?

**Comment by oruebel** [comment]
It looks like ``/general/data_collection`` is missing as well. I should have a PR ready to fix those items hopefully within the next 30min.

**Comment by oruebel** [comment]
#551 should fix the issue with the missing fields from ``/general``

**Comment by ageorgou** [comment]
Thanks @oruebel!
