### ISSUE TITLE
Remove autogen properties from PyNWB API

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/pynwb#55]
The following autogen datasets/attributes have been removed from the format spec and should also be removed from the API. Need to check which of these are exposed in PyNWB and if so they should be removed. As approbriate, custom get functions may be added to the corresponding container class to compute the corresponding property on request as needed. 

* NWBFile/epochs.tags
* NWBFile/epochs/epoch_X.links
* TimeSeries.timestamp_link
* TimeSeries.extern_fields
* TimeSeries.data_link
* TimeSeries.missing_fields
* Module.interfaces
* TimeSeries/num_samples
* ClusterWaveforms/clustering_interface_path
* Clustering/cluster_nums
* EventDetection/source_electricalseries_path
* ImageMaskSeries/masked_imageseries_path
* IndexSeries/indexed_timeseries_path
* RoiResponseSeries/segmentation_interface_path
* ImageSegmentation/image_plane/roi_list
* MotionCorrection/image_stack_name/original_path
* UnitTimes/unit_list

This is related to Issue  #14

**Comment by ajtritt** [comment]
Solved with GH-61
