### ISSUE TITLE
roi pixel mask shape

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#550]
The `pixel_mask` argument of `PlaneSegmentation.add_roi` is currently allowed to be (n, (x,y,v)) where n is the number of pixels, x and y are the coordinates of the pixel, and v is the value. If you try to make an roi that is 3D: (n, (x,y,z,v)), there will be an error during the `io.write` call. I would prefer if we allowed (n, (x,y,z,v)), since rois are sometimes defined in 3D and I think it will be tricky to define 3D rois in any other way. If for some reason we need to keep this only in a single plane, then I would at least like to catch this error on the `add_roi` call, not during `io.write`

**Comment by jayrbolton** [comment]
Hi @bendichter, here is my reproduction of this problem (I think the add_roi func signature has changed recently): https://gist.github.com/jayrbolton/682c984f3f55255d11115f91fde37486. All boilerplate stuff until line 30. Throws an error only on `io.write` as you describe. 

I'm assuming the spec here would need to change to support 3d: https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.ophys.yaml#L2. Has that been discussed anywhere?

I can quickly add an error checker, but it seems preferable to just support 3d.

**Comment by bendichter** [comment]
Yes @jayrbolton, it's being discussed here: #554. It would be great to have your input

**Comment by oruebel** [comment]
@bendichter can this issue be closed?
