### ISSUE TITLE
Add support for 3D ROIs

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#554]
2) Feature Request

- [ ] Replace *manifold* with start coordinate + deltas
- [ ] Add ImagingRegion that supports 2D or 3D regions
- [ ] Add RegionSegmentation 
        - can be a copy with PlaneSegmentation with ImagingRegion swapped for ImagingPlane
- [ ] add Pending deprecation to ImagingPlane and PlaneSegmentation
- [ ] add zero or more RegionSegmentation to ImageSegmentation
- [ ] Add 3 dimensions where only 2 dimensions are allowed:
        - PixelMasks
        - ImageMasks

### Problem/Use Case
Some labs are imaging across volumes. Currently, the schema is restricted to imaging across planes.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
What's the purpose of having `ImageSegmentation` and `RegionSegmentation`? What if we just had ≥0 `ImageSegmentation` objects and did away with `RegionSegmentation`

**Comment by bendichter** [comment]
also, are we including the idea that pixel mask is removed and rendered on the fly?

**Comment by ajtritt** [comment]
> What's the purpose of having `ImageSegmentation` and `RegionSegmentation`? What if we just had ≥0 `ImageSegmentation` objects and did away with `RegionSegmentation`

For consistency with the current schema. 

> also, are we including the idea that pixel mask is removed and rendered on the fly?

Lets keep pixel mask for now. We can add a function for autogenerating a pixel mask from an image mask to deal with the inconvenience.
