### ISSUE TITLE
Bug: unittest test_standard_iterator_unbuffered seems buggy

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#56]
Subtle bug, but here it goes:

On test_standard_iterator_unbuffered (tests/unit/form_tests/utils_test/test_core_DataChunkIterator), line 57 and 59, we have
dci = DataChunkIterator(data=range(10), buffer_size=1)
self.assertTupleEqual(dci.max_shape, (None,))

I claim it should read:
self.assertTupleEqual(dci.max_shape, (10,))

This is because in the constructor of DataChunkIterator we have:

```        if self.max_shape is None:
            # If the self.data object identifies it shape then use it
            if hasattr(self.data,  "shape"):
                self.max_shape = self.data.shape
                # Avoid the special case of scalar values by making them into a 1D numpy array
                if len(self.max_shape) == 0:
                    self.data = np.asarray([self.data, ])
                    self.max_shape = self.data.shape
                    self.__data_iter = iter(self.data)
            # Try to get an accurate idea of max_shape for other Python datastructures if possible.
            # Don't just callget_shape for a generator as that would potentially trigger loading of all the data
            elif isinstance(self.data, list) or isinstance(self.data, tuple):
                self.max_shape = ShapeValidator.get_data_shape(self.data)```
```

Initially, max_shape is None will be true, and data will not have attribut.  So the flow control will pass to line ```elif isinstance(self.data, list) or isinstance(self.data, tuple):```

However, this will not evaluate to true in python3, because data is type "range" (in python 2, it is type list, so the line will evaluate True, and max_shape would be set to 10).  

In python3 max_shape will not be set, so the test will pass, but I think this is incorrect behavior for the test.  I think ```elif isinstance(self.data, list) or isinstance(self.data, tuple):``` should be replaced by ```elif isinstance(self.data, (list, tuple, range)):``` and tests or other code should be adjusted accordingly.  This is a short job, but one prone to mistakes, and since it involves rewriting test behavior, I vote for @ajtritt to make the modifications if he agrees.

**Comment by oruebel** [comment]
Ok, I'll take a look. I think this is a valid change.  I guess a more general check may be to check if ```len``` is supported to also try to determine the shape for other generators one might come up with. I believe ```ShapeValidator.get_data_shape``` should already support this, however, for generators it will need to load the first generated value to determine the shape, which may be problematic here. I think the correct fix may be a bit later in the DataChunkIterator.__init__

```
        # If we still don't know the shape then try to determine the shape from the first chunk
        if self.max_shape is None and self.__next_chunk.data is not None:
            data_shape = ShapeValidator.get_data_shape(self.__next_chunk.data)
            self.max_shape = list(data_shape)
            self.max_shape[0] = None
            self.max_shape = tuple(self.max_shape)
```

Instead of always setting ```self.max_shape[0]=None``` here, we should probably check if ``len`` is supported by the iterator and set the first dimensions of max_shape accordingly. 

In Python2 the equivalent here seems to be if xrange is used rather than range.

**Comment by nicain** [comment]
Sounds good to me.  I have been walking through (with andrew's help) using six to get cross compatibility.  If you can get this test working as intended, Ill can push ahead with cross-compat that passes all the tests (were so close!  this is actually the last test!).  six.moves.range in the test is what was working.

**Comment by oruebel** [comment]
Ok. I'll take a look tonight at fixing the code.

**Comment by oruebel** [comment]
Ok, I've create the branch datachunkiter_max_shape_iter_fix with the bug fix. 

@ajtritt can you please review the pull request and approve the changes. Feel free to just merge and close the datachunkiter_max_shape_iter_fix branch if that is simpler, otherwise I can do the merge.

**Comment by nicain** [comment]
Thanks Oliver @ajtritt any chance you can merge this today?
