### ISSUE TITLE
Add method to attach the simulus/protocol name to PatchClampSeries

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#564]
### Problem

The NWB schema documentation does currently not provide a way to attach the stimulus/protocol name to a PatchClampSeries.

Some existing users of NWBv1, e.g. http://celltypes.brain-map.org/experiment/electrophysiology/474626527, use a text dataset named `aibs_stimulus_description` to store that name. This dataset is labeled as `neurodata_type = Custom` in order to keep the NWB files schema compliant.

### Not viable alternative solutions

Encoding the stimset name in the group name itself is not a viable option. The reasons, taken from https://nwb-users.slack.com/archives/C5XKC14L9/p1532442382000078?thread_ts=1530802845.000026&cid=C5XKC14L9, are:
- The group name has to be unique so you have to attach some numbers to the stimulus name and on reading remove these numbers again. Basically doing a custom serializing/deserialization on the string.
- HDF5 objects names can not contain arbitrary characters ('/' being the most notable one) so you would need to introduce some mapping if you use forbidden characters in your stimset name.

### Proposed solution

- Schema: Add `stimulus_description` as required dataset to PatchClampSeries
- Code: Add `stimulus_description` to the `__init__` method of PatchClampSeries

If there is consent that this is something worth doing I can try to find time doing it.

**Comment by ajtritt** [comment]
@t-b A couple questions/comments... I'm just trying to understand what the need is.

1) What information are you trying to store? It sounds like the group name is okay as a unique identifier, but there is other information you want to store. What do you mean by "stimulus/protocol name"?
2) Since *PatchClampSeries* is a *TimeSeries*, it already has a *description* field. Could you store it here?

**Comment by t-b** [comment]
@ajtritt Don't hestitate to ask!

> What information are you trying to store? It sounds like the group name is okay as a unique identifier, but there is other information you want to store. What do you mean by "stimulus/protocol name"?

In intracellular elektrophysiology (I'm not a scientist though):
The protocol/stimset name is the name of the dataset used for stimulating the cell. This ranges from "Short Square" to "Ramp" or someting similiar.

> Since PatchClampSeries is a TimeSeries, it already has a description field. Could you store it here?

Yes of course. But I would need to use some custom serialization, e.g. JSON, in case I want to store multiple additional entries. And with BASE64 encoding I could also store arbitrary binary data in the description field.

But that would leave the burden onto the user to figure out my custom serialization.

**Comment by jeffteeters** [comment]
@t-b I wonder if the abstractfeatureseries might help for this?
https://nwb-schema.readthedocs.io/en/latest/format.html#abstractfeatureseries
The abstractfeatureseries is a time series that specifies values of stimulus features over time.  The values of the features are stored in the "data" dataset of the timeseries.
Perhaps one of the columns in the "data" dataset (values of one of the features) could be used to indicate the type of stimulus, e.g. 1 = "Short Square", 2="Ramp", ... and other features could be used to specify the parameters of the given stimulus, e.g. spatial frequency of a short square.  The "features" dataset would contain a legend specifying what the different columns in "data" contain.  If the stimulus could be completely described by an abstractfeatureseries, then in the description field for PatchClampSeries you could specify what the corresponding abstractfeatureseries stimulus was.

**Comment by t-b** [comment]
@jeffteeters Thanks for the hint.
AbstractFeatureSeries sound interesting. Especially as you can store text well. But the main problem persists:

 > [...] then in the description field for PatchClampSeries you could specify what the corresponding abstractfeatureseries stimulus was.

as this uses description in exactly the way I want to avoid.
