### ISSUE TITLE
wheel test failing

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#565]
## 1) Bug

ruamel chokes when importing pynwb installed from a wheel, but test suite runs fine. 

https://circleci.com/gh/NeurodataWithoutBorders/pynwb/5534

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
I suspect it's requirements.txt vs setup.py
