### ISSUE TITLE
pynwb.base.TimeSeries.starting_time & rate does not return the floats given in the argument

### ISSUE THREAD

**Issue by lungsi** [NeurodataWithoutBorders/pynwb#579]
## 1) Bug
I am able to create a TimeSeries object but while checking if the object was what I intended to create I noticed something weird.
If `ts = TimeSeries (...)` (as shown below), I can get the exact **float** values I gave in the argument for `ts.resolution` and `ts.conversion`.
But for `ts.starting_time` and `ts.rate`, they do not return floats instead they return **None**; which is the pynwb default value.

### Steps to Reproduce
```
from pynwb import TimeSeries

ts = TimeSeries( name = "dummy",
                 source = "soma",
                 data = list(range(0, 100, 10)),
                 unit = "milliVolt",
                 resolution = 0.01,
                 conversion = 1000.0,
                 timestamps = list(range(10)),
                 starting_time = 0.0,
                 rate = 1/0.01 )

>> ts.resolution # same for ts.conversion
0.01

>> type(ts.conversion) # same for ts.resolution
<type 'float'> 

>> ts.starting_time # same for ts.rate
None

>> type(ts.rate) # same for ts.starting_time
<type 'NoneType'>
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Python
- **Python Version:** Python 2.7
- **Operating System:**  Ubuntu 16.04
- **Pynwb Version:**  0.4.1

**Comment by bendichter** [comment]
This is because you either enter timestamps or rate+starting_time, not all three. We should catch this and raise an error.
