### ISSUE TITLE
Please distribute tests/ within your source releases on PyPI

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#607]
ATM tarballs on pypi seems to lack `tests/`:
```
$> tar -tzvf <(wget -O- -q https://files.pythonhosted.org/packages/6f/f2/5802890d6d1706dca27b69eac298b82e5c61af620d570be83709639e4cdf/pynwb-0.4.1.tar.gz) | grep test
>
```
so redistributors (e.g. Debian) cannot assure correct operation of the pynwb, and would need to base their distribution on dumps of this git repository

**Comment by oruebel** [comment]
@dorukozturk @jcfr any thoughts on this?
