### ISSUE TITLE
RFC: upload 0.4.1+git41-gc3a1bed to (Neuro)Debian?

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#609]
I prepared a Debian package,  but did it on top of the current dev since had to generate a new tarball anyways (#607).  Any objections if I upload this snapshot to Debian (will take some time to get through NEW anyways) and NeuroDebian (backports for where it built/tested fine, #608)

**Comment by yarikoptic** [comment]
knock knock - if there would be no objections, I will upload later today ;-)

**Comment by bendichter** [comment]
I'm going to cut a release of the latest dev branch. There have been some important fixes we need to get into the wild. Could you hold off until that's done? Should be 1 day max.

**Comment by yarikoptic** [comment]
Sure!

**Comment by bendichter** [comment]
technical difficulties but we should be cutting a release for 0.5.0 soon!

**Comment by yarikoptic** [comment]
Thanks for the update. That is ok - I am not in a rush on this one. Just didn't want it to slip away from my attention

**Comment by yarikoptic** [comment]
I see the 0.5.1 tag, I guess time to update to that release and upload, right? ;)

**Comment by bendichter** [comment]
Yes! Sorry the technical difficulties distracted me and I forgot to let you know. Please proceed with the upload when you have a chance

**Comment by yarikoptic** [comment]
eh, will need to package from git anyways since #622 is not yet in, and 0.5.1 doesn't include tests.

**Comment by yarikoptic** [comment]
with the patch from #625 uploaded 0.5.1-1 into Debian proper (would take a while to get through NEW anyways) and NeuroDebian (should already be available from the main NH server, others will pick it up soon and page will get generated on the website).
