### ISSUE TITLE
feature: pandas interface for tables

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#631]
pandas is a widely-adopted and performant Python package for working with (and viewing!) tabular data. It would be useful if DynamicTable and NWBTable had methods for casting to and from pandas DataFrames. 

I'm working on this [here](https://github.com/NileGraddis/pynwb/tree/feature/units-interface). If there are no objections, I'll keep going.

**Comment by NileGraddis** [comment]
It might be reasonable to fold #623 into this work as well.

**Comment by ajtritt** [comment]
As along as this is an optional feature, I have no objections.  Are you adding it as a property/method of DynamicTable?

**Comment by bendichter** [comment]
Thanks @NileGraddis this is looking great!

**Comment by NileGraddis** [comment]
@ajtritt I agree and am indeed implementing it that way
@bendichter Thanks!

**Comment by ajtritt** [comment]
@NileGraddis one thing that might be problematic, and that you wouldn't know from the issue I created is that DynamicTable will eventually support *VectorData*/*VectorIndex*.

**Comment by NileGraddis** [comment]
@ajtritt Thanks for the heads-up. My understanding from looking at the code is that IndexedVector implements an efficient store where data are concatenated into a vector (VectorData) and indices into that vector (VectorIndex) are used to recover individual items. Does this sound about right? When you say that DynamicTable will support this structure, do you mean that:
1. A column of a DynamicTable might have elements which are variable-length containers. This column will be implemented using an IndexedVector.
2. A DynamicTable itself might use an IndexedVector under the hood to store its data.
3. both/neither/something I haven't thought of :)

**Comment by ajtritt** [comment]
@NileGraddis  a VectorData-VectorIndex pair will be acceptable as column in the DynamicTable

**Comment by NileGraddis** [comment]
@ajtritt What should be the return type of [:] (and of [i]) on a DynamicTableRegion? Currently for an NWBTableRegion, we get back a list of tuples (or one tuple in the singular case). This is easy to implement for DynamicTable, but has a couple disadvantages:
1. it makes users rely on order, rather than names
2. user code which works with entire tables requires special casing to also handle subsets of those tables' rows.

My inclination is for the __getitem__ methods on these classes to return subtables whose data can then be accessed in the normal way for those table classes. Does that sound crazy?

**Comment by ajtritt** [comment]
@NileGraddis returning something that behaves like a DataFrame would be preferable. I tried implementing \_\_getitem\_\_ so that it returned a [numpy structured array](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html). I had to set it aside, but if I remember correctly, the crux was building *dtype*. You'll probably find my commented-out chunks of code, feel free to throw that out if its not useful.

**Comment by ajtritt** [comment]
@NileGraddis I notice you made DynamicTableRegion an NWBDataInterface. This will be problematic, since in the schema, it extends NWBData (a dataset) and NWBDataInterface is a group. You might want to hold off until #634 gets merged so you can work on the DynamicTableRegion implementation I added

**Comment by ajtritt** [comment]
#634 has been merged... I also started working on allowing VectorData/VectorIndex to go in DynamicTable. Part of that was moving IndexedVector functionality into VectorIndex, sorry about the moving target. 

https://github.com/NeurodataWithoutBorders/pynwb/blob/f6ee7e6a0f7e9b250d25c6e992a178e33686924b/src/pynwb/core.py#L293
