### ISSUE TITLE
Replace Epochs and ROITable with DynamicTable

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#643]
### Problem/Use Case
Making these structures DynamicTables will make it easier for users to add additional metadata. Currently, they must use an extension to include additional metadata.

This will have an impact on issues discussed in #637 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
@neuromusic @bendichter @oruebel This change has a couple effects:

1) Pixel masks and image masks don't both need to be required. Are there any objections to allowing either or both? 
2) ROIs get integer IDs, so they don't need a *name*. 

IIRC, both of these were pain points, but I just wanted to double check. Is there anyone else that should weigh in on these?

**Comment by oruebel** [comment]
If I recall previous discussion on this correctly (and may not) then at least one of pixel mask or image mask should always be required. I'm not sure if we can actually formally specify this in the current schema language (i.e., I think we can have both optional or both required but not an either/or). I think the "either or both " requirement is something we can currently only enforce on the API level (which is fine).

**Comment by ajtritt** [comment]
@oruebel 
>  I think the "either or both " requirement is something we can currently only enforce on the API level (which is fine).

That is correct. The API will enforce this.

**Comment by bendichter** [comment]
I don't really care which one we use, but we should only require 1.

**Comment by ajtritt** [comment]
Closing this and using two separate issues.
