### ISSUE TITLE
Creating env with conda and requirements.txt shows dependency conflict

### ISSUE THREAD

**Issue by mamelara** [NeurodataWithoutBorders/pynwb#645]
## 1) Bug
When trying to create an environment based off of the requirements.txt, conda will throw an error
```shell
[I] ➜ conda create --name pynwb --file requirements.txt
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy==1.14.2
  - pandas==0.19.2 -> numpy=1.11
Use "conda info <package>" to see the dependencies for each package.
```
### Steps to Reproduce
```
conda create --name pynwb --file requirements.txt
```
### Environment
 **Python Executable:** Conda 
**Python Version:**  Python 3.6
**Operating System:** macOS
**Pynwb Version:** git tag latest, branch dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by oruebel** [comment]
@NileGraddis #637 #631

**Comment by t-b** [comment]
After adding the conda-forge channel this works on windows with

```
conda create --name pynwb python=3.6 --file requirements.txt
```

**Comment by mamelara** [comment]
conda-forge is on my channel config.

And I still get this:
```yaml
[I] ➜ cat ~/.condarc
channels:
  - defaults
  - conda-forge
```

```console
[I] ➜ conda create --name pr_test python=3.6 --file requirements.txt
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy==1.14.2
  - pandas==0.19.2 -> numpy=1.11
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by t-b** [comment]
@mamelara Are you sure you are using the latest version? This is currently `ca60249f (Merge pull request #652 from ukos-git/bug/install_python3_numpy, 2018-10-11)`.

**Comment by mamelara** [comment]
Ah thanks! Yes can confirm this works now. Will close this.
