### ISSUE TITLE
Documentation broken link: "Edit on github" on read-the-docs

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#647]
## 1) Bug

Documentation redirect link is broken; on https://pynwb.readthedocs.io/en/latest/index.html, the top-right "Edit on github" link points to:

```
https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/home/docs/checkouts/readthedocs.org/user_builds/pynwb/checkouts/latest/docs/source/conf.py/index.rst
```

which returns 404.

**Comment by oruebel** [comment]
Just as an additional data point, this seems to be an issue of ``latest`` build  while for the ``stable`` build the links seem  to work. I.e., the links on https://pynwb.readthedocs.io/en/stable/ are ok and on https://pynwb.readthedocs.io/en/latest they are broken. 

It seems like there are a bunch of issue tickets for this sort of problem on readthedocs, but I have not found the right solution for this yet. 

On a separate issue, I believe right now we point users typically to the ``latest`` docs but we may want to change this to point to ``stable`` (i.e., the latest release).
