### ISSUE TITLE
evaluate use if __prepare__

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#65]
Right now, form.build.DecExtenderMeta uses __prepare__ to populate the namespace of ObjectMapper with a decorator. We need to evaluate whether the solution of calling the decorator from the ObjectMapper class (`@ObjectMapper.constructor_arg` vs `@constructor_arg`) is sustainable.

see src/form/build/map.py

This relates to #59

**Comment by nicain** [comment]
Agreed. I'll hold off on https://github.com/NeurodataWithoutBorders/pynwb/issues/59 until I hear about this. Thanks!

**Comment by nicain** [comment]
@ajtritt I thought about several options last night, and the only one I came up with that is not terrible is illustrated in https://github.com/nicain/pynwb/tree/issue/constructor_arg

Basically the decorator contructor_arg gets special treatment, and moved out of the metaclassing in DecExtenderMeta (not illustrated in the branch, but pulled out of __prepare__ and made a function at module level).  

The advantage of this is that it is explicit about what is being done (tagging these methods with particular information), and works in python2 and python3.  The disadvantages are that it decouples what the information is used for away.  Also, its a pretty serious change to the design of how all the classes in build/map are built, so I am not pushing this as a solution.  Its just the best option I could come up with, out of several bad ones.

Let me know what you think about this, or if you have other suggestions.

**Comment by nicain** [comment]
I just updated https://github.com/nicain/pynwb/tree/issue/constructor_arg, removing "__prepare__" and making sure to have constructor_arg functionality available to the classes that need it.  This branch passes all the tests.

**Comment by ajtritt** [comment]
resolved in PR #98
