### ISSUE TITLE
RuntimeWarning in numpy==1.15

### ISSUE THREAD

**Issue by ukos-git** [NeurodataWithoutBorders/pynwb#650]
## minor (Warning) Bug

We currently only support numpy 1.14.2. This was the newest available in cbb3043f updated by  @dorukozturk  (2018-04-05 23:14:29 -0700)

newer versions of numpy add a warning, if the size of a dtype element changes. This is probably due to a programming error at data_type handling

### Steps to Reproduce
```
pip install numpy==1.15
python docs/gallery/domain/icephys.py
```
### Environment

- **Python Executable:** python
- **Python Version:** Python 2.7.15rc1
- **Operating System:** Ubuntu 18.04
- **Pynwb Version:** current dev 430ae547afb1f454c6e7df636914ea082fc36fc2

### Problem

```console
$ python docs/gallery/domain/icephys.py
/home/matthias/Documents/Projects/pynwb/env/local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/matthias/Documents/Projects/pynwb/env/local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/matthias/Documents/Projects/pynwb/env/local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/matthias/Documents/Projects/pynwb/env/local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
```

**Comment by ukos-git** [comment]
sorry. We do not support 3.7, right?

**Comment by ukos-git** [comment]
**test installation from a wheel** on circleci uses numpy 15.2 anyway so this has to be addressed one time or another.

```console
wheelinstall-py27 installed: certifi==2018.8.24,chardet==3.0.4,h5py==2.8.0,idna==2.7,null==0.6.1,numpy==1.15.2,pandas==0.23.4,pynwb==0.5.1.post0.dev35,python-dateutil==2.7.3,pytz==2018.5,requests==2.19.1,ruamel.ordereddict==0.4.13,ruamel.yaml==0.15.72,six==1.11.0,urllib3==1.23
```

**Comment by t-b** [comment]
@ukos-git From the [numpy release notes](https://docs.scipy.org/doc/numpy/release.html#numpy-1-15-1-release-notes).

> The annoying but harmless RuntimeWarning that “numpy.dtype size changed” has been suppressed. The long standing suppression was lost in the transition to pytest.

So I guess this can be closed. Please reopen if required.

**Comment by ukos-git** [comment]
@t-b Thank you for digging into it. The size change is only minimal: ```Expected 96, got 88``` sounded like the a (true) binary -> string conversion. As it is suppressed in 15.1, let's assume the warning never existed.
