### ISSUE TITLE
Make Epochs a DynamicTable

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#664]
### Problem/Use Case
The epoch table is currently a compound-dtype table. This makes it hard to extend and inefficient for querying along a single feature. 

Part of this move of making Epochs a DynamicTable should also involve removing the use of RegionReferences for indexing into an array of TimeSeriesIndex. Removing this will make the schema less dependent on HDF5 primitives and make it easier to use alternative backends.

Relates to #643 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
@ajtritt close via #690?

**Comment by ajtritt** [comment]
oops. close via #682
