### ISSUE TITLE
Convert between pixel mask and image mask

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#669]
## Feature Request
Users are no longer required to provide both *pixel_mask* and *image_mask*--they can provide either or both.  To make it easier to work with files that use different mask types, supply PlaneSegmentation with a method that can convert from *pixel_mask* to *image_mask* and back. 

Motivated by @bendichter [here](https://github.com/NeurodataWithoutBorders/pynwb/pull/665#issuecomment-429113306)

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by mamelara** [comment]
Hello!

Looking to be a new contributor to pyNWB and wanted to work on this issue. I am a bit confused as to the difference between pixel_mask and img_mask. To me, the only difference is that one is basically a list of lists and the other is a list of tuples (this is from my very beginner understanding of the two types.) Could you please elaborate on what is expected from this conversion? Thanks!

**Comment by bendichter** [comment]
Hey @mamelara, welcome to the team! pixel_mask and img_mask are two different ways of specifying regions of an image. A pixel mask is a list where each element of the list describes a single pixel: (x, y, value). The size of a pixel mask is [any x 3]. For an image mask, the mask is the same size as the original image, and only the values in the region are non-zero. We would like to be able to convert from one type to another. Does that help?

**Comment by ageorgou** [comment]
I just thought I'd mention, since I don't see it here, that it may be useful to look at how [the old NWB  API](https://github.com/NeurodataWithoutBorders/api-python/blob/master/nwb/nwb_utils.py#L278) created a pixel mask from an image mask and vice versa. Some changes may be needed,  though, at least because the pixel mask now also contains the weights (which were a separate argument in the old API).
