### ISSUE TITLE
Indexing Dynamic Table

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#673]
I have a question on how DynamicTable rows are supposed to be retrieved when using non-default ids. Consider the following example which adds two rows with ids 1 and 2:

```python
from pynwb.core import DynamicTable

spec = [
    {'name': 'foo', 'description': 'foo column'},
]
data = [
    (1, {'foo': "first content"}),
    (2, {'foo': "second content"})
]
table = DynamicTable("test_table", "example", "a test table", columns=spec)
for id, row in data:
    table.add_row(row, id=id)

print(table[1])
print(table[2])

# for id, row in data:
#     assert table[id, 'foo'] == row['foo']
```

This gives an error when printing the second row:
```
(2, 'second content')
Traceback (most recent call last):
  File "try_dynamic_table.py", line 15, in <module>
    print(table[2])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/core.py", line 1103, in __getitem__
    ret = tuple(col[arg] for col in self.__df_cols)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/core.py", line 1103, in <genexpr>
    ret = tuple(col[arg] for col in self.__df_cols)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/core.py", line 275, in __getitem__
    return self.data[args]
IndexError: list index out of range
```

Looking at [the source for DynamicTable](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/core.py#L1103), I can see why this happens (the argument is directly interpreted as a row number, rather than an id from `table.id`). I don't know if this is intentional, and the unit tests for DynamicTable all use sequential 0-based ids. If this is the intention, I'm not sure I understand what the purpose of passing an explicit id is.

If this is indeed a bug, I'm happy to submit a PR for it and related tests.

**Comment by ajtritt** [comment]
This isn’t a bug, this is intentional. The point of letting users pass in IDs is override of the default autoincrementing behavior. Eventually, you should be able to query by ID, but right now, you can only index by row number.

**Comment by ageorgou** [comment]
Thanks. Are there any thoughts on making tables themselves iterable, or should I just iterate over `table.id.data` to access each row?

**Comment by bendichter** [comment]
@ageorgou you might like `table.to_dataframe()` Pandas dataframes are iterable (`df.iterrows()`) and have a lot of other handy features for manipulating tabular data

**Comment by ageorgou** [comment]
Thanks @bendichter. I was just looking for a more elegant way than how I'm currently iterating, so I don't think converting to a dataframe will be necessary.

I'll close this now, thanks for the clarifications.
