### ISSUE TITLE
Do not install enum34 (from requirements-dev.txt) in Python>3.4

### ISSUE THREAD

**Issue by tjd2002** [NeurodataWithoutBorders/pynwb#677]
## 1) Bug

`requirements-dev.txt` installs enum34 irrespective of the python version.

enum34 provides python 3.4-like enum functionality to earlier versions of python. If it is installed on python >3.4, it can actually break enums (https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36)

We don't seem to use any enums in pynwb, but flake8 depends on it. 

Here are 2 proposed solutions

1) If requirements-dev.txt is meant to freeze requirements, we should add an environment marker to the enum34 line to avoid installing it inappropriately:
   ```
   enum34==1.1.6 ; python_version < '3.4'
   ```
2) If we don't care about capturing the version of enum34, we could just remove this line, and let flake8 pull in an appropriate version of enum34. 

Solution (2) would also allow for the use of conda to install all the requirements (e.g. `conda create -c conda-forge -n pynwb python=3.6 --file requirements.txt --file requirements-dev.txt`). Currently that command fails because conda (correctly) detects a conflict between python==3.6 and enum34==1.1.6. Solution (1) won't work in this case since conda doesn't know how to interpret environment markers. (pip is not as picky, and will happily install enum34 on python 3.5 or 3.6). 
## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
From my POV solution 2 sounds good.

**Comment by oruebel** [comment]
Since this is a dependency of flake8 I think 2 is fine. @dorukozturk @jcfr thoughts?

**Comment by dorukozturk** [comment]
2 sounds good to me.

**Comment by tjd2002** [comment]
A note for posterity: if _pynwb itself_ ever starts using python enums, then this approach will need to be revisited. The correct solution in that case would probably be to use solution (1) above in requirements.txt. However, since this is currently just a dependency of one of our dependencies it's ok to punt this, and rely on pip to install the package only when needed.
