### ISSUE TITLE
Allow NWBHDF5IO and HDF5IO to accept h5py.file objects

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#680]
These classes currently require a path and construct an `h5py.File` object at that path when their `open` method is called. It would be handy to have the option of passing in a pre-constructed `h5py.File` object (skipping the construction of a new one in `open`). This would not impact existing functionality, but would allow us to use h5py features for free without explicitly implementing support for them (for instance: using the core driver for fast testing).

**Comment by bendichter** [comment]
Hey @NileGraddis, sounds interesting. Could you expand on what features this would provide?

**Comment by NileGraddis** [comment]
@bendichter This is an example of dependency injection - a pattern where an object is (in this case optionally) given the tools it needs rather than building them itself. You are probably familiar with this pattern from other Python packages - h5py actually [implements it for its File object](http://docs.h5py.org/en/latest/high/file.html#python-file-like-objects).

This is useful for testing (you can make an object that stores info about how it was used and pass that in, for instance). It also gives users the ability to pass in subclasses of h5py.File that do whatever handy stuff they want (logging, automatic filter application, anything). It also gives us access to lots of h5py features without requiring us to implement or maintain support for them.
