### ISSUE TITLE
Allow users to specify other sets of time intervals

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#683]
### Problem/Use Case
Right now all time interval data is stored in either *epochs* or *trials*. This should be generalized so that users can arbitrary types of intervals and not be restricted to classifying them as epochs or trials. 

- [ ] make a new top level group called *intervals*
- [ ] change named of neurodata_type *EpochTable* to something more general i.e. *TimeIntervals*
- [ ] make *trials* an instance of *TimeIntervals*
- [ ] move *epochs* and *trials* to the *intervals* top-level group
- [ ] let *intervals* take any number of *TimeIntervals* objects

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by ajtritt** [comment]
@bendichter please provide feedback

**Comment by bendichter** [comment]
I don't think this would cause an issue for me, but it's not solving an issue I have either. Is there a lab that needs this?

**Comment by tjd2002** [comment]
I like the idea of having a more general multicontainer of TimeIntervals available.

We are already saving pynwb.misc.IntervalSeries objects in a column of our Units table for clustered spikes (to indicate the valid periods, or 'observation intervals' for each clustered unit). This seems to work fine; would this still be the right way to do things after this proposed refactor?

**Comment by bendichter** [comment]
@tjd2002 That sounds like a good use of `IntervalSeries`. Let's make sure the proposed changes are the best way to meet your needs. Is there a specific type of data you were going to use this data structure for?
