### ISSUE TITLE
Implement RoiResponseSeries

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#7]
Originally reported by: **dcamp_lbl (Bitbucket: [dcamp_lbl](https://bitbucket.org/dcamp_lbl), GitHub: Unknown)**

----------------------------------------

Create the base RoiResponseSeries class

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/7

**Comment by ajtritt** [comment]
*Original comment by* **dcamp_lbl (Bitbucket: [dcamp_lbl](https://bitbucket.org/dcamp_lbl), GitHub: Unknown)**:

----------------------------------------

RoiResponseSeries basic class is done and basic test case.

Need save and load functions.

**Comment by oruebel** [comment]
Save and load handled by default mapping. Need integration tests.
