### ISSUE TITLE
Docs still point to bitbucket repo

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#70]
Some of the docs still point to the pre-migration bitbucket repository 

Here is a screen cap listing some of the locations, there might be more:
![image](https://user-images.githubusercontent.com/113055/29194539-eb1fb9b4-7dde-11e7-88d8-f4d3609aff55.png)

@jhyearsley, do you want to take a stab at correcting these, and submitting a PR?

**Comment by jhyearsley** [comment]
Definitely, I will look into this tomorrow.

**Comment by jhyearsley** [comment]
I've changed the simple links from the screen shot that can just be pointed directly to github, but there are other links referencing content on bitbucket that I don't have access to (or doesn't exist).

For instance in the `setup.py` file, the source of the nwb schema is downloaded from a bitbucket link in a `downloads` folder hosted on bitbucket, and I'm not sure where the `nwb_core.tar` file lives now.

There are also references in some of the Jupyter notebooks to issues hosted on bitbucket that are broken links. Not sure what the thought process is on that. One solution is to just remove the links but I will wait for suggestions before editing that.

**Comment by oruebel** [comment]
I've fixed the references in the current notebooks. I've searched through both the pynwb and nwb-schema repo, and it looks like the only relevant instance that still requires fixing is in the function ```CustomBuild``` in ```setup.py``` which references a tar file on bitbucket. @ajtritt can you check whether that link needs to be updated.

**Comment by ajtritt** [comment]
@oruebel that link does not need to be updated. That class can be removed from setup.py

**Comment by oruebel** [comment]
@ajtritt thanks for the quick response. I'll remove the class and close this ticket.
