### ISSUE TITLE
Document `__columns__` in DynamicTable

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#702]
### Problem/Use Case
DynamicTable comes with a feature for specifying columns and handling the boiler plate code for adding them. Unfortunately, as demonstrated in #701, this has yet to be documented for users.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
Can't we just drop `__columns__` if the class is defined in the YAML file?

**Comment by ajtritt** [comment]
@t-b yes, we should be able to do that. There is other functionality, such as child containers in \_\_nwbfields\_\_ that could be added to classes based on what's defined in the spec. I would like to address all of these features together.
