### ISSUE TITLE
icephys tutorial warning

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#714]
## Bug

running the icephys tutorial, I get the following warning: 
```python
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:762: MissingRequiredWarning: dataset 'series_index' for 'sweep_table' of type (SweepTable)
  warnings.warn(msg, MissingRequiredWarning)
```

which indicates that the tutorial is not creating a valid NWB file. 

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by t-b** [comment]
@bendichter I think the warning is BS.

If I look into the file with ` h5dump -H icephys_example.nwb  | grep -A 20 series_index`

I get

```
           DATASET "series_index" {
              DATATYPE  H5T_STD_I32LE
              DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
              ATTRIBUTE "help" {
                 DATATYPE  H5T_STRING {
                    STRSIZE H5T_VARIABLE;
                    STRPAD H5T_STR_NULLTERM;
                    CSET H5T_CSET_UTF8;
                    CTYPE H5T_C_S1;
                 }
                 DATASPACE  SCALAR
              }
              ATTRIBUTE "namespace" {
                 DATATYPE  H5T_STRING {
                    STRSIZE H5T_VARIABLE;
                    STRPAD H5T_STR_NULLTERM;
                    CSET H5T_CSET_UTF8;
                    CTYPE H5T_C_S1;
                 }
                 DATASPACE  SCALAR
              }
```
