### ISSUE TITLE
Bits per pixel not respected

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#732]
When creating an `ImageSeries`, we always seem to end up with 8-bit data, even if that's not enough to store all values, which then corrupts our data. This happens even when explicitly setting the `bits_per_pixel` to a higher value.
Is that option supposed to be respected for I/O, or is it just metadata? Either way, is there a way to use more than 8 bits per pixel?

Steps to reproduce:

```python
from datetime import datetime

import numpy as np
from pynwb import NWBFile, NWBHDF5IO
from pynwb.image import ImageSeries

nwbfile = NWBFile('image series test', 'NWB123', datetime.now())

# Add a single-frame image that needs more than 8 bits
img = np.array([[255, 128], [0, 10]], dtype=np.int16)
print(img.dtype)
img_series = ImageSeries('image_series', data=[img],
                         timestamps=[0.0], bits_per_pixel=16)
nwbfile.add_acquisition(img_series)

# Write the file
with NWBHDF5IO('test_image.nwb', 'w') as io:
    io.write(nwbfile)

# Check again: the image is now 8bit
with NWBHDF5IO('test_image.nwb', 'r') as io:
    nwbfile = io.read(nwbfile)
    img = nwbfile.get_acquisition('image_series')
    print(img.data.dtype)
```

for which the output is:
```
<snipped timezone warning>
int16
int8
```

This is with the current `dev` (033d2462) and, in case it makes a difference:
```
numpy==1.13.0
h5py==2.8.0
```

Thanks in advance!

**Comment by bendichter** [comment]
@ageorgou This behavior is due to the specification of [`ImageSeries`](https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=ImageSeries#imageseries) in the schema. It says here that `ImageSeries.data` is of type `int8`, which means it will be saved as `int8` no matter how you enter it. `bits_per_pixel` does not change this- this value is simply metadata for indicating I think the resolution. I think the best solution would be to allow a user to add data in whatever numeric type require. This would require a change to the schema language. We have an open issue for this [here](https://github.com/NeurodataWithoutBorders/nwb-schema/issues/226)

**Comment by tjd2002** [comment]
In the meantime, should we add a check in the API that warns if any value larger than 8 is specified for `bits_per_pixel`?
[EDIT: I retract this suggestion, given that this is a bug, and the int8 type should just be seen as a suggestion]

**Comment by oruebel** [comment]
CC @ajtritt . Usually ``int8`` should be interpreted as the minimum resolution so that, e.g., ``int16`` or ``int32`` should still be allowed. I think this may be a bug.

**Comment by ageorgou** [comment]
@bendichter My understanding of the [schema documentation](https://nwb-schema.readthedocs.io/en/latest/format_description.html#design-notes) is that the datatype given in the specification is just the suggested precision for integers, not the only one allowed:
>The listed size of integers is the suggested size. What’s important for integers is simply that the integer is large enough to store the required data, and preferably not larger. 

and further up (in the section on [time values](https://nwb-schema.readthedocs.io/en/latest/format_description.html#storing-time-values)):
> For fields with a recommended size, larger or smaller sizes can be used (and for integer types both signed and unsigned), so long as the selected size encompasses the full range of data, and for floats, without loss of significant precision. Fields that have a minimum size can use larger, but not smaller sizes.

**Comment by tjd2002** [comment]
I agree with @bendichter that the best solution would be to convert this to 'numeric'.

Also, note that ImageSeries already has a 'resolution' field which seems redundant with 'bits_per_pixel', and is used for lots of other data types.

Given that 'bits_per_pixel' seems to be confusing, and redundant with 'resolution', and also will not be applicable once we switch to a generic 'numeric' type (it's not meaningful to specify bits per pixel for floating point data), can I propose that we remove this field for NWB 2.0?

Current description for 'resolution' field is:

```
Resolution: 

Smallest meaningful difference between values in data, stored in the specified by unit.

Comment: E.g., the change in value of the least significant bit, or a larger number if signal noise is known to be present. If unknown, use -1.0```

**Comment by ageorgou** [comment]
I'm not sure that the `resolution` field makes sense for integer data, at least with the current description: the meaningful difference will always be 1. `bits_per_pixel` can indicate both range (for integers and floating-point numbers) and precision (for floats only).

**Comment by tjd2002** [comment]
Well, once the underlying bug you identified is fixed, then the number of bits per pixel, and the representation (signed/unsigned int, floating point) can be determined just by inspecting the type of the data that is returned. (I.e. int8 will be stored as int8, uint32 will be stored as uint32...). Allowing the user to specify that as metadata seems ill-advised (and is not something we do anywhere else as far as I am aware).

[EDIT: removed some erroneous stuff about truncation]

**Comment by tjd2002** [comment]
I think the intended use of the 'bits_per_pixel' field is *not* as a hint about what dataype to use for storage, but rather to capture the fact that the stored data does not make use of the full bit depth of the representation. For example, if you have a camera that returns 12 bits-per-pixel data, but you are storing those frames as uint16, you'd like to know the maximum value.

The current description for this field ("Number of bit per image pixel") is not clear about this, but this meaning is clear elsewhere in the code base where 'bits_per_pixel' is specified:
https://github.com/NeurodataWithoutBorders/pynwb/blob/dea07228b48bde3441338f7b1e0a4b2021df96fe/src/pynwb/retinotopy.py#L22-L24

So, I think we should be explicit about this in the docs, for sure. 

If we decide to allow floating-point values, it's not clear to me how we'd interpret a 'bits_per_pixel' in an analogous way. For example, if the data is stored as, e.g. a float32, I wouldn't know how to interpret a 'bits_per_pixel' value of '28' (should I truncate the significand??).

If it is important to specify the maximum value that the data can take, and we want to support both integer and FP numbers (and also handle the situation where a 'conversion' factor is supplied !), then I think it would be less confusing to  'maximum_value' (specified in units) or something like that. 

If we just want to fix the current issue where only ints are allowed, then just updating the docs should be sufficient.

**Comment by jonc125** [comment]
Any chance of getting the truncation at least fixed for NWB2.0 final, so we can store `int16` or `int32` data here?

**Comment by ajtritt** [comment]
Todo:

- [x] deprecate bits_per_pixel
- [x] fix int16 -> int8 conversion bug

**Comment by ajtritt** [comment]
relates to #698
