### ISSUE TITLE
Prevent misuse of NWBHDF5IO vs HDF5IO

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#741]
### Steps to Reproduce
```
$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pynwb
>>> io = pynwb.NWBHDF5IO("tests/reference_abf/2018_03_20_0008.nwb")
>>> nwb = io.read()
>>> io = pynwb.HDF5IO("tests/reference_abf/2018_03_20_0008.nwb")
>>> nwb = io.read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\backends\io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\build\map.py", line 190, in construct
    result = self.__type_map.construct(builder, self)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\build\map.py", line 1397, in construct
    attr_map = self.get_map(builder)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\build\map.py", line 1326, in get_map
    data_type = self.get_builder_dt(obj)
  File "e:\projekte\pynwb\src\pynwb\form\utils.py", line 375, in func_call
    return func(self, **parsed['args'])
  File "e:\projekte\pynwb\src\pynwb\form\build\map.py", line 1234, in get_builder_dt
    raise ValueError(msg)
ValueError: builder 'root' does not have a data_type
>>>
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Anaconda 4.2.0 (64-bit)|
- **Python Version:** Python 2.7.12 |
- **Operating System:** Windows 7  64bit
- **Pynwb Version:** 6683635c (add list comprehension for reading references in an array after file <E2><80><A6> (#740), 2018-11-19)

### Problem/Use Case

It is too easy to misuse HDF5IO as it is too similiar to NWBHDF5IO.

### Example file
[2018_03_20_0008.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/2600135/2018_03_20_0008.zip)

**Comment by bendichter** [comment]
I agree. How would you recommend we rectify this?

**Comment by t-b** [comment]
What is the purpose of the two classes? Can we integrate both classes functionality in `NWBHDF5IO`?

**Comment by bendichter** [comment]
It looks like `NWBHDF5IO` is meant to be a more automatic version of `HDF5IO` that automatically loads a manager and (optionally) namespaces

https://github.com/NeurodataWithoutBorders/pynwb/blob/6683635cac7a0d4b6a08c97e6d485acebef194bd/src/pynwb/__init__.py#L189-L229

so I would infer that `HDF5IO` is meant for non-standard cases where these things need to be precisely controlled. Is that right, @ajtritt? What kinds of use-cases would necessitate the use of `HDF5IO`? 

At the very least we could improve that exception message.

**Comment by oruebel** [comment]
I think it becomes a bit clearer if you think of FORM as a separate library (which we plan to make it in the not to distant future). With this in mind ``HDF5IO`` is a generic I/O backend that FORM provides. ``NWBHDF5IO`` is the NWB-specific HDF5 backend. In part this is also, to make sure end users should not have to import classes from FORM directly in order to read/write NWB files.

**Comment by t-b** [comment]
Okay so once FORM is in a separate library that is a non-issue?

**Comment by oruebel** [comment]
> Okay so once FORM is in a separate library that is a non-issue?

I think the answer is yes. However, I think we can take steps now to help along the path. E.g, can we remove HDF5IO from the pynwb namespace, so that ``pynwb.HDF5IO`` does not work but you actually have to do ``pynwb.form.io.backends.h5tools.HDF5IO``? Another part is to make sure that we are using NWBHDF5IO consistently in the galleries.

**Comment by t-b** [comment]
Okay that sounds like a plan. I'll make a PR.
