### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#754]
The last release is from 11/16/2018 and it is misses one important fix 6683635c (add list comprehension for reading references in an array after file <E2><80><A6> (#740), 2018-11-19) to be able to use reference datasets which I'm using for the sweep tables.

**Comment by bendichter** [comment]
@t-b thanks for the nudge. I just pushed a release, which should be active as soon as the CI tests pass

**Comment by t-b** [comment]
@bendichter Thanks for the quick reaction. Very much appreciated.
