### ISSUE TITLE
cannot place CorrectedImageStack in processing module

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#757]
## 1) Bug

I am trying to use the `CorrectedImageStack` neurodata type. I think the most natural place to put it is in a processing module, but I am getting an error when I try to put it there:

```python
from pynwb import NWBFile, TimeSeries
from datetime import datetime
from pynwb.ophys import ImageSeries, CorrectedImageStack
import numpy as np

nwbfile = NWBFile("a file with header data", "NB123A", datetime.now().astimezone())

is1 = ImageSeries(name='is1', data=np.ones((2, 2, 2)), unit='unit',
                  external_file=['external_file'], starting_frame=[1, 2, 3], format='tiff', timestamps=[1., 2.])
is2 = ImageSeries(name='is2', data=np.ones((2, 2, 2)), unit='unit',
                  external_file=['external_file'], starting_frame=[1, 2, 3], format='tiff', timestamps=[1., 2.])
tstamps = np.arange(1.0, 100.0, 0.1, dtype=np.float)
ts = TimeSeries("test_ts", list(range(len(tstamps))), 'unit', timestamps=tstamps)
cis = CorrectedImageStack(is1, is2, ts)

module = nwbfile.create_processing_module('name', 'description')
module.add_container(cis)
```

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/test_env_elecs.py", line 20, in <module>
    module.add_container(cis)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'container' (got 'CorrectedImageStack', expected 'NWBDataInterface')
```

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by oruebel** [comment]
This looks like a bug in the schema. I think CorrectedImageStack should probably have NWBDataInterface as base type. This was probably an oversight when NWBDataInterface was added. You may want to check if other ``neurodata_type_inc: NWBContainer`` may need to be fixed as well, just be safe.

**Comment by bendichter** [comment]
@oruebel ok that's what I thought. Thanks for confirming.
