### ISSUE TITLE
docs: describe observation interval

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#761]
Since observation interval will be a new concept to many users, I think it would be nice to add a paragraph in the docs explaining what they are. @tjd2002, I remember you showing me some figures that might be helpful here

**Comment by tjd2002** [comment]
Will do!

**Comment by oruebel** [comment]
@tjd2002 can you work on this issue before the release?

**Comment by tjd2002** [comment]
Yes. Will do.

**Comment by tjd2002** [comment]
It's already described in the API docs for [add_unit](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/format_release_notes.rst)

And in the [nwb-schema release notes](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/docs/format/source/format_release_notes.rst).

The other place where 'Units' is described is in the NWB basics tutorial. We have added a tutorial on the use of 'obs_intervals' there.
