### ISSUE TITLE
Allow compound data type specification in DatasetSpec

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#77]
To allow table datasets, the *DatasetSpec* class will need to be modified to allow specification of compound types.

The argument *dtype* should be modified to allow a list of DataTypeSpec objects. A DataTypeSpec should hold the data type, label, and documentation about the column.

The following is an example usage of specifying a compound data type

```python
nwb_ds = DatasetSpec(doc='dataset_doc',
                     dtype=[DataTypeSpec(dtype=int, label=neuron_id, doc='a column for neuron ID'),
                            DataTypeSpec(dtype=float, label='voltage', doc='a column for IC voltage')],
                     name='data')
```

**Note:** *NWBDatasetSpec* will also need to be updated to allow these options to be passed through

**Comment by oruebel** [comment]
@ajtritt can this issue be closed?
