### ISSUE TITLE
update HDF5IO to allow writing of compound data types

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#78]
Update `form.backends.hdf5.h5tools.write_dataset` to allow writing of compound data types. 

The *default_dtype* argument should take a list of dictionaries. Each dictionary will have the keys *dtype* and *label*.

**Comment by oruebel** [comment]
Completed in https://github.com/NeurodataWithoutBorders/pynwb/pull/161/files
