### ISSUE TITLE
intermediate-representation integration tests have been deprecated

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#781]
### Problem/Use Case

Integration tests that check intermediate (`test_build` and `test_construct`)data representations have been deprecated (see commit 5da649514d7811b9754e2d2ff917ff66bbf83f1f). The offered very little in the way of debugging and generated more tests to be updated. 

This issue has been created for discussion purposes. 

Relates to #112. 

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by t-b** [comment]
But we do keep the roundtrip tests?

**Comment by bendichter** [comment]
Yes
