### ISSUE TITLE
OptogeneticStimulusSite RT error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#783]
[deleted]

**Comment by bendichter** [comment]
Suspecting that this was due to changes in pynwb, I tried reading the file with an old commit, and got the same error. I'm now looking into doing the same with matnwb.

**Comment by lawrence-mbf** [comment]
I'm running into this error now:
```
Traceback (most recent call last):
  File "c:\...\pynwb-0.6.2\src\pynwb\form\build\map.py", line 984, in construct
    obj = cls(**kwargs)
  File "c:\...\pynwb-0.6.2\src\pynwb\form\utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'device' (got 'str', expected 'Device')
.
.
.
Exception: Could not construct OptogeneticStimulusSite object
```
full log: https://gist.github.com/ln-vidrio/1de2561be635ac93d6d5409f56110364

From what I could tell, there's a deviation between how an OptogeneticStimuluSite stores its devices.  Pynwb expects a Device object while the schema expects text.  I've also been unable to save an simulus site into a test NWB file using pywnb.  I only get a file with just a Device.

**Comment by bendichter** [comment]
Hmm it's possible that the schema changed a bit. I'll look into it

**Comment by bendichter** [comment]
confirmed. This:

```python
from pynwb import NWBHDF5IO, NWBFile
from pynwb.ogen import OptogeneticStimulusSite
from pynwb.device import Device

from datetime import datetime

nwbfile = NWBFile('a', 'b', datetime.now().astimezone())

device = Device(name='dev1')
ogen_stim_site = OptogeneticStimulusSite('stim_site', device, 'my stim site', 300., 'in the brain')

nwbfile.add_device(device)
nwbfile.add_ogen_site(ogen_stim_site)

with NWBHDF5IO('test_out.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test_out.nwb', 'r') as io:
    io.read()
```

does not create a file that has a stimulus site object

**Comment by bendichter** [comment]
@ln-vidrio this fix should do it. However note the change: extraction_lambda is now a float, not a string. You will need to change this in your script as well
