### ISSUE TITLE
DecompositionSeries cannot be added to LFP

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#787]
## 1) Bug

`LFP.add_decomposition_series` does not work. The file created does not contain the `DecompositionSeries` object inside of `LFP`.

### Steps to Reproduce
```python
from pynwb import NWBHDF5IO, NWBFile
from pynwb.misc import DecompositionSeries
from pynwb.ecephys import LFP, ElectricalSeries
import numpy as np
from datetime import datetime

nwbfile = NWBFile('a', 'b', datetime.now().astimezone())

device = nwbfile.create_device(name='trodes_rig123')

electrode_group = nwbfile.create_electrode_group('tetrode1',
                                                 description="an example tetrode",
                                                 location="somewhere in the hippocampus",
                                                 device=device)

for idx in [1, 2, 3, 4]:
    nwbfile.add_electrode(idx,
                          x=1.0, y=2.0, z=3.0,
                          imp=np.nan,
                          location='CA1', filtering='none',
                          group=electrode_group)

electrode_table_region = nwbfile.create_electrode_table_region([0, 2], 'the first and third electrodes')

ephys_ts = ElectricalSeries('test_ephys_data',
                            [1., 2., 3.],
                            electrode_table_region,
                            rate=10.,
                            description="desc")
nwbfile.add_acquisition(ephys_ts)

lfp = LFP()
lfp.add_electrical_series(ephys_ts)
nwbfile.create_processing_module('ecephys', 'ecephys module')


spec_anal = DecompositionSeries(name='LFPSpectralAnalysis',
                                description='my description',
                                data=np.ones((3, 3, 3)),
                                timestamps=np.ones((3,)),
                                source_timeseries=ephys_ts,
                                metric='amplitude')

#nwbfile.modules['ecephys'].add_data_interface(spec_anal)
lfp.add_decomposition_series(spec_anal)
nwbfile.modules['ecephys'].add_data_interface(lfp)

for band_name in ['alpha', 'beta', 'gamma']:
    spec_anal.add_band(band_name=band_name, band_limits=(1., 1.), band_mean=1., band_stdev=1.)

with NWBHDF5IO('test_out.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test_out.nwb', 'r') as io:
    nwb = io.read()
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda or Python
- **Python Version:** Python 2.7 or Python 3.6
- **Operating System:** Windows, macOS or Linux
- **Pynwb Version:** Version of Pynwb used

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by VBaratham** [comment]
Hi @bendichter, just want to make sure I'm using nwb right. Currently I'm only using LFP to store the raw data (an "acquisition" in nwb terms). We consider frequency decomposition to be a processing step, so I think that means I'd want to put DecompositionSeries into a processing module, rather than store it alongside the raw dataset that it came from (there's still a reference to the raw dataset as the `source_timeseries` attribute of the DecompositionSeries). How does this sound to you?

**Comment by bendichter** [comment]
@VBaratham There are a few different issues here. If you refer to what comes from the acquisition system as "LFP," then it belongs in acquisition. Some labs store what they call "raw" data at high sampling rate and then also have "LFP" data that is a downsampled and filtered version of the "raw" data. In this case, I would put the "raw" data in `/acquisition` and the "LFP" data in `/processing/ecephys/LFP` (I use namespace module names as processing module names as a convention, thus the processing module named "ecephys"). So the `LFP` interface could go in acquisition or in a processing module depending on how the data is structured in your lab. 

When we created the `DecompositionSeries` object, there was some discussion as to whether it should be able to go within the `LFP` object. As you rightly point out, `DecompositionSeries` should be in a processing module, so that would in some cases require a second `LFP` interface (this I think is the confusing part). However the point is a bit moot currently because I haven't figured out how to get `LFP` to accept both `ElectricalSeries` and `DecompositionSeries` objects and, as you rightly pointed out, doing so is not necessary, since the `DecompositionSeries` already contains a reference to the LFP data through `source_timeseries`, so I have been putting `DecompositionSeries`  objects directly into the processing module, without wrapping them in an `LFP` interface. Given your confusing maybe it's best if it stays that way.

Sorry for the confusion. Does that help?

**Comment by VBaratham** [comment]
Ah thanks, this does help. As long as I can use DecompositionSeries into a processing module, I'm happy!
