### ISSUE TITLE
Data type promotion favours always 64bit floats

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#795]
Using 29c2fb6b (Merge pull request #793 from NeurodataWithoutBorders/bug/final_cleanup, 2019-01-16)
I"m getting really large files as floats are always saved as 64bit ones. With an earlier version b10d8781 (Merge pull request #784 from NeurodataWithoutBorders/fix_opto_stim_site, 2019-01-14) I did not had that problem.

Screenshot (top is new, bottom is old):

![grafik](https://user-images.githubusercontent.com/1185677/51331442-0f81ae00-1a7a-11e9-8e13-d56d49488d1e.png)

I can share the NWBs if required.

**Comment by ajtritt** [comment]
This is part of the schema logic. The specified precision is a *minimum* precision. This means users can pass in a higher precision than what is specified. So, if you pass in a 64-bit float where a 32-bit float is specified, the API assumes you are requesting higher precision. I suspect you are now seeing this because we had not imposed this logic prior to eba93749a66ea2607a10029cac67b9d4e25a73a1. Additionally, Python uses 64-bit floats by default. Are you using Python's default floats, or are you passing in 32-bit floats that get converted to 64-bit floats?

**Comment by t-b** [comment]
@ajtritt Thx. I'll investigate.

**Comment by t-b** [comment]
@ajtritt Got it.

No bug here I just was accustomed to the old behaviour.

For playing around I've used

```python
from pynwb import NWBHDF5IO
from pynwb import TimeSeries
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile

import numpy as np

start_time = datetime(2017, 4, 3, 11, tzinfo=tzlocal())
create_date = datetime(2017, 4, 15, 12, tzinfo=tzlocal())

nwbfile = NWBFile('demonstrate NWBFile basics', 'NWB123', start_time,
                  file_create_date=create_date)


test_ts_fp32 = TimeSeries('test_timeseries_fp32', np.ones(5, dtype=np.float32), 'SIunit', rate=1.0)
test_ts_fp64 = TimeSeries('test_timeseries_fp64', np.ones(5, dtype=np.float64), 'SIunit', rate=1.0)

nwbfile.add_acquisition(test_ts_fp32)
nwbfile.add_acquisition(test_ts_fp64)

io = NWBHDF5IO('basic_example.nwb', mode='w')
io.write(nwbfile, cache_spec=True)
io.close()
```

and this gives

```
 h5dump -pH basic_example.nwb  | grep -A100 test_timeseries | grep -A 20 \"data\"
        DATASET "data" {
           DATATYPE  H5T_IEEE_F32LE
           DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
           STORAGE_LAYOUT {
              CONTIGUOUS
              SIZE 20
              OFFSET 7360
           }
           FILTERS {
              NONE
           }
           FILLVALUE {
              FILL_TIME H5D_FILL_TIME_IFSET
              VALUE  0
           }
           ALLOCATION_TIME {
              H5D_ALLOC_TIME_LATE
           }
           ATTRIBUTE "conversion" {
              DATATYPE  H5T_IEEE_F64LE
              DATASPACE  SCALAR
-
        DATASET "data" {
           DATATYPE  H5T_IEEE_F64LE
           DATASPACE  SIMPLE { ( 5 ) / ( 5 ) }
           STORAGE_LAYOUT {
              CONTIGUOUS
              SIZE 40
              OFFSET 7312
           }
           FILTERS {
              NONE
           }
           FILLVALUE {
              FILL_TIME H5D_FILL_TIME_IFSET
              VALUE  0
           }
           ALLOCATION_TIME {
              H5D_ALLOC_TIME_LATE
           }
           ATTRIBUTE "conversion" {
              DATATYPE  H5T_IEEE_F64LE
              DATASPACE  SCALAR
```

Sorry for the noise.
