### ISSUE TITLE
Bail out in @docval if a duplicated parameter name is used

### ISSUE THREAD

**Issue by t-b** [NeurodataWithoutBorders/pynwb#806]
This would prevent problems like #805.

**Comment by ajtritt** [comment]
this should move here: https://github.com/hdmf-dev/hdmf

**Comment by t-b** [comment]
@ajtritt You can nowadays move issues in github. But I can't.

**Comment by bendichter** [comment]
It looks like you can't move issues between organizations. I'll move this to hdmf manually
