### ISSUE TITLE
Round Trip Integration Tests Don't Check Array Contents.

### ISSUE THREAD

**Issue by lawrence-mbf** [NeurodataWithoutBorders/pynwb#815]
### Steps to Reproduce
Note: This is all under `pynwb\tests\integration\ui_write\base.py` where pynwb is wherever the repository lives.
The environment was created following the tutorial for running tests in pynwb (https://pynwb.readthedocs.io/en/stable/getting_started.html#installation)

[Relevant MatNWB Issue](https://github.com/NeurodataWithoutBorders/matnwb/issues/106#issuecomment-461572136)
1) `TestMapNWBContainer.assertContainerEqual()` expects the first argument to be the _actual_ read data and the second argument to be the _expected_ data.  This is flipped in the subclass `TestMapRoundTrip` when `assertContainerEqual` is called at the end of `test_roundtrip()`.
2) Fixing the above inconsistency revealed that h5py.Dataset classes are not accounted for when validation occurs.  The error message snippet looks like this:
```
FAIL: test_roundtrip (ui_write.test_base.TestTimeSeriesIO) (container_type='TimeSeries', nwbfield='data')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "...\pynwb\tests\integration\ui_write\base.py", line 129, in assertContainerEqual
    self.assertEqual(f1, f2)
AssertionError: <HDF5 dataset "data": shape (10,), type "<i4"> != [100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
```
The reason why this didn't break tests earlier was because if the first argument is array data, then it will only validate if its contents are NWBContainers or NWBData.  In the expected data, the contents were numeric.
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Miniconda
- **Python Version:** Python 3.7.1
- **Operating System:** Windows 10
- **Pynwb Version:** origin/dev f21aa5d8

**Comment by bendichter** [comment]
Thanks @ajtritt!

@ln-vidrio this bug has been fixed in the latest dev.
