### ISSUE TITLE
Incorrect type for 'keywords' - saved as string

### ISSUE THREAD

**Issue by filippomc** [NeurodataWithoutBorders/pynwb#837]
Hi, I'm encountering this error while saving and reloading a simple file with the last pynwb dev.
`TypeError: incorrect type for 'keywords' (got 'str', expected 'ndarray, list, tuple, Dataset, AbstractDataChunkIterator or FORMDataset')`

The file has been created through this code snippet:

```Python
def create_time_series_file():
    start_time = datetime(2019, 1, 1, 11, tzinfo=tzlocal())
    create_date = datetime.now(tz=tzlocal())

    nwbfile = pynwb.NWBFile('Example time series data',
                            'TSD',
                            start_time,
                            file_create_date=create_date,
                            notes='Example NWB file created with pynwb v%s' % pynwb.__version__,
                            experimenter='Experimenter',
                            experiment_description='Add example data',
                            institution='My institution',
                            keywords=['Test', 'Data'])

    timestamps = [i / 1000.0 for i in range(2000)]
    data = [math.sin(t / 0.05) for t in timestamps]

    test_ts = pynwb.TimeSeries('test_sine_timeseries', data, 'SIunit', timestamps=timestamps)

    nwbfile.add_acquisition(test_ts)
    return nwbfile
```

If I remove the 'keywords' specification i can load the file.
Looking at the debugger when loading the file I can see that the array provided in the constructor is being loaded as the string 
`"['Test', 'Data']"`

Thanks

**Comment by bendichter** [comment]
Thanks for bringing this to our attention. I'll look into this asap

**Comment by ajtritt** [comment]
If we look at the specification, it says `keywords` should be written as a 1D dataset of text (i.e. unicode strings).
https://github.com/NeurodataWithoutBorders/pynwb/blob/0c1a8497889b18cda85926606a138621ed1f496c/src/pynwb/data/nwb.file.yaml#L164-L169

From the what is shown of the error message, it looks like the data is being passed to the constructor as a string. This suggests one of two problems:

1) `keywords` is being written as a scalar unicode dataset 
2) `keywords` is being written properly, but is somehow getting converted to a string.

**Comment by bendichter** [comment]
Looking at the data in HDFView, it's 1. `keywords` is being written as a scalar unicode dataset.
