### ISSUE TITLE
file.analysis and file.get_analysis cannot access BehavioralTimeSeries

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#845]
## 1) Bug

Cannot access analysis (write works fine).

### Steps to Reproduce
```
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.behavior import BehavioralTimeSeries
import numpy as np
import datetime

filename = "./debug.nwb"

nwbfile_out = NWBFile(
    session_description='test foraging2',
    identifier='behavior_session_uuid',
    session_start_time=datetime.datetime.now(),
    file_create_date=datetime.datetime.now(),
)

ts1 = TimeSeries(
    name='1',
    data=np.random.rand(5),
    timestamps=np.random.rand(5), 
    unit='s'
)

ts2 = TimeSeries(
    name='2',
    data=np.random.rand(5),
    timestamps=np.random.rand(5), 
    unit='s'
)

running_bts = BehavioralTimeSeries(name='running')
nwbfile_out.add_analysis(running_bts)

running_bts.add_timeseries(ts1)
nwbfile_out.add_acquisition(ts2)

with NWBHDF5IO(filename, mode='w') as io:
    io.write(nwbfile_out)

nwbfile_in = NWBHDF5IO(filename, mode='r').read()
assert len(nwbfile_in.acquisition) == 1 # WORKS
assert len(nwbfile_in.analysis) == 1 # DOESNT WORK
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** Ubuntu
- **Pynwb Version:** HEAD as of 12 March 2019 (0c1a8497889b18cda85926606a138621ed1f496c)

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
reproduced

**Comment by bendichter** [comment]
Thanks for the bug report, @nicain. I'll look into this.
