### ISSUE TITLE
docs: Update conda package release instructions 

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#848]
Since conda-forge now has an `Autoticking Bot` creating a PR on the [pynwb-feedstock](https://github.com/conda-forge/pynwb-feedstock/), the corresponding instructions [make_a_release.rst](
https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/source/make_a_release.rst) should be updated to mention a PR is expected. 

That said, we should keep the details instructions in case the bot failed (e.g because of GH rate limitation)

References:
* https://justcalamari.github.io/jekyll/update/2018/06/11/introduction.html
* https://github.com/regro/cf-scripts

**Comment by stephprince** [comment]
The release instructions were updated to describe the `regro-cf-autotick-bot` and keep the manual instructions with https://github.com/NeurodataWithoutBorders/pynwb/pull/1560
