### ISSUE TITLE
Look into rever for simplifying release process

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#849]
The software release process is still quite manual. There is a tool called _rever_ for standardizing and automating the process. Lets look into this to see if it can help simplify the process:
https://regro.github.io/rever-docs/

**Comment by yarikoptic** [comment]
FWIW, we are using [auto](https://github.com/intuit/auto) for dandi-cli .  https://github.com/dandi/dandi-cli/blob/master/DEVELOPMENT.md#releasing-with-github-actions-auto-and-pull-requests . Quite neat

**Comment by rly** [comment]
@yarikoptic auto looks very useful. I'll do some testing.

**Comment by stephprince** [comment]
For the most part the release process has been automated with https://github.com/NeurodataWithoutBorders/pynwb/pull/1560
