### ISSUE TITLE
AnalysisModule for storing NWBData or NWBContainer

### ISSUE THREAD

**Issue by maxdougherty** [NeurodataWithoutBorders/pynwb#860]
## Feature Request
I would like an `AnalysisModule` for storing both `NWBData` and `NWBContainer` objects. Ideally with a function analogous to `add_electrical_series` for storing arbitrary ndarrays in Analysis. 

Currently, `NWBFile.add_analysis()` does not accept an `NWBData` object. 
```python
from datetime import datetime
import numpy as np
from pynwb import NWBFile, NWBHDF5IO

nwbfile = NWBFile('aa', 'aa',  datetime.now())
test_mat = np.arange(25).reshape(5,5)
test_data = NWBData('bb', test_mat)
nwbfile.add_analysis(test_data)

with NWBHDF5IO('testfile.nwb', 'w') as io:
    io.write(nwbfile)
```

### Problem/Use Case
I would like to cache intermediate datasets used in several analysis pipelines to avoid expensive recomputing. Storing these in Analysis, would also remove the need to write external files, simplifying the process of sharing analysis.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
Hey @maxdougherty,
Can you give a little more context as to what types of data you'd like to store? Would it be possible to create an NWB neurodata_type for this data? Without knowing the specific details, I'd be concerned about encouraging storage of plain arrays because you would not have any way to indicate what dimensions of the array mean.

**Comment by maxdougherty** [comment]
Sure @bendichter,
One example is the baseline mean and standard deviation for `DecompositionSeries` data. Which would be a (channels, frequency_bin) sized array. This takes ~8 minutes to compute for a 192 channel 24 minute recording. Another example would be the computed receptive fields for each channel, a (channels,stim_param1, stim_param2,...) size array. And I may want to have several of these RF datasets from a variety of analyses. 

Regarding dimension labeling, I did not intend for these datasets to be utilized independently, but rather as a cache for specific analysis. Then I can send the .nwb file and an analysis/plotting script to let someone reproduce analytical results in a reasonable amount of time.

**Comment by bendichter** [comment]
@maxdougherty So far the philosophy has been to have users either follow the prescribed data objects or specify their own with extensions. My worry is that if we allow undocumented data we'll open the gates for a whole lot of data to be stored this way and we'll be back where we started. I totally understand that the workflow for extensions is cumbersome during development. Would it be possible to ease the workflow of extensions to the point where it would be reasonable to use them for this context?

**Comment by bendichter** [comment]
So this is a bit of a clunky solution but the best I can do right now is 

1) Create an extension that defines a NWB container that contains a dataset
```python
from pynwb.spec import NamespaceBuilder, NWBGroupSpec

name = 'single_dataset'
doc = 'example extension for single dataset'

ns_builder = NamespaceBuilder(doc=doc, name=name, version='0.1',
                              author=['author'],
                              contact='email')

ns_builder.include_type('NWBDataInterface', namespace='core')

my_dataset_container = NWBGroupSpec(neurodata_type_inc='NWBDataInterface', neurodata_type_def='MyDatasetContainer',
                                    doc='doc')
my_dataset_container.add_attribute(name='help', doc='doc', dtype='text', default_value='help text here')
dataset = my_dataset_container.add_dataset(name='my_dataset', doc='doc', dtype='float', shape=(None, 12),
                                           dims=('runs', 'params'))
dataset.add_attribute(name='help', doc='doc', dtype='text', default_value='help text here')


ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'

# Export
ns_builder.add_spec(ext_source, my_dataset_container)
ns_builder.export(ns_path)
```

2) Auto-generate the class from the extension using `get_class`

```python
from pynwb import load_namespaces, get_class
load_namespaces('/Users/bendichter/dev/to_nwb/to_nwb/analysis_dataset/single_dataset.namespace.yaml')

MyDatasetContainer = get_class('MyDatasetContainer', 'single_dataset')
```

3) Write the data to the file, making sure to cache the spec

```python
nwbfile = NWBFile('aa', 'aa', datetime.now().astimezone())

data = np.ones((40, 12))
nwbfile.add_analysis(MyDatasetContainer(name='MyDataset', my_dataset=data))

with NWBHDF5IO('test_cc.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)
```

4) Anyone should be able to read this data using the cached spec to auto-generate the python API

```python
with NWBHDF5IO('test_cc.nwb', 'r', load_namespaces=True) as io:
    nwb2 = io.read()
    print(nwb2.analysis['MyDataset'].my_dataset[:])
```

**Comment by rly** [comment]
See issue #1024 and PR #1027 for new implementation of scratch space for storing arbitrary ndarrays and other NWBData
