### ISSUE TITLE
data in TimeSeries not required or TimeStamps object without data attribute

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#882]
## 2) Feature Request

Ability to create a TimeSeries object without a data attribute, and not throw MissingRequiredWarning.  

### Problem/Use Case
Having a TimeSeries that just provides timestamps, that can be reused to associate timestamps between multiple other TimeSeries objects in the file is very useful.  I would like to make data a non-required arg in the base TimeSeries, or create a TimeStamps object derived from TimeSeries that does not have a data attribute.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
If I understand correctly, your goal is to reuse the timestamps arrays across multiple TimeSeries. However, it is not clear to me why you need to store those timestamps in a separate TimeSeries without data. To reuse timestamps, I think the proper solution would be to save the timestamps with one of the TimeSeries and to have links in the others.

**Comment by nicain** [comment]
> I think the proper solution would be to save the timestamps with one of the TimeSeries and to have links in the others.

This would be fine for me, I just don't know how to do it.  Here is a snippet that summarizes what I tried:

```
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb import ProcessingModule
import numpy as np
import datetime

def nwbfile_factory():
    return NWBFile(session_description='test foraging2',
                   identifier='behavior_session_uuid',
                   session_start_time=datetime.datetime.now(),
                   file_create_date=datetime.datetime.now())

with NWBHDF5IO('f1.nwb', mode='w') as io:
    f1 = nwbfile_factory()
    ts1 = TimeSeries(name='1', data=np.ones(1000), timestamps=np.ones(1000), unit='s')
    f1.add_acquisition(ts1)
    io.write(f1)

with NWBHDF5IO('f2.nwb', mode='w') as io:
    ts1 = TimeSeries(name='1', data=np.ones(1000), timestamps=np.ones(1000), unit='s')
    ts2 = TimeSeries(name='2', data=np.ones(1000), timestamps=np.ones(1000), unit='s')
    f2 = nwbfile_factory()
    f2.add_acquisition(ts1)
    f2.add_acquisition(ts2)
    io.write(f2)

with NWBHDF5IO('f3.nwb', mode='w') as io:
    ts1 = TimeSeries(name='1', data=np.ones(1000), timestamps=np.ones(1000), unit='s')
    ts2 = TimeSeries(name='2', data=np.ones(1000), timestamps=ts1.timestamps, unit='s')
    f3 = nwbfile_factory()
    f3.add_acquisition(ts1)
    f3.add_acquisition(ts2)
    io.write(f3)
```

This results in:

```
-rw-rw-rw- 1 nicholasc nicholasc  31K Apr 12 10:14 f1.nwb
-rw-rw-rw- 1 nicholasc nicholasc  51K Apr 12 10:14 f2.nwb
-rw-rw-rw- 1 nicholasc nicholasc  51K Apr 12 10:14 f3.nwb
```

The problem here is that the size of f2.nwb and f3.nwb is the same, telling me that timestamps were not reused.  How do I get the link made?

**Comment by bendichter** [comment]
you want

```python
with NWBHDF5IO('f2.nwb', mode='w') as io:
    ts1 = TimeSeries(name='1', data=np.ones(1000), timestamps=np.ones(1000), unit='s')
    ts2 = TimeSeries(name='2', data=np.ones(1000), timestamps=ts1, unit='s')
    f2 = nwbfile_factory()
    f2.add_acquisition(ts1)
    f2.add_acquisition(ts2)
    io.write(f2)
```
