### ISSUE TITLE
'help' should be required for schema generator

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#886]
## 1) Bug

When using the schema generator API and generating a new neurodata type, the user needs to add 'help' as an attribute. If they do not, there is a warning, but not until data saved using the extension is read back using pynwb. I would like to either add a warning in the schema generator, or add a check to make 'help' required if `neurodata_type_def` or `neurodata_type_inc` is present.

If you are reporting a bug please provide the following:
### Steps to Reproduce
```python
from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec
from pynwb import NWBHDF5IO, NWBFile
from datetime import datetime
from dateutil.tz import tzlocal

name = 'test_groups'
ns_path = name + ".namespace.yaml"
ext_source = name + ".extensions.yaml"

group_type = NWBGroupSpec(
    neurodata_type_def='Group1',
    doc='doc',
    neurodata_type_inc="NWBDataInterface",
    groups=[
        NWBGroupSpec(doc='doc', neurodata_type_def='Group2', neurodata_type_inc="NWBDataInterface",
                     attributes=[NWBAttributeSpec(name='str_type', dtype='text', doc='doc')])
    ]
)

ns_builder = NWBNamespaceBuilder(name + ' extensions', name)
ns_builder.add_spec(ext_source, group_type)
ns_builder.export(ns_path)


from pynwb import load_namespaces, get_class

load_namespaces(ns_path)
Group1 = get_class('Group1', name)
Group2 = get_class('Group2', name)

group1 = Group1(name='gp1_name', group2=Group2(str_type='hello', name='name'))

nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
test_mod = nwbfile.create_processing_module('test_mod', 'desc')
test_mod.add_data_interface(group1)

fpath = 'test_groups.nwb'
with NWBHDF5IO(fpath, 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO(fpath, 'r') as io:
    nwb = io.read()
    print(nwb.modules['test_mod'].data_interfaces['gp1_name'].group2.str_type)
```

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
`help` is no longer an attribute in nwb schema
