### ISSUE TITLE
Signal decomposition

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#9]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

A typical analysis is to perform a frequency decomposition (or other form of decomposition of signals), e.g,. of electrical recordings of the brain. This kind of analysis results in a timeseries with an additional dimension to represent the bands/features the signal is decomposed into. A possible target for this is FilteredEphys, but, e.g., the ElectricalSeries does only allow for 2D data.

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/9

**Comment by oruebel** [comment]
This issue should be discussed on the nwb-schema issue tracker. I've created a new issue here:
 https://github.com/NeurodataWithoutBorders/nwb-schema/issues/46
