### ISSUE TITLE
validator erroneously passing files with extensions

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#908]
### Steps to Reproduce
```bash
python -m pynwb.validate EC125.nwb
```
on [this file](https://drive.google.com/file/d/1Tj-beQb1_6hWalCYPXGYggCBdUFv0933/view?usp=sharing) should throw an violation because EC125.nwb contains a neurodata_type defined in the ecog NDX. It should require:

```bash
python -m pynwb.validate -p ecog.namespace.yaml  EC125.nwb
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** macOS
- **Pynwb Version:** latest

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
https://drive.google.com/file/d/1Tj-beQb1_6hWalCYPXGYggCBdUFv0933/view?usp=sharing

**Comment by t-b** [comment]
This could be solved with my changes in #944.

**Comment by t-b** [comment]
@bendichter Could you retry with latest dev?

**Comment by bendichter** [comment]
@t-b thanks for the nudge. I'm working on this now.

**Comment by t-b** [comment]
Isn't that here the same as what I complained about in #942?

**Comment by bendichter** [comment]
Looks like it

**Comment by t-b** [comment]
Good, closing as duplicate of #942.
