### ISSUE TITLE
Minor documentation issues:

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#91]
1) In the Creating TimeSeries section, after the ephys_ts line, there is:
    f.add_raw_timeseries(ts, [ep1, ep2])
I think it should be this to match:
    f.add_raw_timeseries(ephys_ts, [ep1, ep2])

2) Typo in “Using Extensions” section:
    exentsion
@wbwakeman

**Comment by nicain** [comment]
@jhyearsley Since you have a good workflow for taking down doc bugs, can you squash this?

**Comment by jhyearsley** [comment]
Sure thing.
