### ISSUE TITLE
Improve docs and api names for processing modules and other containers

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#941]
## 2) Feature Request

"What is a processing module?"
"What is a data interface?"

These are terms that some users at the hackathon were confused and intimidated by. Either we should explain them more clearly and earlier in the tutorials or rename them to something more approachable to neuroscientists. For example, representing processing modules as folders is pretty intuitive and showing a pictoral representation of an `NWBFile` being a container (or folder) with properties and nested containers would be helpful. 

Also I think renaming `nwbfile.module['my_module_name'].add_data_interface(my_elec_series)` to `nwbfile.processing['my_module_name'].add(my_elec_series)` would be a lot easier for new users to understand.

Relatedly, in the documentation, I think showing multiple options for creating and adding a new field to a container is confusing, e.g. `addProcessingModule` and `createProcessingModule`. Same for getting data, e.g. `nwbfile.module[name]` and `nwbfile.getProcessingModule(name)` (it is also confusing that the naming in this example breaks the convention of `nwbfile.field` == `nwbfile.getField`)

**Comment by bendichter** [comment]
I agree `nwbfile.processing['my_module_name'].add(my_elec_series)` is nicer.
