### ISSUE TITLE
Enforce dimensions order of data for acquisition in pynwb.file.NWBFile()

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/pynwb#960]
## 2) Feature Request
For TimeSeries added with `add_acquisition` method of `NWBFile()` class, users can store numpy arrays with any dimensions order, e.g. [num channels] [num times]. It would be interesting to enforce consistency here with, for example, ecephys.ElectricalSeries().

According to [documentation for ecephys.ElectricalSeries()](https://pynwb.readthedocs.io/en/stable/pynwb.ecephys.html#pynwb.ecephys.ElectricalSeries), the recommended format for `data` is:
TimeSeries::data array structure: [num times] [num channels] (or [num_times] for single electrode)

A reproducible snippet:
```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, TimeSeries, NWBHDF5IO
import numpy as np

nSamples = 1000
nChannels = 10

# Create a new NWB file
start_time = datetime(2017, 4, 3, 11, tzinfo=tzlocal())

nwb = NWBFile(session_description='demonstrate NWBFile basics',
              identifier='NWB123',  
              session_start_time=start_time)  

# Add signal
X_data = np.zeros((nChannels,nSamples))          # <--- This should not pass
#X_data = np.zeros((nSamples,nChannels))        # <--- This should be enforced
timestamps = list(range(nSamples))
test_ts = TimeSeries(name='test_timeseries', data=X_data, unit='s', timestamps=timestamps)
nwb.add_acquisition(test_ts)

# Add electrode groups and channels
dev0 = nwb.create_device(name='dev0')
elec_group0 = nwb.create_electrode_group(name='electrodes', description='', location='', device=dev0)
for i in np.arange(nChannels):
    ii = float(i)
    nwb.add_electrode(x=ii, y=ii, z=ii, imp=ii, location='', filtering='', group=elec_group0)

# Save file
io = NWBHDF5IO('example_file.nwb', mode='w')
io.write(nwb)
io.close()

# Now open the file and check it's content
with NWBHDF5IO('example_file.nwb', 'r') as io:
    nwb = io.read()
    print('Data shape: ', nwb.acquisition['test_timeseries'].data.shape)
    print('Electrodes: ', nwb.electrodes['x'][:].shape)
```

this prints:
```
Data shape:  (10, 1000)
Electrodes:  (10,)
```

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by oruebel** [comment]
I agree that some warnings would be useful here, but I don't think we will be able to detect this issue in all cases, simply because we can at best figure out the shape but not the semantics of dimensions when we are handed a numpy array or list. E.g., when only a sampling rate and start time are given, we can't know how long the time dimension should be. That being said, if timestamps are given one could add a check and issue a warning when timestamps and the first dimension of data do not align. I think this issue will be addressed by #626.

**Comment by luiztauffer** [comment]
I was thinking that a cross-check with other fields, such as electrodes, could do the work. But of course, this would be limited to just some cases. Another option would be to have explicit input arguments such as numberBins, numberChannels, numberPixels, etc… I guess it’s along the lines of #626 , like you said! Indeed, the semantics of dimensions in data seems like too broad of a problem to be easily solved.

Explicit orientation at the documentation would be already quite helpful, though!

**Comment by oruebel** [comment]
I agree that it is useful to check for and provide help avoid these errors. You mentioned also "Explicit orientation at the documentation..." Did you have any particular parts of the documentation in mind where it would be helpful to provide additional guidance on this?

**Comment by luiztauffer** [comment]
Take, for instance, the example of [pynwb.ecephys.LFP.create_decomposition_series](https://pynwb.readthedocs.io/en/stable/pynwb.ecephys.html#pynwb.ecephys.LFP.create_decomposition_series). At the field `data` it is explicit the order of data dimensions. As someone not fluent in NWB, this definitely helped me structure my code.

I believe that if the same line *– dims: num_times * num_channels * num_bands*, or similar, would be present, for example, at [TimeSeries](https://pynwb.readthedocs.io/en/stable/pynwb.base.html#pynwb.base.TimeSeries) documentation, it would be nice.

**Comment by oruebel** [comment]
@luiztauffer thanks for the suggestion. I created issue #965 for the documentation issue. 

Do you think we can close this issue in favor of #626 and #965

**Comment by luiztauffer** [comment]
Yes of course. Thanks for the feedback!
