### ISSUE TITLE
NWBFile.session_start_time is not in __nwbfields__

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#964]
I'm not quite sure why it is omitted from the `__nwbfields__` list. I also don't quite understand how it is written to disk without being a member of the list. Is this field somehow special? 

## Checklist

- [ ] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [ ] Have you included a brief and descriptive title?
- [ ] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by tjd2002** [comment]
Possibly relevant issue: https://github.com/NeurodataWithoutBorders/nwb-schema/issues/49

There is some special handling of `session_start_time` / `timestamps_reference_time` in pynwb (i.e. default value of s_s_t is set to t_r_t if set, I think)

**Comment by bendichter** [comment]
It's the other way around- t_r_t is set to s_s_t by default. This does touch those items but doesn't quite explain why s_s_t isn't in `__nwbfields__`. It wasn't removed in that PR.

**Comment by tjd2002** [comment]
Most likely it is just an oversight that it's not in that list.

I guess s_s_t is included because it's defined with the `@property` decorator. According to the docs on `__nwbfields__` (https://pynwb.readthedocs.io/en/stable/building_api.html#nwbfields), that is what that list is for (convenience function to define properties for you).

**Comment by tjd2002** [comment]
(here: https://github.com/NeurodataWithoutBorders/pynwb/blob/e9bf8d548dad6d6fa6046697e26d1b9eb1083be6/src/pynwb/file.py#L398-L400)

**Comment by bendichter** [comment]
ah ok, that makes sense. It looks like an oversight then.
