### ISSUE TITLE
spec cache naming

### ISSUE THREAD

**Issue by ukos-git** [NeurodataWithoutBorders/pynwb#972]
Current spec cache looks like this:

```console
GROUP "/specifications" {
   GROUP "core" {
      GROUP "2.0.1" {
         DATASET "namespace" {
            DATATYPE  H5T_STRING {
               STRSIZE H5T_VARIABLE;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
            DATASPACE  SCALAR
            DATA {
            (0): ""
            }
         }
```

This approach implicitly allows more than one version specification. I would have expected an attribute with the version here to avoid two contrary specifications being added to the nwb file.

**Comment by ukos-git** [comment]
i just realized that this is handled over at hdmf.

Also seems like the latest version is used to validate if more than one version is found. Not sure if this will use alphabetically sorted latest version or last added version.

https://github.com/hdmf-dev/hdmf/blob/8ddc8574123853215a4d6c43d27bd2aec908017d/src/hdmf/backends/hdf5/h5tools.py#L84-L92

**Comment by t-b** [comment]
@ukos-git Looking at http://docs.h5py.org/en/stable/high/group.html gives

```
By default, objects inside group are iterated in alphanumeric order. However, if group is created with track_order=True, the insertion order for the group is remembered (tracked) in HDF5 file, and group contents are iterated in that order. The latter is consistent with Python 3.7+ dictionaries.
```

so there are edge cases where the current code fails with multiple namespaces present.
