### ISSUE TITLE
add NWBFile copy method

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#992]
## 2) Feature Request
Add ability to do a soft copy of an NWBFile. Any existing objects in the NWBFile should be linked to from the new copy.

## Checklist

- [X] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [X] Have you included a brief and descriptive title?
- [X] Have you included a clear description of the problem you are trying to solve?
- [X] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [X] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by luiztauffer** [comment]
Hi, actually a 'hard copy' method would be highly desirable as well, without links, just copying the user requested groups
